### ISSUE TITLE
Add ability to have subdirectories under Targets and modules folder

### ISSUE THREAD

**Issue by EricZimmerman** [EricZimmerman/KapeFiles#102]
and then be able to reference things in a tkape file like:

Targets\508\Eventlogs.tkape

Targets\500\LnkFiles.tkape

and so on.

additionally, KAPE should look for a target in all subdirectories except !Disabled

@mark-hallman, does this make sense based on what we were talking about?

**Comment by mark-hallman** [comment]
Yep, that sounds right.
  

  
  

  
  
>

**Comment by EricZimmerman** [comment]
Sync needs to respect this as well

**Comment by EricZimmerman** [comment]
download zip
unzip

1. scan local files, looking for any duplicate IDs.
	if any dupes are found, move BOTH files to !DupeID directory (which should be ignored)

2. scan existing files, record full path and ID in dictionary
3. scan new files, record full path and ID in dictionary

4. for download files, verify directories as they exist in download tree exist in main tree

5. for download files, for each id, look thru existing files and move them to new directory as needed

6. for new files, replace any existing files in existing files, tracking new vs modified

report as normal

Notes
dictionary should be string,string, key is ID, value is full path

we know basedir for existing configs and new configs, so strip that as needed for comparisons

**Comment by EricZimmerman** [comment]
make it a generic function so it can be used for modules and targets

**Comment by EricZimmerman** [comment]
feature request: -tlist foo shows targets under the foo\ directory, e.g. -tlist FileSystem shows all FileSystem targets

tlist will take a string. empty shows Targets dir, else if supplied string exists, list those.

**Comment by EricZimmerman** [comment]
allow doing something like:

--target SomeDir\target

where target.tkape lives in SomeDir

**Comment by EricZimmerman** [comment]
now this works

.\kape.exe --msource C:\temp\tout\ --mdest C:\temp\mout --mflush --module RECmd,arpcache
or
.\kape.exe --tsource c --target registryHives,filesystem,chrome --tdest C:\temp\tout\ --tflush
even tho those targets are in a directory
it finds them
you could also use one of the dir names in the target or module list and it pulls in all files under that dir
like a quick compound target
