### ISSUE TITLE
Have difficulty getting a module to work with --mvars

### ISSUE THREAD

**Issue by mark-hallman** [EricZimmerman/KapeFiles#104]
#########################
This is an RDP Event Log KAPE chain I am building.  I want to collect event logs that contain RDP related entries and the only process the event_ids relevant to RDP activicty with EvtxECmd.  This will require the use of --mvars to pass in the list of event_ids.

Target portion works. 

Using --mvars to pass in a list of event_id to include
#########################

#########################
Complete KAPE Command line
#########################
kape --tsource G --target EventLogs-RDP --tdest f:\kape_out\rdp_evtx --tflush --module EvtxECmd-RDP --mdest f:\kape_out\rdp_evtx_out --mflush --mvars "evtx_id:4624,4625,4634,4647,4778,4779,21,22,23,24,25,261,1149"

#########################
module command line:  
#########################
        Executable: EvtxECmd\EvtxECmd.exe
        CommandLine: -d %sourceDirectory% --csv %destinationDirectory% --inc %evtx_id% 
        ExportFormat: csv
    -

#########################
Problem:  KAPE ia only picking up the first event_id in the list.  
#########################

This works: evtxecmd -d F:\kape_out\rdp_evtx --csv c:\kape_out\evtxecmd_out --inc 4624,4625,4634,4647,4778,4779,21,22,23,24,25,261,1149 

#########################
I tried these variations of the command line.  Changing " and ' as well as spaces between the colon or not.
#########################
kape  --msource f:\kape_out\rdp_logs --module EvtxECmd-RDP --mdest f:\kape_out\rdp_evtx_out --mflush --mvars evtx_id:4624,4625,4634,4647,4778,4779,21,22,23,24,25,261,1149 
kape  --msource f:\kape_out\rdp_logs --module EvtxECmd-RDP --mdest f:\kape_out\rdp_evtx_out --mflush --mvars evtx_id: "4624,4625,4634,4647,4778,4779,21,22,23,24,25,261,1149"
kape  --msource f:\kape_out\rdp_logs --module EvtxECmd-RDP --mdest f:\kape_out\rdp_evtx_out --mflush --mvars evtx_id:"4624,4625,4634,4647,4778,4779,21,22,23,24,25,261,1149"
kape  --msource f:\kape_out\rdp_logs --module EvtxECmd-RDP --mdest f:\kape_out\rdp_evtx_out --mflush --mvars evtx_id: '4624,4625,4634,4647,4778,4779,21,22,23,24,25,261,1149'
kape  --msource f:\kape_out\rdp_logs --module EvtxECmd-RDP --mdest f:\kape_out\rdp_evtx_out --mflush --mvars evtx_id:'4625,4625,4634,4647,4778,4779,21,22,23,24,25,261,1149'

#########################
Debug log snippet:
#########################
KAPE directory: C:\Tools\kape
Command line: --msource f:\kape_out\rdp_logs --module EvtxECmd-RDP --mdest f:\kape_out\rdp_evtx_out --mflush --mvars evtx_id:4624,4625,4634,4647,4778,4779,21,22,23,24,25,261,1149 --debug 
Enabled debug messages...
Validating configuration files
67 targets and 95 modules validated successfully
Using Module operations
Processing variable 'evtx_id:4624'
Processing variable '4625'
Unable to process variable '4625'. Skipping...
Processing variable '4634'
Unable to process variable '4634'. Skipping...

**Comment by EricZimmerman** [comment]
im guessing KAPE is expecting the vars separated by a comma, and the comma is breaking things with them being in the event. i can switch the separator for variables to a different character in next version. you have time this week to test it?

**Comment by mark-hallman** [comment]
Yes,  I can turn the testing around quickly.  Thanks for looking into it.

-Mark

**Comment by EricZimmerman** [comment]
sent test build to slack

**Comment by mark-hallman** [comment]
Eric,

I am only using one var so the ^ separator does not come into play in this particular command example.  But whatever you changed fixed the issue.  

Here is the command line:

```kape --tsource G --target EventLogs-RDP --tdest f:\kape_out\rdp_evtx --tflush --module EvtxECmd-RDP --mdest f:\kape_out\rdp_evtx_out --mflush --mvars "evtx_id:4624,4625,4634,4647,4778,4779,21,22,23,24,25,261,1149"```

**Comment by EricZimmerman** [comment]
OK awesome!

can you try to do a var call with more than one, just for kicks and testing ^?

**Comment by mark-hallman** [comment]
A timestamp like --sd for startdate has a problem with the space between the date and time. when not surrounded by quotes

This command line
``` Command line: --msource f:\kape_out\rdp_evtx --module EvtxECmd-RDP --mdest f:\kape_out\rdp_evtx_out --mflush --mvars evtx_id:4624,4625,4634,4647,4778,4779,21,22,23,24,25,261,1149^start_date:2013-08-31 03:43:29 ```

expands and is run like this.

```Running 'EvtxECmd\EvtxECmd.exe': -d f:\kape_out\rdp_evtx --csv f:\kape_out\rdp_evtx_out\EventLogs --inc 4624,4625,4634,4647,4778,4779,21,22,23,24,25,261,1149 --sd 2013-08-3103```

**Comment by EricZimmerman** [comment]
give this a whirl

--mvars "evtx_id:4624,4625,4634,4647,4778,4779,21,22,23,24,25,261,1149^start_date:'2013-08-31 03:43:29'" 

doubles around whole thing, singles around the timestamp

**Comment by EricZimmerman** [comment]
![image](https://user-images.githubusercontent.com/4265254/62573536-45df1900-b864-11e9-85da-e4901f929b33.png)

**Comment by EricZimmerman** [comment]
ok, updating evtxecmd to work with this format now:

-d C:\Temp\event --csv C:\Temp\eventm\EventLogs --inc 4624,4625,4634,4647,4778,4779,21,22,23,24,25,261,1149 --sd 2013-08-31T03:43:29

notice SD basically has no space in it now. the T replaces the space, which fixes things.


EvtxECmd version 0.5.1.0
Author: Eric Zimmerman (saericzimmerman@gmail.com)
https://github.com/EricZimmerman/evtx
Command line: -d C:\Temp\event --csv C:\Temp\eventm\EventLogs --inc 4624,4625,4634,4647,4778,4779,21,22,23,24,25,261,1149 --sd 2013-08-31T03:43:29
Setting Start date to '2013-08-31 03:43:29.0000000'
CSV output will be saved to 'C:\Temp\eventm\EventLogs\20190806203015_EvtxECmd_Output.csv'

**Comment by EricZimmerman** [comment]
full kape command line:

.\kape.exe --target EventLogs-RDP --tsource c --tdest C:\Temp\event --tflush --mdest C:\Temp\eventm --module EvtxECmd-RDP --mflush --debug --mvars "evtx_id:4624,4625,4634,4647,4778,4779,21,22,23,24,25,261,1149^start_date:2013-08-31T03:43:29"

pushing update to evtxecmd if you want to test it

**Comment by EricZimmerman** [comment]
closing this until i hear back

**Comment by mark-hallman** [comment]
Eric,

Sorry for the delay in testing.  The command line now works are expected with multiple variables using the --mvars option.  Very cool.

Now that this is working,  I am going to rework the EvtxECmd-RDP module to include the list of even_id's so that they are not required on the command line.  I think that the list of id's is pretty static and the command could be cleaned up considerably if they are moved into the module.  

So the new command line would be something like this:

```kape.exe --target EventLogs-RDP --tsource c --tdest f:\kape_out\evtx\tdest  --mdest f:\kape_out\evtx\mdest --module EvtxECmd-RDP```

-Mark

**Comment by EricZimmerman** [comment]
sounds good and thanks for confirming
