### ISSUE TITLE
Can't stay connected to KAPE SFTP Server

### ISSUE THREAD

**Issue by mark-hallman** [EricZimmerman/KapeFiles#116]
I have setup a 3 VM's to test using KAPE as an SFTP server.  I have created the config file with a single user.  I start the server with this command:

```kkape --sftpc C:\Tools\KAPE\kape_sftp_config.skape```  

and I get the following.  You will also see the message from my connection and immediate disconnection.

![image](https://user-images.githubusercontent.com/16808320/63137230-ef2bba80-bf9a-11e9-8a51-1d4a85c47e31.png)

From the other computer, I run this KAPE command.

```kape --tsource c --target LnkFilesAndJumpLists --tflush --tdest c:\kape_out\tdest --vhdx $env:ComputerName --module LECmd,JLECmd --mflush --mdest c:\kape_out\mdest  --zm --scs 192.168.62.187 --scp 22 --scu mark --scpw "wizzo123!" ```

I get these messages.

![image](https://user-images.githubusercontent.com/16808320/63137317-5ea1aa00-bf9b-11e9-9bca-94babd24dfb9.png)

I have attached the logs and the config file.  Looks like a locking issue or something similar.  What am I doing wrong?  This command works if I go to my own SFTP server.

[kape_sftp_config.skape.txt](https://github.com/EricZimmerman/KapeFiles/files/3507719/kape_sftp_config.skape.txt)
I had to add the .txt extension so GitHub would take the file. 

[20190816T011749_KAPE_SFTP_Log.txt](https://github.com/EricZimmerman/KapeFiles/files/3507723/20190816T011749_KAPE_SFTP_Log.txt)

**Comment by EricZimmerman** [comment]
the issue is how kape is writing the test file. i have it correct in the targets validation, but the old code was still in module validation.

easy fix and will be done for next release. i can get you a build tomorrow with the fix if you want it for testing

**Comment by EricZimmerman** [comment]
why did you comment out access? just set it to All if you want full permissions

**Comment by mark-hallman** [comment]
Look at the line above.    Kept the other line so I could get back to default if I wanted to.
  

  
  

  
  
>

**Comment by mark-hallman** [comment]
Whatever works for you.    I would like to keep testing.    Thank you!
  

  
  

  
  
>

**Comment by EricZimmerman** [comment]
doh, missed that.

i will send you a build here in a sec

**Comment by EricZimmerman** [comment]
see slack

**Comment by EricZimmerman** [comment]
test build i sent confirmed working on my side on a separate machine. please test and update/close this as necessary

**Comment by mark-hallman** [comment]
Latest build works / corrected issue.  Thanks!

In case anyone is also testing,  here are the commands to start the server on one machine and run kape on another to sftp target and module output to the KAPE server.


Server Side
```kape --sftpc C:\Tools\KAPE\kape_sftp_config.skape```

Collection Side
```kape --tsource c --target LnkFilesAndJumpLists --tflush --tdest c:\kape_out\tdest --vhdx $env:ComputerName --module LECmd,JLECmd --mflush --mdest c:\kape_out\mdest --zm --scs 192.168.62.187 --scp 22 --scu mark --scpw "wizzo123!" ```

Config File - Comments removed
```
# Example KAPE SFTP configuration file
Port: 22
HomeDirectory: C:\temp\sftp\Root
LogDirectory: C:\temp\sftp\Logs
LogLevel: Verbose 
Users:
    -
        UserName: mark
        Password: wizzo123!
        Access: Read|Write|List
        Jail: true
