### ISSUE TITLE
Unhandled Exception - given paths format not supported

### ISSUE THREAD

**Issue by biscegb** [EricZimmerman/KapeFiles#118]
PS F:\SIFT-Lab-Install\kape> kape.exe --tsource 'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01' --target F:\SIFT-Lab-Install\kape\Targets\!ALL --vhdx SANS-SIFT --tdest G:\TeamExercise\dmz-ftp\
KAPE version 0.8.6.2 Author: Eric Zimmerman (kape@kroll.com)

KAPE directory: C:\Forensic Program Files\kape
Command line: --tsource H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01 --target F:\SIFT-Lab-Install\kape\Targets\!ALL --vhdx SANS-SIFT --tdest G:\TeamExercise\dmz-ftp\

Using Target operations
Found 1 targets. Expanding targets to file list...
Target 'Amcache' with Id '13ba1e33-4899-4843-adf1-c7e6b20d759a' already processed. Skipping!
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\System Volume Information' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\$Recycle.Bin' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\RECYCLER' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\System Volume Information' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
Target 'Amcache' with Id '13ba1e33-4899-4843-adf1-c7e6b20d759a' already processed. Skipping!
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
Target 'EventLogs' with Id 'd95784d9-bd1c-472b-aeef-de5d9ecc7aaa' already processed. Skipping!
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Windows\System32\WDI' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Windows\System32\LogFiles\WMI' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Windows\System32' does not exist. Skipping
Target 'PowerShellConsole' with Id 'efa4332a-89eb-430c-ab61-006a9e6620d7' already processed. Skipping!
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
Target 'EventLogs' with Id 'd95784d9-bd1c-472b-aeef-de5d9ecc7aaa' already processed. Skipping!
Target 'EventTraceLogs' with Id 'af494526-9e44-4548-9d29-f088eafa6f3d' already processed. Skipping!
Target 'EvidenceOfExecution' with Id '13ba1e33-4899-4843-adf0-c7e6a20d758a' already processed. Skipping!
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Program Files\Microsoft\Exchange Server' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Program Files\Microsoft\Exchange Server' does not exist. Skipping
Target 'ExchangeClientAccess' with Id '9e802154-53eb-4cc9-9cca-d2e39f3227d7' already processed. Skipping!
Target 'ExchangeTransport' with Id '9bc0a453-50ab-46e8-a424-09dc7022c4a4' already processed. Skipping!
Target 'FileSystem' with Id 'cf748dbc-1c5a-4ae9-8f68-4aba6505e181' already processed. Skipping!
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Windows\system32\LogFiles' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\inetpub\logs\LogFiles' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Resources\directory' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
Target 'LnkFilesAndJumpLists' with Id '5fc6820c-4d30-4a38-9e43-5e0b788a4b0c' already processed. Skipping!
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Program Files\Microsoft SQL Server' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Program Files\Microsoft SQL Server' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
Target 'PowerShellConsole' with Id 'efa4332a-89eb-430c-ab61-006a9e6620d7' already processed. Skipping!
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
Target 'Recycle' with Id 'ab04eb7f-30cb-4cdc-83df-88ec83dc7a' already processed. Skipping!
Target 'RegistryHives' with Id '76af6086-bd0b-429f-bfd7-4a8e8ff8138f' already processed. Skipping!
Target 'RegistryHivesSystem' with Id '2b7f40fd-cd02-47da-87da-9966fa5d8159' already processed. Skipping!
Target 'RegistryHivesUser' with Id 'a7745574-97b8-4dbe-87fb-d37f59a92er3e' already processed. Skipping!
Target 'ScheduledTasks' with Id 'e5dc4367-2e6b-49bf-a90a-d4c1598bbe28' already processed. Skipping!
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Documents and Settings' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
Target 'SRUM' with Id '9858f1fc-5e22-46a0-8bfd-c821ac9b4a13' already processed. Skipping!
Target 'StartupInfo' with Id 'e1c2040e-c1b4-47ef-973f-73a54c5e87ca' already processed. Skipping!
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
Target 'Symantec_Daily_AV' with Id '5e750ea2-f6dc-4981-88d1-636ce042aa0d' already processed. Skipping!
Target 'Syscache' with Id 'd4665b13-9953-4cf0-bdc4-6fcb7a37842f' already processed. Skipping!
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
Target 'ThumbCache' with Id '1eec8849-b6eb-475b-a700-f4fb0055356d' already processed. Skipping!
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
Target 'USBDevicesLogs' with Id '07ee308f-c79a-47de-a431-c93ab34e4b66' already processed. Skipping!
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
Target 'InternetExplorer' with Id 'b1e1d79b-324d-4587-a002-cc81144588ff' already processed. Skipping!
Target 'Chrome' with Id 'a56d0a8f-3229-489e-aea7-353d1f6f9639' already processed. Skipping!
Target 'FireFox' with Id '28801734-b95a-47e7-b84f-4ebd0c104862' already processed. Skipping!
Target 'Edge' with Id 'c72bd45c-2a24-4df9-aa0b-3d7048c90337' already processed. Skipping!
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
Target 'WindowsFirewall' with Id 'e1c2040e-c1b4-47ef-973f-73a54c5e87ca' already processed. Skipping!
Target 'WindowsIndexSearch' with Id '9828b927-f955-464a-80fb-a48ce0101236' already processed. Skipping!
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
        'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\Users' does not exist. Skipping
Found 5 files. Beginning copy...
        Deferring 'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\$MFT' due to IOException...
        Deferring 'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\$LogFile' due to IOException...
        Deferring 'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\$Secure:$SDS' due to IOException...
        Deferring 'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\$Boot' due to IOException...
        Deferring 'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\$Extend\$RmMetadata\$TxfLog\$Tops:$T' due to IOException...
Deferred file count: 5. Copying locked files...
Could not copy file 'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\$MFT' to 'G:\TeamExercise\dmz-ftp\H\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\$MFT'. Error: BIOS Parameter Block is invalid for an NTFS file system
Could not copy file 'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\$LogFile' to 'G:\TeamExercise\dmz-ftp\H\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\$LogFile'. Error: BIOS Parameter Block is invalid for an NTFS file system
Could not copy file 'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\$Secure:$SDS' to 'G:\TeamExercise\dmz-ftp\H\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\$Secure_$SDS'. Error: BIOS Parameter Block is invalid for an NTFS file system
Could not copy file 'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\$Boot' to 'G:\TeamExercise\dmz-ftp\H\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\$Boot'. Error: BIOS Parameter Block is invalid for an NTFS file system
Could not copy file 'H:\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\$Extend\$RmMetadata\$TxfLog\$Tops:$T' to 'G:\TeamExercise\dmz-ftp\H\SRL-Data\Disk Images\dmz-ftp-cdrive.E01\$Extend\$RmMetadata\$TxfLog\$T'. Error: BIOS Parameter Block is invalid for an NTFS file system

WARNING: THERE WERE 5 FILE COPY FAILURES! See the console log for details!!!

Copied 0 out of 5 files in 0.7110 seconds. File copy errors: 5. See console log for details! See '*_copylog.*' in the VHD(X)/Zip located in 'G:\TeamExercise\dmz-ftp' for copy details
Initializing VHDX creation. This may take a while...
Unhandled exception! Attempting to write current Console Log to 'C:\Forensic Program Files\kape\2019-08-17T02_03_39_8977170_Console_Log.txt'

Unhandled Exception: System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at kape.Program.CreateVhdx(Boolean asVhd)
   at kape.Program.Main(String[] args)
PS F:\SIFT-Lab-Install\kape>

**Comment by EricZimmerman** [comment]
why are you trying to set --tsource to an E01? it doesnt support that. mount the E01 with ARSENAL IMAGE MOUNTER and point it at the drive letter assigned.

**Comment by biscegb** [comment]
Shouldn't that be the error message?  I struggled with that for a bit.


On Aug 16, 2019 10:50 PM, Eric <notifications@github.com> wrote:

why are you trying to set --tsource to an E01? it doesnt support that. mount the E01 with ARSENAL IMAGE MOUNTER and point it at the drive letter assigned.

**Comment by EricZimmerman** [comment]
I don't know about that. The documentation doesn't say to be able to point to a file It says to point it to a directory
