### ISSUE TITLE
S3 upload error in corporate proxy environment

### ISSUE THREAD

**Issue by mattnotmax** [EricZimmerman/KapeFiles#121]
Uploading to AWS S3 from a corporate environment with an authenticated proxy produces an error message: 
_**"Error validating s3 information: Exiting!! Error: A web exception with status ProtocolError was thrown.**_

I suspect it is similar to this recorded issue: https://stackoverflow.com/questions/35879889/exception-while-uploading-file-to-s3-net-sdk

Ideally, KAPE would obtain the logged user proxy credentials automatically if possible. Otherwise, passing the creds as arguments.

![u8cgr5hZ png_large](https://user-images.githubusercontent.com/39072319/63427058-986d2780-c457-11e9-82de-1c7c63b9b061.png)

Let me know if you need more info/debug logs etc. I haven't tested for Azure.

Happy to test in my environment.

**Comment by EricZimmerman** [comment]
ok, so lets try this and see if it works

1. create a file named kape.exe.config in same directory as kape.exe 
2. add the following to it:

``` 
<?xml version="1.0" encoding="utf-8"?>
<configuration>
<system.net>
   <defaultProxy useDefaultCredentials=”true”> </defaultProxy>
</system.net>
</configuration>
```
3. save
4. test

if this works, i will document it in KapeDocs and off we go!

**Comment by mattnotmax** [comment]
No luck unfortunately: 
Program 'kape.exe' failed to run: The application has failed to start because its side-by-side configuration is
incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detailAt line:1
char:1
+ .\kape.exe
+ ~~~~~~~~~~.
At line:1 char:1
+ .\kape.exe
+ ~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

![kape](https://user-images.githubusercontent.com/39072319/63554471-df0a7100-c580-11e9-8eb4-443dbef93767.PNG)

**Comment by EricZimmerman** [comment]
i saw your post via email. looks like you have some special symbols around the true value etc. can you create a new text file and make sure there are just quotes in there?

**Comment by mattnotmax** [comment]
yeah, that's why I deleted and trying now :)

**Comment by mattnotmax** [comment]
![kape](https://user-images.githubusercontent.com/39072319/63554934-6d332700-c582-11e9-92a3-6e812cb72300.PNG)

Still no luck

**Comment by EricZimmerman** [comment]
ok well, the easy route was worth looking at! thanks!

**Comment by EricZimmerman** [comment]
ok, some more details

see here

https://docs.aws.amazon.com/sdk-for-net/v2/developer-guide/net-dg-config-ref.html#net-dg-config-ref-elements-proxy

can you try this?

```
<?xml version="1.0"?>
<configuration>
  ...
  <configSections>
    <section name="aws" type="Amazon.AWSSection, AWSSDK.Core"/>
  </configSections>
  <aws>
    <!-- Add your desired AWS settings declarations here. -->
  </aws>
  ...
</configuration>
```

and then use something as seen on that webpage for your proxy?

like this (inside the aws block id guess):

```
<proxy
  host="192.0.2.0"
  port="1234"
  username="My-Username-Here"
  password="My-Password-Here" />
```

![image](https://user-images.githubusercontent.com/4265254/63601113-d7ec5e80-c592-11e9-9d6b-919b1b2475cb.png)


i also found some stuff here that may help me if this does not work:

https://forums.aws.amazon.com/thread.jspa?threadID=142597
https://docs.aws.amazon.com/sdk-for-net/v2/developer-guide/net-dg-config-creds.html

**Comment by mattnotmax** [comment]
OK, I'll have to check in our environment on Monday our time. Will let you know. Thanks.

**Comment by mattnotmax** [comment]
> can you try this?
> 
> ```
> <?xml version="1.0"?>
> <configuration>
>   ...
>   <configSections>
>     <section name="aws" type="Amazon.AWSSection, AWSSDK.Core"/>
>   </configSections>
>   <aws>
>     
>   </aws>
>   ...
> </configuration>
> ```
> 
> and then use something as seen on that webpage for your proxy?
> 
> like this (inside the aws block id guess):
> 
> ```
> <proxy
>   host="192.0.2.0"
>   port="1234"
>   username="My-Username-Here"
>   password="My-Password-Here" />
> ```
> 

Can confirm this worked with kape.exe.config and the above details.

Thanks for pointing me in the right direction.

**Comment by EricZimmerman** [comment]
awesome. i added a link to the FAQ pointing here

**Comment by mattnotmax** [comment]
For the record the final config file was placed in the same folder as kape.exe and named kape.exe.config:

```
<?xml version="1.0"?>
<configuration>
  <configSections>
    <section name="aws" type="Amazon.AWSSection, AWSSDK.Core"/>
  </configSections>
  <aws>
    <proxy
    host="insert IP/domain"
    port="insert port-details"
    username="login"
    password="pw" />
  </aws>
</configuration>
```

For those people looking at this ticket some overall thoughts:

Hard-coding your proxy creds isn't a great idea so this solution isn't probably best practice if you are going to have it widespread use in an environment. Options to mitigate the risk include:

- consider white-listing a single s3 bucket that you might want to use for collections. The API keys could be given write access only (to mitigate any issues if they are exposed) and the data uploaded could be transferred out of the bucket immediately upon write. The keys could be rotated depending on your requirements. This is probably the best way forward.

- use a specific account with limited privs (e.g. proxy access only rather than further internal network access)

- if you need to use proxy creds then consider using powershell to enter them at run-time. something like this (please excuse my powershell):

```
$cred = Get-Credential
$clearpassword = $cred.GetNetworkCredential().password
(Get-Content -path .\kape.exe.config -raw) -replace 'login', $cred.UserName
(Get-Content -path .\kape.exe.config -raw) -replace 'pw', $clearpassword
```

I would then remove the config file in your script following collection (remember your probably collecting off an infected endpoint yeah?) and then rotate the password immediately. 

As you can see there are probably better solutions than this, but it's still good to know it can be done.
