### ISSUE TITLE
KAPE crashing in Batch Mode

### ISSUE THREAD

**Issue by mark-hallman** [EricZimmerman/KapeFiles#123]
I'm running into an exception while running KAPE in batch mode.  The batch file contains the one line shown here.  tdest and mdest are UNC paths.  

```
--tsource c: --target LnkFilesAndJumpLists --tflush --tdest "\\Tarpon\f\temp\tdest" --vhdx $env:ComputerName --module LECmd,JLECmd --mflush --mdest "\\Tarpon\f\temp\mdest" --zm TRUE --gui
```

Running from the cli with this command KAPE runs to completion with the correct results.

```
kape --tsource c: --target LnkFilesAndJumpLists --tflush --tdest "\\Tarpon\f\temp\tdest" --vhdx $env:ComputerName --module LECmd,JLECmd --mflush --mdest "\\Tarpon\f\temp\mdest" --zm TRUE --gui
```

![1566613816781](C:\Users\Mark\AppData\Roaming\Typora\typora-user-images\1566613816781.png)

**Comment by EricZimmerman** [comment]
It's the colon in the vhdx name.

Cant do that in batch mode since colon is not a valid char in a file name.

**Comment by mark-hallman** [comment]
As a follow up,  changing to tdest & mdest paths on the same local drive as KAPE is running from get ths same errors in batch mode.

**Comment by EricZimmerman** [comment]
Use %m which is why it was added.

**Comment by mark-hallman** [comment]
Roger.  Thank you.
