### ISSUE TITLE
Invalid Disk Name Error when using F-Response Universal (Discoveryshare)

### ISSUE THREAD

**Issue by AMcCWash** [EricZimmerman/KapeFiles#134]
So I've been doing some testing with Kape and have come across an issue. I'm mounting the disk image with F-Response Universal (Discoveryshare- Unlocking all files). When running the tool using this method I get an error regarding diskName invalid. 

Seem to work fine when mounting as physical disk to my machine but takes an awful long time doing disk reads to bypass locked files 

My hopes were that I'm not doing something correct when providing targertsource.

**Comment by EricZimmerman** [comment]
any update on this? id like to close it if its a non-issue

**Comment by AMcCWash** [comment]
Sorry for the late reply. Updated the version and work like a charm. The underlying issue I believe  is related to bandwidth as it relates to copying locked files and making disk-reads using the F-Response session. I'll have to take a look at the F-Response deployment. Thanks for help and speedy responses.
