### ISSUE TITLE
KAPE in SFTP mode immediately drops connection

### ISSUE THREAD

**Issue by mark-hallman** [EricZimmerman/KapeFiles#135]
** KAPE version # **
The version of KAPE you are running
KAPE 0.8.7.0

**Describe the bug**
 When a client connects to the server,  it is then immediately dropped.  Logs report some sort of write permissions failure. 

Eric,

I am experiencing an error with KAPE running in sftp mode.  When a client connects to the server,  it is then immediately dropped.  I have attached all logs from a couple of machines,  one physical and the other a Hyper-V VM.  I don't think that should make any difference but I had them already.  

Snippet from the log:

```
2019-09-01 17:37:17.879 DEBUG SftpModule(1)[18] SFTP: Opening file '/2019-09-01_223715KAPE_SFTP_WRITE_TEST_e27fb336-7c68-4b3e-8342-cd1c90a0265a' (Create, Write): failure.
2019-09-01 17:37:17.879 VERBOSE SftpModule(1)[18] SFTP: Filesystem access error: Access denied.
```

I have been successful in running KAPE in SFTP mode on several machines including this particular VM.  I don't know what has changed. Hoping the logs might give you a clue.  I think the logs are saying that KAPE can't get write permissions.

This test Lab has several VMs but this scenario only uses three.  Lab-04 is running the KAPE SFTP Server.  Lab-03 is a file server the has the KAPE executable, targets, modules, etc.   Lab-02 is the target and is 
[KAPE_SFTP_Log.zip](https://github.com/EricZimmerman/KapeFiles/files/3564042/KAPE_SFTP_Log.zip)

initiating the KAPE command, shown farther below.

Just had a thought while writing this up... I'm going to see if changing the permissions for the user in the sftp config file to **"All"** from **"Read|Write|List**"  makes any difference. **Yes,  that works.**  Hum, not sure if you consider this an issue or not.  I can just keep these settings and keep working.

I'm sending a zip with logs, the sftp config that works.  The permissions that don't work are commented out.  

The server is started with this command
 `.\kape.exe --sftpc C:\Tools\KAPE\kape_sftp_config.skape`

Question:  Your docs state that you need to provide the full path to the config file.  Relative paths won't work?

This the simplified (comments removed) sftp config file

```
Port: 22
HomeDirectory: C:\temp\sftp\Root
LogDirectory: C:\temp\sftp\Logs
LogLevel: Verbose 
Users:
    -
        UserName: mark
        Password: wizzo123!
        #Access: Read|Write|List
        Access: Allt
        Jail: true
```

The KAPE command being run from Lab-02 is  

```
\\LAB-03\c$\Tools\KAPE\kape.exe --tsource c: --target LnkFilesAndJumpLists --tflush --tdest "c:\temp\tdest_%m" --vhdx %m --module LECmd,JLECmd --mflush --mdest "c:\temp\mdest_%m" --zm TRUE --scp 22 --scu mark --scpw wizzo123! --scs 172.17.166.228 
```
It is executing kape.exe over UNC path located on a 3rd machine, Lab-03 and send the output to the KAPE SFTP server running on Lab-04.

**Comment by mark-hallman** [comment]
[KAPE_SFTP_Log.zip](https://github.com/EricZimmerman/KapeFiles/files/3564043/KAPE_SFTP_Log.zip)

**Comment by EricZimmerman** [comment]
Is there a create option? While it sounds like write would be enough that's to just write to existing files, so change things to create and see what happens.

**Comment by EricZimmerman** [comment]
https://ericzimmerman.github.io/KapeDocs/#!Pages\6.-SFTP.md#Access

**Comment by mark-hallman** [comment]
Eric,  Yes there is a create option.  I tried using create by itself and in combination with other privileges.  This does not work for me.  The only option that I can make work is the "All" option.

**Comment by EricZimmerman** [comment]
this works

Access: Read|Create|Write|List

apparently you need Create and write to make new files and then write to them.

All makes sense for most (you have Allt in your example), but if you wanted to only allow pushing files you can drop list and Read. i will have to do a bit more looking into why it hangs when read and list are missing, so for now, use all 4 or just All

**Comment by EricZimmerman** [comment]
closing since we know all works and ill open a new ticket for the other permissions
