### ISSUE TITLE
sftp tweaks and permissions

### ISSUE THREAD

**Issue by EricZimmerman** [EricZimmerman/KapeFiles#136]
** KAPE version # **
0.8.7.0

why does this work

Access: Read|Create|Write|List

but this hangs?

Access: Create|Write

need to be able to successfully test when no read/list perms exist.

**Comment by mark-hallman** [comment]
When would you not have a "Create" or "All" in your Access Option?  

Can you give me an example of how one would use "Read" or "List", either by themselves or in combination with other access options?

I really appreciate the granularity but it might be overkill since we can't download from this server.    Or, I don't fully understand what the KAPE SFTP Server can do.  In any case,  this a awesome work.

**Comment by EricZimmerman** [comment]
well, if you wanted a client to only be able to push data, and not list it, youd only give create|write

this way if the creds get compromised, no one could use them to do anything except upload data to the server.

you certainly CAN download from the sftp server if you have the right permissions (All would do it)

**Comment by EricZimmerman** [comment]
ok, so try this. did some testing today.

you want a push only and no listing client, use Write|Create|Read

This should be all you need now, but we can reopen if need be

more options and updates here!

```# Example KAPE SFTP configuration file
# Eric Zimmerman eric.zimmerman@kroll.com
# Adjust as needed, then pass full path to this file to the --sftpc switch

Port: 22
HomeDirectory: C:\temp\sftp\Root
LogDirectory: C:\temp\sftp\Logs
LogLevel: Verbose
Users:
    -
        UserName: eric
        Password: wizzo123!
        Access: Read|Write|Create|List
        Jail: true
    -
        UserName: mike
        Password: wizzo123!
        Access: Read|Write|Create|List
        Jail: false
    -
        UserName: mikeAll
        Password: wizzo123!
        Access: All
        Jail: false
    -
        UserName: mikeRO
        Password: wizzo123!
        Access: Read|List
        Jail: false
    -
        UserName: mikeWriteOnly
        Password: wizzo123!
        Access: Write|Create|Read
        Jail: false

# Access options:
# One or more of the following: Read|Write|Create|Delete|List|All

# To upload files, both Write and Create are needed
# KAPE creates a test file to ensure writability. If delete permissions are missing, KAPE cannot clean up the 
# test files and this will have to be done manually

# To create a user that can only push files and not see anything, use:
# Write|Create|Read

# Jail
# When false, user's home directory is HomeDirectory
# When true, user will be chrooted to 'HomeDirectory\UserName' directory

# LogLevel
# Possible choices are: Error | Info | Debug | Verbose | Off
