### ISSUE TITLE
Write-Host : Cannot process the color error messages

### ISSUE THREAD

**Issue by the-IMOL** [EricZimmerman/KapeFiles#144]
** KAPE version # **
KAPE 0.8.7.2 (but applies to older versions too)

**Describe the bug**
Running the standard ./Get-Update.ps1 script produces multiple of the same "not valid color" error messages (not just limited to line 116).  Sample error message is here:

* Write-Host : Cannot process the color because -1 is not a valid color.
Parameter name: value
Actual value was -1.
At C:\Path\To\KAPE\Get-KAPEUpdate.ps1:116 char:59
+ ... th; $i++) { Write-Host -Object $Text[$i] -ForegroundColor $Color[$i]  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Write-Host], ArgumentOutOfRangeException
    + FullyQualifiedErrorId : SetInvalidForegroundColor,Microsoft.PowerShell.Commands.WriteHostCommand

**To Reproduce**
Run ./Get-Update.ps1 as admin

**Expected behavior**
No error messages

**Screenshots**
Message is cut and pasted above.

**Additional context**
None

**Comment by EricZimmerman** [comment]
what OS? it should not break anything from an update perspective.

ive seen this on a mac before where the color isnt set for some reason. i have a workaround, but lemme know about the OS please

**Comment by the-IMOL** [comment]
Windows 7 Professional (6.1.7601 Service Pack 1 Build 7601)
running ISE / PSVersion:  5.1.14409.1018

**Comment by EricZimmerman** [comment]
do not run it in ISE and see how it goes.

either way ill add the fix to the script for the next version

**Comment by EricZimmerman** [comment]
as a test, locate the line that looks like (around line 151):

$defaultColor = (Get-Host).ui.rawui.ForegroundColor

and replace it with:

$TestColor = (Get-Host).ui.rawui.ForegroundColor
if ($TestColor -eq -1) 
{
    $defaultColor = [ConsoleColor]::Gray
} else {
    $defaultColor = $TestColor
}

then try again. this will break the signature, but thats ok for testing

**Comment by the-IMOL** [comment]
Yep - that's the cause. Ran it without ISE and produced no error messages.

**Comment by EricZimmerman** [comment]
ok, try it in ISE now too
it should be fixed with the code i posted above

close when ready

**Comment by the-IMOL** [comment]
Yes, that fix resolved the issue.  Closing this out now.  Thanks!
