### ISSUE TITLE
ability to customise VHD/ZIP filenames

### ISSUE THREAD

**Issue by mattnotmax** [EricZimmerman/KapeFiles#148]
** KAPE version **
0.8.7.3

**Is your feature request related to a problem? Please describe.**
When the VHD and/or ZIP is created it includes the whole list of targets. Eg. 

_**Command line:**_
`.\kape.exe --tsource C: --tdest C:\Temp --target Chrome,ChromeExtensions,EventLogs,EvidenceOfExecution,FileSystem --vhd Collection`

_**Output filename**_
```
2019-10-01T121241_Chrome,ChromeExtensions,EventLogs,EvidenceOfExecution,FileSystem_Collec
tion.zip
```
_**Desired output**_
`Collection_2019-10-01T121241_MATT-PC.ZIP`

**Describe the solution you'd like**
An option to have a base name + a date of collection + machine name. Similar to folder path checkboxes (add %d, add %m). Perhaps you can include a %t to include the target list to keep the current status quo.

**Describe alternatives you've considered**
No alternative, unless there is a switch / feature already and it's user error on my part

thanks as always for the tool and considering this request.

**Comment by EricZimmerman** [comment]
It can't include the whole list or the file name might end up being 100s of characters long

You can already use %d and %m for timestamp or machine name in tdest mdest zip and vhdx options. 

Look in the console log for full command line which includes all the targets used. 

If you want the file name to include the target, make a compound target and then just call that, vs 15 different target names. Having all the target names used to be the default until people selected all 60 of them and the filename because 300 characters long.

**Comment by EricZimmerman** [comment]
Let me know if those options do not work for you.

**Comment by mattnotmax** [comment]
Sorry, I didn't express myself clearly. I actually don't want the target names in the end VHD/ZIP.

What I was after is an option to have a short VHD/ZIP name instead of the current.  


**Example 1:**
If I use the CLI: 

`.\kape.exe --tsource C: --tdest C:\Temp --target Chrome,ChromeExtensions,EventLogs,EvidenceOfExecution,FileSystem --vhd Collection` 

I end up with a Zip called: 

```
2019-10-01T121241_Chrome,ChromeExtensions,EventLogs,EvidenceOfExecution,FileSystem_Collec
tion.zip
```

What I was after is the option to have the CLI as this: 

` .\kape.exe --tsource C: --tdest C:\Temp --target Chrome,ChromeExtensions,EventLogs,EvidenceOfExecution,FileSystem --vhd Collection_%m_%d`

which would produce a VHD/ZIP with the filename:

`Collection_Matt-PC_2019-10-01T121241.zip`

**Example 2:** 

If I use CLI like this:

`.\kape.exe --tsource C: --tdest C:\Temp\Collect_%m_%d --target Chrome,EventLogs,EvidenceOfExecution,FileSystem --vhd Collection_%m_%d`

I end up with a folder called: `C:\Temp\Collect_Matt-PC_20191001T223233` and inside is a file called: `2019-10-01T223233_Chrome,EventLogs,EvidenceOfExecution,FileSystem_Collection_Matt-PC_20191001T223233.zip`

What I was after was `C:\Temp\Collect_Matt-PC_20191001T223233\Collection_Matt-PC_20191001T223233.zip`

Hope I make sense now! :)

**Comment by EricZimmerman** [comment]
let me see what i can do.

**Comment by EricZimmerman** [comment]
like this?

.\kape.exe --tsource c --tdest C:\Temp\tout --target evidenceofexecution --vhdx thisIsTheName%m

2019-10-02T170426_thisIsTheNameSAGER.zip

.\kape.exe --tsource c --tdest C:\Temp\tout --target evidenceofexecution --vhdx thisIsTheName_%m_%d

2019-10-02T170514_thisIsTheName_SAGER_20191002T170514.zip

this will be in the next release. if you want a build to try, here you go:

https://sansorg.egnyte.com/dl/UohySN3mAJ
Password: vQDcqGMe7T4T

if that works for you, please close the ticket

**Comment by mattnotmax** [comment]
Yup. Tested all good.

Thanks Eric!
