### ISSUE TITLE
Clean Up Script leaves Documentation folder

### ISSUE THREAD

**Issue by ecapuano** [EricZimmerman/KapeFiles#154]
** KAPE version # **
0.8.8.0

**Describe the bug**
Small gripe, but running with `--cu` mode, the Documentation folder is not cleaned up per the docs: 

> Once all spawned KAPE processes have exited, the main KAPE process deletes _kape.cli, along with the Targets, Modules, and Documentation directories.

**To Reproduce**
Ran KAPE with the following arguments
```
--tsource C -vss --tdest "c:\temp\tdest" --target <targets> --module <modules> --mdest "c:\temp\mdest" --zip recon --mflush --tflush --cu
```

**Expected behavior**

> Once all spawned KAPE processes have exited, the main KAPE process deletes _kape.cli, along with the Targets, Modules, and Documentation directories.

**Screenshots**
Post-execution directory contents 
![image](https://user-images.githubusercontent.com/4219694/67637896-7956a000-f8b5-11e9-95a7-92e355b4e64b.png)

**Additional context**
KAPE rocks.

**Comment by EricZimmerman** [comment]
fixed in next release
