### ISSUE TITLE
Forgiveness when using _kape.cli files

### ISSUE THREAD

**Issue by ecapuano** [EricZimmerman/KapeFiles#155]
** KAPE version **
0.8.8.0

**Is your feature request related to a problem? Please describe.**
Huge fan of the `_kape.cli` batch feature... However, sometimes while testing, I'll run `kape.exe -h` for quick reference of CLI options and that invokes the `cli` file (normal behavior as documented) This can be painful when the `cli` file has a `--cu` option which nukes all of my dev/testing stuff...

**Describe the solution you'd like**
Any chance simpler options like `-h` can override the presence of a `_kape.cli` file to prevent the nuclear option during quick help usage?

**Describe alternatives you've considered**
A workaround I've used is just cloning my working directory and doing my testing there, but meh. 

**Additional context**
Thanks Z!

**Comment by EricZimmerman** [comment]
fixed in next release

when kape.exe is run without any args, it picks up batch mode if file is there

if kape.exe /? is run, you get help and it exits
