### ISSUE TITLE
Regex support in target file mask

### ISSUE THREAD

**Issue by ecapuano** [EricZimmerman/KapeFiles#156]
** KAPE version **
The best version

**Is your feature request related to a problem? Please describe.**
Would like to be more flexible with target paths to include regular expression to avoid having super long lists of targets to account for many possible permutations

**Describe the solution you'd like**
Imagine I wanted a long list of file extensions in a single path... Like suspicious executables in User downloads directories.... 

Would like to be able to do this:
```
    -
        Name: Downloads
        Category: Downloads
        Path: C:\Users\*\Downloads\*.(bat|exe|cmd)
        Comment: ""
```

...instead of this...

```
    -
        Name: Downloads
        Category: Downloads
        Path: C:\Users\*\Downloads\*.bat
        Comment: ""
    -
        Name: Downloads
        Category: Downloads
        Path: C:\Users\*\Downloads\*.exe
        Comment: ""
    -
        Name: Downloads
        Category: Downloads
        Path: C:\Users\*\Downloads\*.cmd
        Comment: ""
```

**Comment by EricZimmerman** [comment]
so this is going to slow things down too much, and it "hides" meaning from people not experienced in regex. wont be doing this (for now)
