### ISSUE TITLE
tlist and mlist do not work properly

### ISSUE THREAD

**Issue by Beercow** [EricZimmerman/KapeFiles#159]
** KAPE version # **
The version of KAPE you are running
0.8.8.0

**Describe the bug**
Cannot get any output from tlist or mlist without supplying a folder path. It will only list the targets/modules in that directory and just list the sub directories.

**To Reproduce**
1. kape.exe --tlist (only lists help)
2. kape.exe --tlist . (only lists targets in the directory and lists just the sub-directory)

**Expected behavior**
See output form 0.8.5.0 below.

**Screenshots**

Without supplying folder path:
![image](https://user-images.githubusercontent.com/10360919/67947786-6e9c5380-fbb2-11e9-936f-5906466deb09.png)

With path supplied:
![image](https://user-images.githubusercontent.com/10360919/67947998-c8048280-fbb2-11e9-9079-a2465483c44d.png)

Desired output from 0.8.5.0:
![image](https://user-images.githubusercontent.com/10360919/67948089-fb471180-fbb2-11e9-9a06-606b8578c415.png)

**Comment by EricZimmerman** [comment]
this is not an issue. those switches expect a path with . being the starting point.

from there, to see sub folders, you would do

--tlist Apps

or

--tlist Logs

and so on

--mlist is the same

this makes it easier to see things categorically
