### ISSUE TITLE
Suppress output window

### ISSUE THREAD

**Issue by slacker-kb** [EricZimmerman/KapeFiles#160]
** KAPE version **
0.8.8

**Is your feature request related to a problem? Please describe.**
Configured _kape.cli to run in batch mode and it work fine, sends to S3.  However there does not appear to be a way to suppress the output windows.  

**Describe the solution you'd like**
Run kape in it's intended manner without the output windows.

**Describe alternatives you've considered**
I have tried running kape.exe via ps1 attempting to output to null (Out-null, > $null), etc.  Also tried calling kape.exe from command prompt with "> &null 2>$1". same result.  Output always comes up.  

**Additional context**

**Comment by EricZimmerman** [comment]
So you want the window to be hidden?

**Comment by slacker-kb** [comment]
yessir.

**Comment by EricZimmerman** [comment]
are you executing this on command line straight up or via gkape? if its via gkape i can minimize the window, but there is no way to hide the window outright, as it is now

you would have to control the execution via making a shortcut and setting kape to run minimized. thats about the only way to do it. i did try some stuff to free the console, but then nothing was done, no logging, no collection.

would this work?

PowerShell.exe -windowstyle hidden { your script.. }

https://stackoverflow.com/questions/1802127/how-to-run-a-powershell-script-without-displaying-a-window

**Comment by EricZimmerman** [comment]
your other option is just doing something like this:

.\kape.exe --tsource c --tdest c:\temp\tout --tflush --target evidenceofexecution | Out-Null

and nothing gets displayed

![image](https://user-images.githubusercontent.com/4265254/68336930-67db7800-00ad-11ea-9400-d181bb2f6127.png)

**Comment by slacker-kb** [comment]
Copy.  That works.  Just need to translate to my _kape.cli file.  Thanks!

**Comment by EricZimmerman** [comment]
Woot
