### ISSUE TITLE
Hindsight JSONL output

### ISSUE THREAD

**Issue by cydonia11** [EricZimmerman/KapeFiles#170]
** KAPE version # **
0.8.8.0

**Describe the bug**

hindsight.exe module with json output errors out hindsight.exe;

 Command line: --msource C:\basic\E\Users\ --module Hindsight --mdest C:\Users\xxxx\Desktop\dee\ --mef json

Using Module operations
                Found processor 'Executable: hindsight.exe, Cmd line: -i %sourceDirectory% -o %destinationDirectory%\Hindsight_output -f json, Export: json, Append: False'!
Discovered 1 processor to run.
Executing modules with file masks...
Executing remaining modules...
        Running 'hindsight.exe': -i C:\basic\E\Users -o C:\Users\xxx\Desktop\dee\BrowsingHistory\Hindsight_output -f json
                **error: argument -f/--format: invalid choice: 'json' (choose from 'sqlite', 'jsonl', 'xlsx')**
Executed 1 processor in 7,7056 seconds

and if you try "--mef jsonl" KAPE errors out

**Valid values for 'mef' are: json | csv | html | xml. Exiting**

**Comment by EricZimmerman** [comment]
Show me your module file

You need to have a completely separate duplicated processor that has the exact command line to use for JSON but leave the export format JSON versus JSONL in that entry

**Comment by cydonia11** [comment]
[Hindsight v2.4.0](https://github.com/obsidianforensics/hindsight/releases/tag/v2.4.0)

**Comment by EricZimmerman** [comment]
That's not the module file that you're trying to use in kape

please read the documentation and then try what I suggested and let me know
