### ISSUE TITLE
Quicktimeline module

### ISSUE THREAD

**Issue by yehias** [EricZimmerman/KapeFiles#172]
** KAPE version # **
KAPE version 0.8.8.0

**Describe the bug**
Thanks a lot for such great tool, I was trying to create quicktimeline module  and when I try to use it I will receive an error.

**Command used**:
Kape.exe --tsource c: --tdest G:\test\ --target Quicktimeline --tflush --mdest G:\test\output\ --module QuickTimeline -mflush

**Output Error**

`Author: Eric Zimmerman
Version: 1
Id: 5dbe9218-fd3d-4d86-88aa-56001d38e7f5
RecreateDirectories: true
Targets:

# Create Supertimeline
	-
		Name: Prefetch
		Category: Execution
		Path: EvidenceOfExecution.tkape
		IsDirectory: false
		Recursive: false
		Comment: ""
		
	-
	
		Name: Hives
		Category: Execution
		Path: RegistryHives.tkape
		IsDirectory: false
		Recursive: false
		Comment: ""
		
	-
		
		Name: Jump lists
		Category: Execution
		Path: LnkFilesAndJumpLists.tkape
		IsDirectory: false
		Recursive: false
		Comment: ""
(Line: 12, Col: 3, Idx: 258) - (Line: 12, Col: 3, Idx: 258): While parsing a block mapping, did not find expected key.

Verify all properties against example files or manual and try again.

Syntax error in 'C:\Forensic Program Files\kape\Modules\Quicktimeline.mkape':
Description: Quicktimeline
Category: Timeline
Author: Eric Zimmerman
Version: 1
Id:  5cf0c60e-ablc-4634-83b7-fd222fbbb4e0
BinaryUrl: https://github.com/log2timeline/plaso/releases
ExportFormat: csv
Processors:
    -
        Executable: PECmd.mkape
        CommandLine: ""
        ExportFormat: ""
	-
		Executable: RBCmd.mkape
        CommandLine: ""
        ExportFormat: ""
	-
		Executable: JLECmd.mkape
        CommandLine: ""
        ExportFormat: ""
	-
		Executable: Plaso.mkape
        CommandLine: ""
        ExportFormat: ""
**(Line: 13, Col: 2, Idx: 296) - (Line: 13, Col: 2, Idx: 296): While parsing a block mapping, did not find expected key.**

Verify all properties against example files or manual and try again.

Syntax error in 'C:\Forensic Program Files\kape\Modules\Timelining\Quicktimeline.mkape':
Description: Quicktimeline
Category: Timeline
Author:  Eric Zimmerman
Version: 1
Id:  5cf0c60e-ablc-4634-83b7-fd222fbbb4e0
BinaryUrl: https://github.com/log2timeline/plaso/releases
ExportFormat: csv
Processors:
    -
        Executable: PECmd.mkape
        CommandLine: ""
        ExportFormat: ""
	-
		Executable: RBCmd.mkape
        CommandLine: ""
        ExportFormat: ""
	-
		Executable: JLECmd.mkape
        CommandLine: ""
        ExportFormat: ""
	-
		Executable: Plaso.mkape
        CommandLine: ""
        ExportFormat: ""
**(Line: 13, Col: 2, Idx: 296) - (Line: 13, Col: 2, Idx: 296): While parsing a block mapping, did not find expected key.**

Verify all properties against example files or manual and try again.

One or more targets or modules failed validation. Fix the issues and try again`

**Module file code:**
`Description: Quicktimeline
Category: Timeline
Author: Eric Zimmerman
Version: 1
Id:  5cf0c60e-ablc-4634-83b7-fd222fbbb4e0
BinaryUrl: https://github.com/log2timeline/plaso/releases
ExportFormat: csv
Processors:
    -
        Executable: PECmd.mkape
        CommandLine: ""
        ExportFormat: ""
	-
		Executable: RBCmd.mkape
        CommandLine: ""
        ExportFormat: ""
	-
		Executable: JLECmd.mkape
        CommandLine: ""
        ExportFormat: ""
	-
		Executable: Plaso.mkape
        CommandLine: ""
        ExportFormat: ""`

**Target file code:**
`Description: Quicktimeline
Category: Timeline
Author: Eric Zimmerman
Version: 1
Id:  5cf0c60e-ablc-4634-83b7-fd222fbbb4e0
BinaryUrl: https://github.com/log2timeline/plaso/releases
ExportFormat: csv
Processors:
    -
        Executable: PECmd.mkape
        CommandLine: ""
        ExportFormat: ""
	-
		Executable: RBCmd.mkape
        CommandLine: ""
        ExportFormat: ""
	-
		Executable: JLECmd.mkape
        CommandLine: ""
        ExportFormat: ""
	-
		Executable: Plaso.mkape
        CommandLine: ""
        ExportFormat: ""`

**Comment by mark-hallman** [comment]
yehias,  could you drop a copy of your quicktimeline.mkape here.  I'll take a look.  I see it inline but it would perfer to work from the actual .mkape.

**Comment by EricZimmerman** [comment]
The first thing I would do is run a sync to make sure that you have all of
the most current modules and targets.

 I know that one of the last ones that somebody contributed had an error
and I needed to fix it related to box I believe

for as much as I've asked people to make sure that their syntax verifies
people still don't so I've taken the step to do it myself every time
somebody does a push into the kape files repository. This should prevent
this happening again

**Comment by yehias** [comment]
thanks a lot for you reply, and sorry for later  reply I was off the grid with no internet I will share the r quicktimeline.mkape today after I reach the office @EricZimmerman to be honest with you I'm not expert I was following a tutorial on internet and I did steps to fix and sync the module in case I did something wrong I will learn from this case to prevent that in future again thanks a lot for your great job and efforts creating such tool

**Comment by yehias** [comment]
@mark-hallman 

 **quicktimeline.mkape**

Description: Quicktimeline
Category: Timeline
Author: Eric Zimmerman
Version: 1
Id:  5cf0c60e-ablc-4634-83b7-fd222fbbb4e0
BinaryUrl: https://github.com/log2timeline/plaso/releases
ExportFormat: csv
Processors:
    -
        Executable: PECmd.mkape
        CommandLine: ""
        ExportFormat: ""
	-
	Executable: RBCmd.mkape
        CommandLine: ""
        ExportFormat: ""
	-
	Executable: JLECmd.mkape
        CommandLine: ""
        ExportFormat: ""
	-
	Executable: Plaso.mkape
        CommandLine: ""
        ExportFormat: ""

**Comment by EricZimmerman** [comment]
all of the required indenting is missing.

look at another module file and see what they should look like. it could just be a github formatting thing, but it should look more like this:

```
Category: Modules
Author: Phill Moore
Version: 1.1
Id: f531e7cc-c9f3-4d04-881b-dbc89d1e7f38
BinaryUrl: https://ericzimmerman.github.io/#!index.md
ExportFormat: csv
Processors:
    -
        Executable: AmcacheParser.mkape
        CommandLine: ""
        ExportFormat: ""
    -
        Executable: AppCompatCacheParser.mkape
        CommandLine: ""
        ExportFormat: ""
    -
        Executable: EvtxECmd.mkape
        CommandLine: ""
        ExportFormat: ""
```

**Comment by yehias** [comment]
Thanks for your reply actually my indenting is correct I just copied and paste another module and still giving same error regarding my previous it because of the copy paste.

Thanks again I will try to debug it and solve it on my own

**Comment by EricZimmerman** [comment]
mark wants the actual FILE, not the contents of the file. rename it to .txt and drop it as a comment

**Comment by yehias** [comment]
[quicktimeline.txt](https://github.com/EricZimmerman/KapeFiles/files/4084810/quicktimeline.txt)

Hi Eric,

Sorry for late reply,

**Comment by EricZimmerman** [comment]
closing to due to inactivity. if this is still an issue we can reopen
