### ISSUE TITLE
A button that selects all module items that are shown after filtering

### ISSUE THREAD

**Issue by sjosz** [EricZimmerman/KapeFiles#173]
** KAPE version **
KAPE v0.8.8.0

**Is your feature request related to a problem? Please describe.**
After the collection of data using kape and its target options, I want to process the data on my own forensics machine with GKAPE. On this machine I don't want to select all module items (while excluding the modules for LiveResponse). Is there a way of doing this smarter besides clicking on each module separately?

**Describe the solution you'd like**
In GKAPE make a button that selects all filtered module items. 

**Additional context**
I would love not to select each item that I need, I would like to filter and then select all module items with one click on the button.
![image](https://user-images.githubusercontent.com/11965973/72613644-6a214480-3930-11ea-9668-efd6857f7beb.png)

**Comment by EricZimmerman** [comment]
why not just make a NEW module with what you want in it, OR just use gkape once to make the command like you can then just  repeat over and over and over?

use gkape, build command, then copy it out, but put msource and mdest at the END of the command. that way you can reuse the command and just adjust your paths.

simple and reusable
