### ISSUE TITLE
Obfuscation when using batch mode

### ISSUE THREAD

**Issue by sjosz** [EricZimmerman/KapeFiles#179]
** KAPE version **
0.9.0.0

I love the batch functionality and use it for most of my investigations. When renaming the executable from 'kape.exe' to 'obfuscated.exe', it is unable to run the lines in '_kape.cli'

![cmd](https://user-images.githubusercontent.com/11965973/75090174-4764fa00-5586-11ea-9f45-86e1c89de11c.png)

Is there perhaps an easy workaround for this? If not it would perhaps be a cool new feature. Thanks you.

**Comment by EricZimmerman** [comment]
this is because its looking for kape.exe to shell out to, but you renamed it.

i will add a check to automatically determine the exe name in 0.9.0.1 so this kind of thing works for you

**Comment by EricZimmerman** [comment]
this is done and will be in 0.9.0.2 which will be out most likely today

**Comment by sjosz** [comment]
Cool, thanks - I will update!
