### ISSUE TITLE
gkape.exe: Can't type in the target or module source & destination

### ISSUE THREAD

**Issue by mark-hallman** [EricZimmerman/KapeFiles#18]
GKape:
Not sure if this is intentional or not but I find it limiting to be required to use the file browser to select the target and/or module source and destination.

![image](https://user-images.githubusercontent.com/16808320/53301010-70d43400-3813-11e9-818d-9d840e871207.png)

**Comment by EricZimmerman** [comment]
That's how it is in that version. The next version allows typing.

Eric Zimmerman

Opinions stated, unless explicitly stated otherwise, are mine and not that
of my employer.

P // 501-313-3778

**Comment by mark-hallman** [comment]
Thanks Eric.
