### ISSUE TITLE
File $I30 does not exist

### ISSUE THREAD

**Issue by sjosz** [EricZimmerman/KapeFiles#180]
** KAPE version # **
0.9.0.0

**Describe the bug**
Using a KAPE target, I'm trying to collect the $I30 from specific folders. And it seems that it cannot collect this NTFS metadata file. Is there a way to collect this file using KAPE since it provides forensic value?

**Screenshots**
![kUpvLLC75y](https://user-images.githubusercontent.com/11965973/75621966-0772c800-5bc1-11ea-92ea-85a198452afc.png)

**Comment by EricZimmerman** [comment]
those are not files. they are attributes. as such, KAPE wont see them. this is not a bug.

you also seem to be using FTK, which is not recommended.

the next version of Arsenal Image mounter will contain a way to expose $I30 which you can easily collect with KAPE

if you DO want to use FTK, you will have to adjust your paths to do the silliness that FTK does by adding [root] to your target, so something like:

c:\[root]\$I30

and so on
