### ISSUE TITLE
Target acquisition doesn't produce any output; "source" doesn't seem to be used

### ISSUE THREAD

**Issue by PeterWagenaarNW** [EricZimmerman/KapeFiles#190]
** KAPE version # **
v0.9.0.2

**Describe the bug**
If I run a simple Target acquisition, for instance the !BasicCollection one, no output is produced. If I read the tool log in the console correctly, it seems to ignore my "Target source" settings and instead set the starting point of the acquisition the directory where kape.exe is located. I figure this is the case judging from the "Expanding targets" putting "Users" and "Documents and Settings" folders in the base directory for kape.exe, not the "Target Source" I selected. See screenshots below.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set "Target source" to "C:\" by clicking the ellipsis and selecting the C: drive
2. Set the "Target destination" to somewhere on the C: drive, in my case "C:\Users\cert\Desktop\kape_test_output"
3. Select the !BasicCollection Target
4. Leave everything else as-is. The commandline should be:
`kape.exe --tsource C: --tdest C:\Users\cert\Desktop\kape_test_output --tflush --target !BasicCollection --gui`

**Expected behavior**
I expect KAPE to start collecting various forensically interesting information.

**Screenshots**
This screenshot shows my settings
![Settings](https://user-images.githubusercontent.com/44571193/79437725-e03a5380-7fd2-11ea-90c0-109b6db96cc5.png)
This screenshot shows the output log
![Log](https://user-images.githubusercontent.com/44571193/79437716-dd3f6300-7fd2-11ea-801f-5d0cedf7a896.png)

**Comment by EricZimmerman** [comment]
i just did this:

.\kape.exe --tsource C: --tdest C:\temp\ape_test_output --tflush --target FileSystem

and it worked as expected (with one issue i have to fix)

did you edit any of the files in the targets folder?

**Comment by EricZimmerman** [comment]
im looking into this issue as well in my IDE. thanks for reporting it, but let me know

**Comment by PeterWagenaarNW** [comment]
Checking as we speak...

**Comment by EricZimmerman** [comment]
try making --tsource c:\ as well, just as a test. i think i see what may be causing it

**Comment by PeterWagenaarNW** [comment]
I copied the command exactly as you said above, tried it with 0.9.0.1: works, but with 0.9.0.2 it gives the same error as previously.

**Comment by PeterWagenaarNW** [comment]
Adding a backslash to C: in --tsource seems to fix the problem in 0.9.0.2. I started the client from gkape.exe initially, which doesn't add the \ I assume?

**Comment by EricZimmerman** [comment]
ill have a fix for this out soon.

**Comment by PeterWagenaarNW** [comment]
Great!

**Comment by PeterWagenaarNW** [comment]
Thank you, it works perfectly!
