### ISSUE TITLE
Enhancement: Multiple file masks 

### ISSUE THREAD

**Issue by Beercow** [EricZimmerman/KapeFiles#20]
Ability to add multiple file masks for scripts that take more than one file.

**Comment by EricZimmerman** [comment]
why?

need more info.

is this a target, a module, both?

need examples of each case

**Comment by Beercow** [comment]
If you look at srum-dump.mkape, it takes srudb.dat and the SOFTWARE hive as input. You can setup the module with hardcoded paths to the files, which I don’t have a problem with, if all of your collections are formatted the same way. It would be easier on the the user if you could set a file mask for each of these files and have KAPE find them. Then the module would work out of the box without the need for the end user to adjust them. Just a thought.

**Comment by Beercow** [comment]
I’m not sure how hard this would be to implement without messing with the modules that are already created and don’t need the functionality.

**Comment by EricZimmerman** [comment]
so show me what you would want the srum-dump.mkape file to actually look like and i can see what i can do. like you said, it depends on work involved

**Comment by Beercow** [comment]
Maybe something like file mask can take a comma separated list and the %sourseFile% variably can be incremented by 1? Example: 

Description: 'SRUM-dump: Dump contents of the srum database'
Category: SystemActivity
Author: Brian Maloney
Version: 1
Id: 8e0a2314-79e4-48f2-81ad-a0719e8af680
ExportFormat: csv
FileMask: srudb.dat, SOFTWARE
Processors:
    -
        Executable: srum_dump_csv.exe
        CommandLine: -i %sourceFile% -t SRUM_TEMPLATE.xlsx -r %sourceFile1% -o %destinationDirectory% -q
        ExportFormat: csv

**Comment by EricZimmerman** [comment]
yea thats getting too complicated already. would be better for the program to, given a directory, find the files it wants to process IMO

**Comment by Beercow** [comment]
No problem. I’ll close this for now. Thanks.
