### ISSUE TITLE
Azure transfer works in gKAPE but not cmd KAPE

### ISSUE THREAD

**Issue by cgisecurity** [EricZimmerman/KapeFiles#201]
Using gkape, I can collect into a container, zip, and upload to Azure just fine. When I copy the command line version of the command and attempt it, it gives error "Azure Storage option present, but VHD(X)/Zip options are not. Azure Storage transfer cancelled."
Command example shown is:
.\kape.exe --tsource C: --tdest C:\kape\%m --target !SANS_Triage --vss --asu [blob address] --vhdx %m --gui

**Comment by cgisecurity** [comment]
Thanks for the quick fix!

**Comment by EricZimmerman** [comment]
issue was uri was not in quotes in gkape which caused issues with copy/paste into shell. fixed in 0.9.1.0
