### ISSUE TITLE
--sync use case

### ISSUE THREAD

**Issue by cyberpika2** [EricZimmerman/KapeFiles#227]
** KAPE version **
0.9.0.3

**Is your feature request related to a problem? Please describe.**
I have a use case for keeping KAPE fully updated in a linux environment prior to use.
GetKAPEUpdate.ps1 works wonderfully! However it triggers this helpful message:
```
* Be sure to update local target and module configurations!              
* This can be done via gkape (click Sync button) or run 'kape.exe --sync' from the command line.
```

**Describe the solution you'd like**
kape --sync solution in a linux environment as all media is **read only** once retrieved.

**Describe alternatives you've considered**
WINE MONO - not valid, outside it's capabilities.
docker - changes security profile of host (regulatory)

**Additional context**
If possible remaining with Powershell would be ideal as it blends with the rest of the automation.

Thank you!

**Comment by EricZimmerman** [comment]
the KAPE.exe binary is what does the syncing with the repo. 

you would have to emulate this in linux manually by:

1- downloading the kapefiles repo zip
2. unzipping it
3. either overwriting all files, or determining which are new
4. ???
5. profit
