### ISSUE TITLE
Error: Raw Copies across UNC paths are not supported

### ISSUE THREAD

**Issue by grook14** [EricZimmerman/KapeFiles#234]
** KAPE version # **
v0.9.3.0

**Describe the bug**
Attempting to get target files from a remote machine on our network. It does show some targets being downloaded, but they are unable to be analyzed (for example I tried to retrieve registry files from the same machine, but nothing showed in registry explorer when I attempted to load the offline hive). In the ConsoleLog.txt file it shows this error: _"Error: Raw copies across UNC paths are not supported"_
Command being used: ".\kape.exe --tsource \\COMPUTER_NAME\C$ --tdest C:\tools\Kape\Artifacts --target Chrome,ChromeExtensions --gui"

**To Reproduce**
Running this command listed above from "gkape.exe"

**Expected behavior**
From what I've read, KAPE should be able to pull info from a machine that is able to be analyzed over a UNC path. Unless I am mistaken and there is another alternative.

**Additional context**
Also getting messages saying that a file was deferred "due to IOException..."
I also tried the same thing to get a VHDX file instead and the file came back corrupted when trying to mount it to my system. 
Haven't found documentation to resolve this issue anywhere else. Hopefully you can help! Thank you!
![Screen Shot 2020-08-10 at 2 53 25 PM](https://user-images.githubusercontent.com/22206354/89830541-9513f580-db19-11ea-948b-66fe9a9ad288.png)

**Comment by EricZimmerman** [comment]
This is not a bug. It's not possible to read from a UNC share and get raw access or vscs when interacting with a UNC share. 

The deferred messages are normal. File is in use. 

run kape live on the endpoint that you want to collect via the command line and you'll see that it will work just fine. from there it's just a matter of you figuring out the best way for your environment on how to run it at scale

the trick is to run kape FROM the UNC share on the endpoint that you want to collect on because that will allow you to do everything that you want to do

Try that and let me know.

**Comment by grook14** [comment]
Ah I see. 

So just to clarify, you're saying the best option is to install Kape on the endpoint you want data from and then running it on that endpoint?

**Comment by EricZimmerman** [comment]
No I would just run it from a read only UNC share.

**Comment by grook14** [comment]
Update on where I'm at:

Got everything running correctly without errors in the log file! I appreciate the help on that!

However, when trying to load the registry hives into Registry Explorer, I get the error message that the the file I selected is "(... is not a Registry hive (bad signature)."

Is it still possible that Kape is collecting it in such a way that is not providing sound data? Any info on the matter would be helpful. 

Thank you!

**Comment by EricZimmerman** [comment]
I'd have to see the file that you're saying isn't loaded in a hex editor

What's the signature? Reg

**Comment by grook14** [comment]
Looks like nothing was shown in the Hex editor. This is supposed to be the "NTUSER.DAT" hive. 
![Screen Shot 2020-08-27 at 3 53 56 PM](https://user-images.githubusercontent.com/22206354/91498851-c14fa600-e87d-11ea-8ae9-bfd16322bf77.png)

**Comment by EricZimmerman** [comment]
So now the question is, what does it look like on the actual endpoint ?

**Comment by EricZimmerman** [comment]
do other hives load? if so, its that hive that is the issue on the other side.

**Comment by EricZimmerman** [comment]
i assume you are using the latest version of KAPE as well

**Comment by grook14** [comment]
Yes other hives load. I verified with some hives that I received from my SANS GCFE cert. But all hives obtained in my org so far have failed. 

And yes, I am using Registry Explorer 1.5.2.0

It looks to be like there is content inside of the hives when using Regedit on the endpoint. And the size of the hive is aroun 4000KB, so there should be data in it.

**Comment by EricZimmerman** [comment]
That's what's in memory, not on the disk.

Strange.

**Comment by grook14** [comment]
I also used Kape to take hives from my analysis machine just to check and it worked fine. I wonder if it still has something to do with I acquired them. 

On an enterprise level we were dragging and dropping the hives from the machine we needed hives from to my analysis machine. Could this be an issue?

**Comment by EricZimmerman** [comment]
dragging and dropping into RE? no that would not matter

**Comment by grook14** [comment]
Dragging between from the location the registry is on the network and then to my hoist machine, and then to my analysis VM.
