### ISSUE TITLE
Transfer Options is disabled

### ISSUE THREAD

**Issue by anelshaer** [EricZimmerman/KapeFiles#236]
** KAPE version # **
v0.9.3.0

**Describe the bug**
The Transfer Options which is next to Target Variables is disabled. but I see the equivalent options in the cli. 

**To Reproduce**

**Expected behavior**
I'm Expecting to see Options to transfer the Target Collection to SFTP, S3, AZ bucket. 
**Screenshots**
![Screenshot (2)_LI](https://user-images.githubusercontent.com/4087461/90321840-cf342b80-df4d-11ea-8d62-4cd2d59606f0.jpg)

**Comment by EricZimmerman** [comment]
Not s bug. Need to enable container mode then the transfer option opens up one you check the transfer checkbox. 

Lemme know

**Comment by EricZimmerman** [comment]
I would also use %m vs the env stuff.

**Comment by anelshaer** [comment]
Thanks a lot for the clarification, one last question regarding Transfer Options. is it planned or on Features requests to support GCP Bucket or we just go with SFTP option?

**Comment by EricZimmerman** [comment]
I don't know what a gcp bucket is, so most likely no. 😀

**Comment by EricZimmerman** [comment]
Looks like Google cloud? If there is an sdk for .net it's possible. 

Would you be willing to set up a test bucket I can use? I'd consider it if so.

**Comment by anelshaer** [comment]
Will look into it if it have an sdk, and will open a feature request to
better track it than having it in this dumb question . Will try to setup a
bucket and get back to you on that.

Really appreciate your time and efforts.

**Comment by anelshaer** [comment]
New Issue has been registered: https://github.com/EricZimmerman/KapeFiles/issues/237
