### ISSUE TITLE
Recursive --mlist --mdetail

### ISSUE THREAD

**Issue by nemesislvlup** [EricZimmerman/KapeFiles#245]
Hi Eric, 

KAPE depends on modules which we place in the bin folder ourselves. With new modules being added frequently, keeping the bin folder up to date can be a hassle.

The following code `kape.exe --mlist . --mdetail` helps with finding the missing binaries, but unfortunately this command is not recursive. There is therefore no easy way to make a list of all missing binaries for all modules in every subdirectory. 

We found a temporary solution by using `(Get-ChildItem -Recurse -Directory) | ForEach-Object { & "C:\kape\kape.exe" --mlist .\$_ --mdetail }` in Powershell. This works, but also gives an overview of the modules and not just the missing binaries. 

For this reason, my feature request to easily obtain a list of all missing binaries (with URL) **recursively** so we can easily update them or download them in a fresh KAPE install diractory.

Kind regards,
Bjorn

**Comment by EricZimmerman** [comment]
This is done and will be in 0.9.5.0
