### ISSUE TITLE
Synchronous Operation Errors when running KAPE on F-Response DiscoveryShare

### ISSUE THREAD

**Issue by forensicator0x01** [EricZimmerman/KapeFiles#247]
** KAPE version # **
0.9.3.0

**Describe the bug**
When running KAPE on an F-Response DiscoveryShare I get the following error message:

"Could not copy file 'R:\users\%redacted%\AppData\Roaming\Microsoft\Protect\%redacted%\Preferred' to 'C:\Users\%redacted%\Desktop\Live_Response_Data\R\users\%redacted%\AppData\Roaming\Microsoft\Protect\%redacted%\Preferred'. Error: Handle does not support synchronous operations. The parameters to the FileStream constructor may need to be changed to indicate that the handle was opened asynchronously (that is, it was opened explicitly for overlapped I/O)."

**To Reproduce**
1. Mount DiscoveryShare via F-Response Universal and assigned drive letter.
2. Run KAPE via an admin command prompt
3. Execute KAPE specifying the DiscoveryShare drive letter as the target source:
`kape.exe --tsource R: --tdest ..\Live_Response_Data --target Chrome`

**Expected behavior**
KAPE to extract artefacts and save to the specified destination

**Screenshots**
![image](https://user-images.githubusercontent.com/53453847/91259231-6f414e80-e7b1-11ea-812c-b8230ab1b7a3.png)

![image](https://user-images.githubusercontent.com/53453847/91259706-5ab18600-e7b2-11ea-9d89-e2374dfeae98.png)

**Additional context**

Hi Eric, hope you can help with this issue. I can run KAPE on F-Response mounted Disks and Volumes but run into the above issue with DiscoveryShares.

Cheers,
Dave

**Comment by EricZimmerman** [comment]
Try the same collection against a running system or aim mounted e01. If the problem goes away the issue would seem to be with f response discovery shares. I've never heard of those. What are they?

**Comment by forensicator0x01** [comment]
Not too sure on the underlying process for DiscoveryShares but it is an F-Response trademark...

"DiscoveryShares(TM) allow F-Response Universal users to access a remote machine's files and folders completely read-only with no file locking, whether they be Windows, Linux, or Apple OSX. DiscoveryShares(TM) offer a great way for both technical and non-technical users to access a remote machine's files and folders."

It could well be an F-Response issue. I'm testing with a host connected to a VPN (a common theme atm). Over the VPN we can only connect the DiscoveryShares as when connecting full disks or volumes they time out. I'm guessing maybe the DiscoveryShares pull the metadata of the file system and then only when the files are accessed that is when they are downloaded, which would help with any bandwidth constraints.

I can manually copy the files across but get these synchronous operation when running KAPE against it..

**Comment by EricZimmerman** [comment]
can you try using "normal" f-response and see if it behaves? ie mount a single disk or partition as a drive letter?

this assumes Universal has that

**Comment by forensicator0x01** [comment]
Thanks Eric. Yeah KAPE works great on F-Response mounted Disks and Volumes. Both of these tools have really enhanced our Live Response capability. The only issue I've found is with DiscoveryShares.

I will raise this with Matt and mention this thread...cheers.

**Comment by forensicator0x01** [comment]
Hi Eric, thanks again for looking into this. F-Response have gotten back to me and it doesn't look like this will be resolved any time soon, mainly due to the recent changes in Windows 10.

Closing off the issue.

**Comment by EricZimmerman** [comment]
Hi

Try this. Another user of the same software sent it. Relates back to what you said I think, but adding for posterity

Turns out the issue was related to using the "Discovery Share"  mounting that mounts/assigns a drive.  Using the standard "attach drive" and then pointing to the OS partition works. In cases where a drive letter isn't assigned using diskpart.exe takes care of the rest of it

**Comment by forensicator0x01** [comment]
Thanks for the update, Eric. Yeah I think what they're referring to there is not opting to attach a discoveryshare but instead attaching the OS volume or Disk via F-Response.

For our use case with devices connected to the VPN, we can't successfully browse to the file system of a volume/disk mounted via F-Response over the VPN.

But that's cool....we're still using KAPE for VPN-connected devices just not with F-Response...using KAPE via different method.

Cheers,
Dave
