### ISSUE TITLE
WinPmem: New Release.

### ISSUE THREAD

**Issue by Black-Thanos** [EricZimmerman/KapeFiles#292]
**KAPE version**
0.9.4.0

**Is your feature request related to a problem? Please describe.**
WinPmem Module in Live Response folder is not imaging Memory.

**Describe the solution you'd like**
I'd like it to image the Memory!

**Describe alternatives you've considered**
I have created a Module named **MindStone.mkape** utilising the latest release of the x64 version: _winpmem_mini_x64_rc2.exe_
(https://github.com/Velocidex/WinPmem/releases/download/v4.0.rc1/winpmem_mini_x64_rc2.exe).

.Mkape file can be found here: https://github.com/Black-Thanos/MindStone. 
Rename the winpmem_mini_x64_rc2.exe to WinPmem.exe and place the binary into '<KAPE_working_directory>/Modules/bin'. 
KAPE should now be able to find the executable at '<KAPE_working_directory>/Modules/bin/winpmem.exe'

**Issues**
Tested on Win10 only atm.
No Loggin yet.

**Comment by EricZimmerman** [comment]
Run your module with the debug switch and see what winpmem is doing. This has less to do with kape and more how winpmem is being called. Upload the consolelog with debug enabled and we can take a look

**Comment by Black-Thanos** [comment]
Correct, although I'm not sure it's worth our time, as the verson of WinPmem that is currently in KAPE (WinPmem, Module Id: 1d284835-417b-459e-a396-d228edea3808) used winpmem_3.3.rc1.exe which has now been superceded. There's a brand new build, winpmem_mini_x64_rc2.exe, (it's been removed from the Rekall project apparently). It appears the old commands no longer work. _The MindStone.mkape_ (Module ID: Id: de7486be-51e5-48b6-ae21-554953df6fa3) uses the new version [winpmem_mini_x64_rc2.exe](https://github.com/Velocidex/WinPmem/releases) and works well for me. A big plus for my case use is that it's much faster. I'll slooooooowly work on providing more options re. x86 version and Pagefile/Hiberfil acquisition. #Respect

**Comment by EricZimmerman** [comment]
ok cool. thanks!
