### ISSUE TITLE
Lnk files and jump lists

### ISSUE THREAD

**Issue by HomeGrownCoder** [EricZimmerman/KapeFiles#294]
Description: Lnk files and jump lists
Author: Eric Zimmerman
Version: 1.1
Id: 5fc6820c-4d30-4a38-9e43-5e0b788a4b0c

Just to confirm, I am working through a CTF and I am able to parse an lnk in autopsy that is being missed by the collector above.

Are you able to review and update this collection to include Location	"C:/ProgramData/Microsoft/Windows/Start Menu/Programs/*.lnk"

I checked a few times and did multiple exports, but that location is missed.

**Comment by EricZimmerman** [comment]
I can but did you wanna try to do a pr?

If not I can do it later this week

**Comment by HomeGrownCoder** [comment]
Sure let me give it a shot, will be my first PR on github :) but fine time to learn. I think I saw a post or link from you showing people how to go about the process.

**Comment by rathbuna** [comment]
@HomeGrownCoder if you don't know how to do it, PM me on the Digital Forensics Discord Server and I'm happy to walk you through.

**Comment by EricZimmerman** [comment]
so, do you plan on doing this, or should @rathbuna and i do it?

**Comment by EricZimmerman** [comment]
@rathbuna you can add this one the next time you are in the Targets.

**Comment by rathbuna** [comment]
Roger Wilco

**Comment by rathbuna** [comment]
Just did a PR for this. Good looking out @HomeGrownCoder. Thanks for bringing it up!

**Comment by EricZimmerman** [comment]
No. Pulled
