### ISSUE TITLE
Issues with multiple variables in single Target path

### ISSUE THREAD

**Issue by raptIRJuan** [EricZimmerman/KapeFiles#295]
Using the target path below with %user% and %id% variable in the same path seem to break the variable resolution. 

Name: Chrome Extension Files
Category: Communication
Path: C:\users\%user%\AppData\Local\Google\Chrome\User Data\*\Extensions\%id%\
Recursive: true

It seems to not resolve variables if there's more than one. It spits out a message saying the path C:\users\%user%\AppData\Local\Google\Chrome\User Data' wasn't found. If I hardcode the user or the %id% and leave a single variable in the path it resolves the single variable without issue.

**Comment by EricZimmerman** [comment]
Shoe me the full command line or at least the variables

**Comment by raptIRJuan** [comment]
Using gkape: .\kape.exe --tsource C: --tdest C:\Users\juan\Downloads\TEST\test_%d --tflush --target ChromeExtensionsSpecific --zip test --tvars id:aapocclcgogkmnckokdopfmhonfmgoek^user:juan --gui
[ChromeExtensionsSpecific.txt](https://github.com/EricZimmerman/KapeFiles/files/5423167/ChromeExtensionsSpecific.txt)

**Comment by EricZimmerman** [comment]
That parget looks like it's missing a \after c:\users

Can you adjust it and try again?

So it's c:\users\%user%\

**Comment by raptIRJuan** [comment]
Yeah, I noticed that too, but '\' after users is in the target file. Not sure why when I copied and pasted it into github it got stripped.

**Comment by EricZimmerman** [comment]
Ok I'll look into it

**Comment by EricZimmerman** [comment]
ok, could this be it, or did the \ disappear again? looks like there was not a backslash before the * by extensions

please confirm your path looks like this:

`Path: C:\users\%user%\AppData\Local\Google\Chrome\User Data\*\Extensions\%id% `

im starting to test this out now

you can use ` marks around your text to prevent escapes

**Comment by raptIRJuan** [comment]
Yep, it just disappeared again: `C:\users\%user%\AppData\Local\Google\Chrome\User Data\*\Extensions\%id%\`

**Comment by EricZimmerman** [comment]
This is fixed and will be in release 0.9.5.0

i kept reprocessing the original path, vs the updated path, so when more than 1 var was there, it introduced the error

`
Using Target operations
Processing target variable 'id:aapocclcgogkmnckokdopfmhonfmgoek'
Processing target variable 'user:eric'
Target variables found: 2
        Flushing target destination directory 'C:\Temp\tout2'
Cleaning up old _vssMount directory
        Creating target destination directory 'C:\Temp\tout2'
Found 1 targets. Expanding targets to file list...
Processing target: Chrome Extension Files
Expanding directory: 'c:\users\%user%\AppData\Local\Google\Chrome\User Data\*\Extensions\%id%\'
        'c:\users\eric\AppData\Local\Google\Chrome\User Data\BrowserMetrics\Extensions\aapocclcgogkmnckokdopfmhonfmgoek' does not exist. Skipping
        'c:\users\eric\AppData\Local\Google\Chrome\User Data\CertificateRevocation\Extensions\aapocclcgogkmnckokdopfmhonfmgoek' does not exist. Skipping
        'c:\users\eric\AppData\Local\Google\Chrome\User Data\Crashpad\Extensions\aapocclcgogkmnckokdopfmhonfmgoek' does not exist. Skipping
        'c:\users\eric\AppData\Local\Google\Chrome\User Data\Crowd Deny\Extensions\aapocclcgogkmnckokdopfmhonfmgoek' does not exist. Skipping
Getting files from 'c:\users\eric\AppData\Local\Google\Chrome\User Data\Default\Extensions\aapocclcgogkmnckokdopfmhonfmgoek'. Recursive: True, Mask: *
Found match: 'c:\users\eric\AppData\Local\Google\Chrome\User Data\Default\Extensions\aapocclcgogkmnckokdopfmhonfmgoek\0.10_1\icon_128.png'
Found match: 'c:\users\eric\AppData\Local\Google\Chrome\User Data\Default\Extensions\aapocclcgogkmnckokdopfmhonfmgoek\0.10_1\icon_16.png'
Found match: 'c:\users\eric\AppData\Local\Google\Chrome\User Data\Default\Extensions\aapocclcgogkmnckokdopfmhonfmgoek\0.10_1\main.html'
Found match: 'c:\users\eric\AppData\Local\Google\Chrome\User Data\Default\Extensions\aapocclcgogkmnckokdopfmhonfmgoek\0.10_1\main.js'
`

**Comment by raptIRJuan** [comment]
Great! Thanks for the quick fix!

**Comment by EricZimmerman** [comment]
if you wanna test this, email me at saericzimmerman/gmail and i can send you a test build
