### ISSUE TITLE
Targets need updated for Windows.old

### ISSUE THREAD

**Issue by EricZimmerman** [EricZimmerman/KapeFiles#315]
many targets look like this:

    -
        Name: Prefetch
        Category: Prefetch
        Path: C:\Windows*\prefetch\
        FileMask: '*.pf'

with Windows*

that expands to windows.old of course, but under there, we have another windows dir, like this:

$WINDOWS.~BT
PerfLogs
Program Files
Program Files (x86)
ProgramData
Recovery
Users
WINDOWS

because of this extra layer, we need to update all targets that refer to windows.old to be as shown below

    -
        Name: Prefetch
        Category: Prefetch
        Path: C:\Windows.old\Windows\prefetch\
        FileMask: '*.pf'

**Comment by rathbuna** [comment]
This is now complete
