### ISSUE TITLE
A target named * already exists...

### ISSUE THREAD

**Issue by computerclues** [EricZimmerman/KapeFiles#316]
Ran the powershell update today on kape with all modules and programs installed. After update, I get a series of target errors, even when just running modules with no target acquisitions. Below is a sample of the errors.

I shut everything down, I rebooted, and I removed all targets. Without the targets, the modules ran, but obviously, the targets cannot. When I replace the modules, I get the same errors no matter the operation.

```A target named 'EvidenceOfExecution' already exists at 'C:\Users\Stacy\Downloads\KAPE_with_modules\Targets\Compound\EvidenceOfExecution.tkape'. Target file names must be unique. Correct the issue and try again. Source file: 'C:\Users\Stacy\Downloads\KAPE_with_modules\Targets\Windows\EvidenceOfExecution.tkape'

A target named 'FileSystem' already exists at 'C:\Users\Stacy\Downloads\KAPE_with_modules\Targets\Compound\FileSystem.tkape'. Target file names must be unique. Correct the issue and try again. Source file: 'C:\Users\Stacy\Downloads\KAPE_with_modules\Targets\Windows\FileSystem.tkape'

A target named 'RegistryHives' already exists at 'C:\Users\Stacy\Downloads\KAPE_with_modules\Targets\Compound\RegistryHives.tkape'. Target file names must be unique. Correct the issue and try again. Source file: 'C:\Users\Stacy\Downloads\KAPE_with_modules\Targets\Windows\RegistryHives.tkape'```

**Comment by EricZimmerman** [comment]
delete or rename your targets directory, then do a kape.exe --sync to pull things down. 

you have dupe names for targets is all that means, and they must be unique. its even telling you which ones are dupes. so you can delete those if you like, but i would just nuke Targets and sync

**Comment by computerclues** [comment]
Thanx for the quick turnaround, Eric. I read the errors but did not see any obvious duplicates of the Target folder or within it. I nuked the Targets folder and restarted gkape, but that then errored out. AppEvents showed a gupdate error. After I close the error note, gkape appears to open, but nothing functions. The sync also failed. 

I have fresh installs (8.4 and 9.4) that are working correctly, so you can close this request. 

```The description for Event ID 0 from source gupdate cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Service stopped
```

**Comment by computerclues** [comment]
```The description for Event ID 0 from source gupdate cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.```

**Comment by EricZimmerman** [comment]
i have no idea what any of that is. gupdate isnt me. i dont use any services with kape

you can always add --debug to see more info on what targets are failing too

**Comment by computerclues** [comment]
Thanx again!
