### ISSUE TITLE
Retain local copy of zip-file upon transferring for instance Azure Blob

### ISSUE THREAD

**Issue by godstoge** [EricZimmerman/KapeFiles#319]
** KAPE version **
0.9.5.0

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Upon running KAPE, I would like .zip-file with the vhdx to be retained on the system where kape.exe was run.

kape.exe --asu   = transfer and delete .zip-file
kape.exe --asulc = transfer and retain local copy .zip-file

**Describe alternatives you've considered**
Run kape.exe without the transfer option and do a manual (scripted) upload of the file.

**Comment by EricZimmerman** [comment]
the switch would affect all transfer options, so will probably be something like

--rlc

for Retain Local Copy

and would come into play if any of the transfer options are used.

This will be in 0.9.6.0
