### ISSUE TITLE
Targets selected/Modules selected not tallying

### ISSUE THREAD

**Issue by rathbuna** [EricZimmerman/KapeFiles#324]
** KAPE version # **
0.9.5.0

**Describe the bug**
Targets selected and Modules selected not populating whatsoever as Targets and Modules are selected/deselected

**To Reproduce**
See GIF below

**Expected behavior**
Targets selected and Modules selected to be populated as they are selected/deselected

**Screenshots**
![o7bMMK8iJm](https://user-images.githubusercontent.com/36825567/101791742-e1743f80-3ad1-11eb-9817-b832c25f4d37.gif)

**Additional context**
Clicking outside of grid doesn't appear to populate the Targets selected or Modules selected.

**Comment by EricZimmerman** [comment]
this is fixed. the issue was i was only updating the labels when you used the context menus, vs just checking the boxes. doh
