### ISSUE TITLE
RegRipper timeline plugins missing computername in output

### ISSUE THREAD

**Issue by Karneades** [EricZimmerman/KapeFiles#367]
** KAPE version # **
0.9.6.0

**Describe the bug**
All RegRipper modules in [timelining](https://github.com/EricZimmerman/KapeFiles/tree/master/Modules/timelining) use a %computername% placeholder which should be expanded I guess (-s switch for RegRipper). But during my tests either from an elevated powershell or cmd and then running `kape.exe --msource C:\ --mdest .\output --module RegRipper_AppCompatCache_TLN` the string %computername% was in the output after running that module, so no expansion was made. I'm not sure what the purpose is, @mdegrazia could you clarify? Do these modules work for you that way?

And when running that module against existing hives from other computers on my analyst machine, the current computername should NOT be used.

**To Reproduce**
1. Use one of the modules with the name RegRipper*, e.g. RegRipper_AppCompatCache_TLN
2. Run that against --msource C:\Windows or against --msource <other existing SYSTEM hive folder>
3. Look at the RegRipper output

**Expected behavior**
The computer name is read during execution but not when running against existing hives on an analyst maschine.

**Comment by rathbuna** [comment]
I've never used RegRipper but what version are you using? I'm pretty sure those modules were made with version 2.X in mind. Beyond that, I don't know.

**Comment by EricZimmerman** [comment]
the module author will have to weigh in on this. This is a program being called issue vs kape.

**Comment by Karneades** [comment]
As I read in the compund for timelining (module Mini_Timeline) from @mdegrazia, it could be that this placeholders must be filled by hand during analysis. So maybe it's needed that an analyst fills all this placeholders and then run the plugin...Maybe its not even a plugin issue but a user issue ;)

**Comment by Karneades** [comment]
OK, got it, --mvars and module variables it is. Close the issue and sorry for the troubles.
