### ISSUE TITLE
gkape: add category column in target browser

### ISSUE THREAD

**Issue by Karneades** [EricZimmerman/KapeFiles#389]
**KAPE version**
0.9.6

**Is your feature request related to a problem? Please describe.**
gkape.exe: provide a category column in the UI in the target browser too, as already available in module browser. It helps finding targets.

**Describe the solution you'd like**
Add column in gkape.exe to also filter and search for the category of targets. The category field is available in the files.

**Describe alternatives you've considered**
n/a

**Additional context**
The feature request is for gkape. Although, it would be cool to have the category browser for target and module too on the cli. Currently, the folder names are used. Either extend it to the category field too or replace the folder name search with the category field. If both are the same (or should be the same) than it doesn't matter.

**Comment by rathbuna** [comment]
![JmR1kvqDDK](https://user-images.githubusercontent.com/36825567/106478040-ce993e00-6476-11eb-9329-027ae9c4bc10.gif)

**Comment by Karneades** [comment]
My bad... very sorry for wasting your time... thanks a lot!

**Comment by Karneades** [comment]
The field is empty despite targets have the field category on target level. The difference to the modules is that the category is only available on the target-level and not the file-level, the modules have a category field in the header.
