### ISSUE TITLE
Target not found but it is in the cmdline

### ISSUE THREAD

**Issue by chrisnewmanuk** [EricZimmerman/KapeFiles#395]
**KAPE version**

The version of KAPE you are running   0.9.6.0

**Describe the bug**

![image](https://user-images.githubusercontent.com/7243321/106595572-a6c7da00-654b-11eb-9638-6c5aa0639925.png)

**To Reproduce**

as above screenshow 

**Expected behavior**

MFT collected from C:\ in zip file names kape.zip and put in c:\tools\kape directory

**Comment by Karneades** [comment]
Try escaping the $ using a backtick, because $ is a powershell special charachter
```
... --target `$MFT...
```

**Comment by EricZimmerman** [comment]
Yep. A dollar sign in powershell denotes a variable so enclosing in a single quote will turn that off

**Comment by EricZimmerman** [comment]
I should add this only happens when running in powershell. gkape executing kape works as does cmd. Ps is preferred tho

**Comment by chrisnewmanuk** [comment]
> Yep. A dollar sign in powershell denotes a variable so enclosing in a single quotes will turn that off

Thanks.  Could you add a "copy for powershell" so that all of the escaping has been done?

**Comment by EricZimmerman** [comment]
just put all the target list in single quotes.

gkape is really used to build a command line and learn, so if you use it to generate a cli, adjust it as needed for your platform, save it to a txt file or ps1, and off you go.

the other option is to use batch file mode as it will deal with that automatically
