### ISSUE TITLE
Missing collection of info files for folders when collecting recylce bin

### ISSUE THREAD

**Issue by Karneades** [EricZimmerman/KapeFiles#403]
Currently, e.g. info files for folders are missing because they don't have an extension in [RecycleBin_InfoFiles.tkape](https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Windows/RecycleBin_InfoFiles.tkape).

Is this on purpose to only include files with file extensions? Or should we collect everything with removing the `.*` in the file masks? I don't know the context if this file mask was used on purpose.

We could use `FileMask: '$I*'`(same for data files by using `$R*`) to also include them, I would propose a PR if you see the value of those files too.

https://github.com/EricZimmerman/KapeFiles/blob/d653d4ef547126149beae92d4ed0a34f7705ab05/Targets/Windows/RecycleBin_DataFiles.tkape#L11

https://github.com/EricZimmerman/KapeFiles/blob/d653d4ef547126149beae92d4ed0a34f7705ab05/Targets/Windows/RecycleBin_InfoFiles.tkape#L11

**Comment by rathbuna** [comment]
I would suggest testing the results with the current Targets and compare to the results of the proposed Targets. Report back and we can make a decision but the Target in it's current form has been pulling what we need. If there's something we're missing then let us know!

**Comment by Karneades** [comment]
I made that diff and as I wrote, e.g. data and info files are missing in the output for files without an extension. But based on your comment, it already pulls all you need and these info files for files are of no concern, I guess. And yes, it's only seldom that files have no extension. But anyhow, I make a PR to also include them: https://github.com/EricZimmerman/KapeFiles/pull/404.

**Comment by EricZimmerman** [comment]
you can always make a new target that pulls EVERYTHING from Recycle, but the way it is now allows for collection of either/or of the two types of things

i would think would be rare on windows to have a file without extension since windows uses them so much. the MFT can help find those as well pretty quickly as a cross reference
