### ISSUE TITLE
Enhancement: Respect disabled targets and modules 

### ISSUE THREAD

**Issue by Beercow** [EricZimmerman/KapeFiles#41]
When syncing with GitHub, users have to move targets and modules that they don’t want to use back into the disabled folder. Would be useful for sync to check and place updated targets and modules in the active and disabled folders.

**Comment by EricZimmerman** [comment]
i will see what i can do, but i do not want it to get overly complicated.

perhaps if i do the update into the main folder, then check the !Disabled folder for a file with same name, and if found, move it to Disabled?

would that work?

**Comment by EricZimmerman** [comment]
This will be in the next release:

- When using --sync, any targets or modules in !Disabled folders will be removed from the Targets or Modules directory so they stay disabled

**Comment by EricZimmerman** [comment]
gonna close this since its done in 0.8.3.1 which should be out soon.

please test it when it comes out and if its not working as expected we can revisit. it worked on my testing for modules and targets tho.
