### ISSUE TITLE
Weird bug

### ISSUE THREAD

**Issue by Banaanhangwagen** [EricZimmerman/KapeFiles#42]
Strange thing happened.
My Desktop folder got wiped while executing gkape.exe. 

Let me try to explain what happened.
I executed `kape.exe` (only one target) and saved a vhdx on the following path `c:\users\me\Desktop`. The source was `c:`
Everything went well.

While the `cmd` stayed open, and the generated files stayed untouched on the Desktop, I opened `gkape.exe` and did exactly the same thing (exact same command and destination folder), except for the extra `--tflush --zv false --gui` flags.
When executing `gkape.exe` by clicking on `Execute`, it gave me immediately an error that the destination (Desktop) wasn't available and my Desktop was wiped. All files gone.

I used Kape 0.8.3.0 on a Win 10 (1803)

**Comment by EricZimmerman** [comment]
this is not a bug. you had KAPE  save its collection to the Desktop folder. you also had KAPE flush the tdest folder via the --tflush option, which deletes all files in --tdest before it runs.

the command line option does NOT have --tflush on by default. the GUI does.

This is shown via a tool tip in gkape:

![image](https://user-images.githubusercontent.com/4265254/54566506-6850c280-49a7-11e9-84ad-2418e50799c1.png)

and on the CLI options:

![image](https://user-images.githubusercontent.com/4265254/54566534-7d2d5600-49a7-11e9-889f-5b678126675c.png)

and in the manual.

What i would recommend is setting --tdest to something like C:\temp\tout or similar and NOT an existing folder where you have files you may want.

Sorry stuff got deleted but it is not a KAPE bug.

**Comment by Banaanhangwagen** [comment]
I understand. My bad.
On the other hand, It's not nice to learn it the hard way. I can imagine that other people will have the same surprise one day. 

Maybe for gkape deactivating the flush by default, so it is in line with command line kape?

**Comment by EricZimmerman** [comment]
that only sounds like a good idea on paper, because what if you were working a case and inadvertently combined two separate cases into the same folder? this would be a bad day for your case.

So in either case, flush being on, or off, by default, there will be people affected.

I chose to have tflush on by default in the GUI to prevent people from running into a situation where their case would be compromised by comingling evidence. since it seems most people choose to use the GUI, this protects most people from inadvertently falling into this situation.

it is unfortunate files were deleted. so far you are the second person that this has happened to our of 1000s of users tho, so the percentages are small.

**Comment by EricZimmerman** [comment]
I will see about adding a warning in 0.8.3.1 stating that one or more flush
options is enabed when execute is clicked with a yes/no dialog as a second
chance.

I do not want things to get repetitive with things that frustrates users
tho so this is a balancing act.

**Comment by EricZimmerman** [comment]
Hows this look?

![image](https://user-images.githubusercontent.com/4265254/54571379-ccc84d80-49b8-11e9-873f-fadec4268c19.png)

**Comment by Banaanhangwagen** [comment]
>
> I do not want things to get repetitive with things that frustrates users tho so this is a balancing act.

You are right.

I think your proposed solution is a good compromise.

**Comment by EricZimmerman** [comment]
Final dialog

it will only be shown if:

1. the destination directory exists
2. has files and/or directories
3. flush is enabled

![image](https://user-images.githubusercontent.com/4265254/54604705-cfa95980-4a1d-11e9-8f83-eeac7c187621.png)

**Comment by Banaanhangwagen** [comment]
Good job!
