### ISSUE TITLE
Possible issue with Kroll_Batch.reb

### ISSUE THREAD

**Issue by mark-hallman** [EricZimmerman/KapeFiles#424]
I'm getting a syntax error Kroll_batch.reb.  Error from the trace log is in this snippet.  More of the log is at the bottom of this post and the full log is attached.

`2021-02-18 22:43:49.2728 | D | Syntax error in 'BatchExamples\Kroll_Batch.reb':`

**Step that I took to get this error**
I have the reb file in `C:\Forensic Program Files\Collection\KAPE\Modules\bin\RECmd\BatchExamples\Kroll_Batch.reb` which I think is correct based on reviewing RECmd_Kroll.mkape.  

I have used KAPE and the RegistryHives.mkape compound target to collect all registry files 
`.\kape.exe --tsource E: --tdest G:\tmp\kape_out\tdest --target RegistryHives`
`E:\` is a mounted vhdx.  The Registry file are accessible.

I run this command to execute the RECmd_Kroll module.

`kape.exe --msource G:\tmp\kape_out\tdest\E --module RECmd_kroll --mdest G:\tmp\kape_out\mdest`

I get no results when I run the command.

![image](https://user-images.githubusercontent.com/16808320/108431247-8336ac00-723a-11eb-9956-252aac530d29.png)

Running with trace and debug
`kape.exe --msource G:\tmp\kape_out\tdest\E --module RECmd_kroll --mdest G:\tmp\kape_out\mdest --mflush --trace --debug`

Reviewing trace/debug log

```
2021-02-18 22:43:49.2728 | D | Syntax error in 'BatchExamples\Kroll_Batch.reb':
2021-02-18 22:43:49.2728 | D | (Line: 3, Col: 10, Idx: 68) - (Line: 3, Col: 13, Idx: 71): Exception during deserialization
2021-02-18 22:43:49.2728 | D | Input string was not in a correct format.
2021-02-18 22:43:49.2728 | D | The batch file failed validation. Fix the issues and try again


[2021-02-18T224331_ConsoleLog.txt](https://github.com/EricZimmerman/KapeFiles/files/6006401/2021-02-18T224331_ConsoleLog.txt)

**Comment by EricZimmerman** [comment]
Update recmd under the modules\bin folder and try again

**Comment by mark-hallman** [comment]
Will do.  Just so you know,  I updated Zimmerman tools about an hour ago
and then copied the files to KAPE/bin from there.
-Mark

**Comment by EricZimmerman** [comment]
Ok It could very well be an issue with data In The registry we need to look
at

Can we get the hives?

>

**Comment by mark-hallman** [comment]
Updating the recmd.exe in the /bin folder did the trick.  My previous response was referring to the .reb file.

**Comment by mark-hallman** [comment]
Thanks!

**Comment by rathbuna** [comment]
@mark-hallman if you have any feedback on the Kroll batch file, let me know! It's 1.0 with many revisions planned so long as I can keep finding new stuff to add to it. It's laid out much like the SANS_Triage Target in that it's verbose enough to be a good study resource. Lots of links to blog posts, videos, etc for most artifacts.
