### ISSUE TITLE
Some modules don't execute analysis tools correctly

### ISSUE THREAD

**Issue by mnrkbys** [EricZimmerman/KapeFiles#43]
The modules below don't execute analysis tools correctly.

BrowsingHitoryView.mkape
ApplicationFullEventLogView.mkape
PowershelOperationalFullEventLogView.mkape
PrintServiceOperationalFullEventLogView.mkape
SecurityFullEventLogView.mkape
SystemFullEventLogView.mkape

Because these modules don't pass correct folder name that has artifacts.
For example, kape.exe copy IE artifacts to %sourceDirectory% but BrowsingHitoryView.mkape  passes only %sourceDirectory% to "HistorySourceFolder" parameter.
In this case, it should pass %sourceDirectory%\<DriveLetter>\Users to "HistorySourceFolder" parameter.

**Comment by EricZimmerman** [comment]
have you read the comments in the modules? this is more a function of how the module was called or a shortcoming of the software used in the module to not find all the profiles it needs. the browser history one comes to mind on this. 

do you plan to submit working modules or a patch or is this for someone else to look into? also I assume all the proper binaries are in the bin folder?

**Comment by mnrkbys** [comment]
I'm sorry, I have overlooked those comment lines and understood.
So, these modules cannot specify with such other module as AmcacheParser and MTFECmd, right?

**Comment by EricZimmerman** [comment]
I'm not sure I follow. You can make compound modules. Just look at the manual or some of the event log modules.

**Comment by EricZimmerman** [comment]
you certainly can make a new module named AmcacheAndMFTECmd.mkape for example, then reference the individual modules in the new module.

again, see the examples included or the manual. 

if thats not what you meant we can reopen
