### ISSUE TITLE
Enable locked file copying of UNC target remotely using disk-mapped shadow copies.

### ISSUE THREAD

**Issue by AngusSckitt** [EricZimmerman/KapeFiles#448]
**KAPE version**
0.9.6.0

**Is your feature request related to a problem? Please describe.**
No, it's an improvement suggestion on a currently existing limitation.

**Describe the solution you'd like**
Sometimes you may want to collect artifacts as a way to investigate whether or not an incident is *currently* taking place in your network. That means you have a live, possibly volatile and, often, not currently physically accessible target: it may be a workstation in the possession of a remote collaborator, even a possible insider which may attempt to wipe evidence if confronted. The ability of running the extraction over the network via UNC path is tidy, but takes the juiciest fruits out of our reach with the inability of copying locked files, which are almost always what we need the most in order to confirm an incident and/or substantiate a claim.

Were KAPE able to make use of VSS (Volume Shadow Service) in order to expose and map a shadow copy from memory as a physical volume, copying artifacts in their runtime state would be made possible in remote over-the-network scenarios where the target is assigned via UNC path.

**Describe alternatives you've considered**
Before starting to use KAPE, I had been developing a PowerShell script which made use of [Craig Andera's ShadowSpawn](https://github.com/candera/shadowspawn) in order to make a shadow copy of my target directories and expose them as a disk mapping. I would then run robocopy to remotely extract the artifacts from the mapped shadow volume.

This, of course, came with challenges of its own:

1. The remote machine is not capable of remotely making use of the target's Windows Volume Shadow Service: ShadowSpawn had to be "injected" into the target machine and run with elevation. I accomplished that with the Invoke-Command cmdlet using administrative credentials after robocopy-ing ShadowSpawn and its dependencies to a temporary folder in the target machine. I've not looked into means to bypass this limitation and just worked around it, as my script was intended for use only in my corporation's network scope and I'd always have a privileged credential available.
2. ShadowSpawn itself is portable, but depends on Microsoft Visual C++ Redistributable 2010 installed. I incorporated into my script a function that would extract the installer package vcredist-2010_x64.exe, copy it into the target machine to a temporary folder, and silently run the installation remotely. If not logged properly, this *may* compromise the chain of custody... But I find it unlikely.

It would be interesting to see a similar feature for this kind of scenario

**Additional context**
I've not published my script in GitHub, yet... Planning to do that soon.

**Comment by EricZimmerman** [comment]
Interesting but too many moving parts. Run kape ON the endpoint FROM a unc share. 

Problem solved and no additional complexities added.

**Comment by AngusSckitt** [comment]
Fair enough - should've looked at the closed issue history, as you'd already mentioned this method in the past. Sorry about that.

Thanks for the feedback, though! I agree, it does add way too much complexity just to be able to run extraction from the same location we're going to be going the parsing. We'll be doing your way here.

I'll let you know if I come up with a simpler solution to make the extraction endpoint-side execution independent.
