### ISSUE TITLE
Kape v1.0.0.0 - ToolSync Module

### ISSUE THREAD

**Issue by b1draper** [EricZimmerman/KapeFiles#468]
When I run the tool sync module from within gkape I get an error mentioning that "C:\Forensic" is not recognized. It looks like it doesn't like the path C:\Forensic Program Files\KAPE\kape.exe --sync. I've verified that the executable is located in that folder. It looks like the command doesn't like the long file path name.
![image](https://user-images.githubusercontent.com/44442120/113571672-d1362200-95e4-11eb-9e98-afe17d73eba3.png)

**Comment by EricZimmerman** [comment]
I most likely need to wrap the sync call in quotes.

**Comment by b1draper** [comment]
That's what I was thinking too. I started digging through my kape directory
looking for the referenced .mkape modules to see if I can "fix" it by
adding quotes

**Comment by EricZimmerman** [comment]
@rathbuna can you take a look at the sync modules?

**Comment by rathbuna** [comment]
I actually think I've noticed this before too but hadn't gotten around to it yet. The other three sync modules work as expected, last I knew. Is that what you're seeing @b1draper?

**Comment by EricZimmerman** [comment]
My guess is single quotes around the path would do it. I assume there is a %kapedir% or something in there. That's what would need wrapped.

**Comment by rathbuna** [comment]
See https://github.com/EricZimmerman/KapeFiles/pull/469, this is now fixed.
