### ISSUE TITLE
MiniTimeline - Timeslice

### ISSUE THREAD

**Issue by b1draper** [EricZimmerman/KapeFiles#474]
When using the kape mini timeline and slice modules together; some times the module appears to hang and stop responding. I'm not sure if there's just too much data for the module to process and it hangs or if there's something wrong with the data; every other image it works like a champ. I'm thinking about trying to decrease the date range in the timeline and just make multiple timelines for smaller chunks of the desired date range.
![image](https://user-images.githubusercontent.com/44442120/114413268-d4e51e00-9b7b-11eb-9086-3fd51feb8508.png)

**Comment by EricZimmerman** [comment]
it would certainly be interesting if your idea of a smaller slice or trying to narrow down a file type pans out.

if you add --debug you can see the programs stdout to see if you have any errors or other helpful info

this has little to do with kape itself tho. i would hit up the plugin author to see what they can do about it.

**Comment by b1draper** [comment]
Thanks Eric. Cutting it down to smaller chunks hasn't made and difference. Given, this is test data I'm not too worried but thought it was interesting that the regripper plugin seems to die on the vine while processing the SYSTEM hive to create the appcompatcache_tln file to build the timeline. Trying a smaller window after a reboot

**Comment by EricZimmerman** [comment]
ok, ill close this for now, since it seems regripper related, or some other program in the chain other than KAPE. appcompat cache should be no more than 1024 entries which should be pretty instantaneous. my guess is there is an infinite loop in there somewhere in the regripper code.

**Comment by rathbuna** [comment]
https://github.com/mdegrazia/KAPE_Tools

This may be where you want to bring up issues for this Module.

**Comment by EricZimmerman** [comment]
If that's not in the description and or the documentation for the modules we probably want to get that added in the GitHub repo

**Comment by rathbuna** [comment]
Good idea, I'll get it added.
