### ISSUE TITLE
KAPE Only Advertises TLS 1.0

### ISSUE THREAD

**Issue by jmurchie88** [EricZimmerman/KapeFiles#479]
**KAPE version**
1.0.0.0

**Is your feature request related to a problem? Please describe.**
KAPE appears to only advertise support for TLS 1.0 when performing the handshake with Azure. Many organizations are enforcing minimum TLS version connections and as TLS 1.0 is deprecated this presents an inability to use the built-in Azure functionality.

**Describe the solution you'd like**
Support for TLS 1.2/1.3.

**Describe alternatives you've considered**
Scripting the copying/moving of artifacts to Azure using PowerShell and the native Azure modules.

**Additional context**
I have not tested if this issue also applies to the S3 functionality.

**Comment by EricZimmerman** [comment]
i use the azure SDK for this. surprising its so low by default.

ill see whats possible in the SDK

**Comment by antmar904** [comment]
Hi
I am trying to us TLS 1.2 when using Azure Blob and I am receiving the following error:

**The TLS version of the connection is not permitted on this storage account.**

TLS 1.2 is the minimum TLS version.

**Comment by EricZimmerman** [comment]
this should be fixed in next release

can you send me a URL for testing this that forces TLS 1.2 tho? that would be ideal

email works if you do not want to post it here

**Comment by antmar904** [comment]
> this should be fixed in next release
> 
> can you send me a URL for testing this that forces TLS 1.2 tho? that would be ideal
> 
> email works if you do not want to post it here

I can get you a URI in a bit.  What's the email?

**Comment by EricZimmerman** [comment]
saericzimmerman
gmail

**Comment by EricZimmerman** [comment]
1.0.0.1 is out now, please try and report back.

**Comment by antmar904** [comment]
email sent please test it out

**Comment by antmar904** [comment]
I'm getting the same error with kape 1.0.0.1

**Comment by EricZimmerman** [comment]
fixed. i forgot to upgrade the tls connection during the testing of the URL.

1.0.0.2 is out fixing this.

**Comment by antmar904** [comment]
it's now working, thank you!
