### ISSUE TITLE
vhd(x) examination

### ISSUE THREAD

**Issue by Banaanhangwagen** [EricZimmerman/KapeFiles#48]
My forensic tools (X-Ways but also FTK) have problems parsing the created vhd(x) container (when clicking on the Partition)

Can you reproduce this?
Is it kape-related or x-ways related?

Double-clicking on vhd(x) in Windows gives no issues.

**Comment by EricZimmerman** [comment]
use the 32 bit version of x-ways. 64 bit seemed to have had an issue. this was for vhdx files. havent tried the others.

its not a kape issue if windows mounts it =) 

closing, but please let me know if 32 bit works for you

**Comment by Banaanhangwagen** [comment]
32bit XWF has no problem opening it
hmmm

**Comment by EricZimmerman** [comment]
i would report the x64 bit issue to xways

**Comment by Banaanhangwagen** [comment]
Done!

**Comment by Banaanhangwagen** [comment]
Issue got fixed with v19.8 SR-5, released couple days ago.

**Comment by EricZimmerman** [comment]
Awesome! I emailed them a few times about it.
