### ISSUE TITLE
Using Timeline Explorer with KAPE

### ISSUE THREAD

**Issue by b1draper** [EricZimmerman/KapeFiles#481]
Used KAPE to process a collection created using the "KapeCollect". When processing the collection I selected the "!EZParser" and "MiniTimeline" and "Mini_Timeline_Slice_by_Date". When I open the timeline created I get the attached error "Erroc.Invalid member name". I'm able to open the timeline in Excel.

![image](https://user-images.githubusercontent.com/44442120/118547576-76d1ca80-b727-11eb-8c0d-fe01d535f0d6.png)

**Comment by EricZimmerman** [comment]
does the file have a header?

can you send the file, or the first 10 rows or something?

**Comment by b1draper** [comment]
![image](https://user-images.githubusercontent.com/44442120/118548854-c1a01200-b728-11eb-9b22-9b9fc1d8d622.png)

**Comment by EricZimmerman** [comment]
theres your problem. no header.

i would get with the module author, because thats not a good thing. headers are required.
