### ISSUE TITLE
KAPE Batch Mode --cu

### ISSUE THREAD

**Issue by antmar904** [EricZimmerman/KapeFiles#483]
Hi.
I am using the latest version of KAPE.  I just started testing batch mode by using the _kape.cli file.  I notice that the directories removed are Targets, Modules and Documentation however would it be possible to have the clean up function delete everything in the folder kape is being ran from after the collection, zip or hvdx then uploaded?  We are currently using Azure Storage for uploading the compressed data after being collected and I would like everything to be delete after the upload so we leave nothing on the workstation or server.

Thanks again for your work and support.

**Comment by EricZimmerman** [comment]
it cant delete itself, its running, so its already doing everything it can to clean up after itself. kape.exe with nothing else tho cannot do anything.

if you want to delete kape.exe youd have to sweep back with a powershell script or something.

i would have to do the same, but then the script would be left, and so on.

**Comment by EricZimmerman** [comment]
if you are seeing something OTHER Than kape.exe, lemme know, but that limitation is due to the fact kape.exe is running

**Comment by antmar904** [comment]
Sorry kape.exe is fine.  I was talking more about the collected zip data.  that is still being left after kape is done

**Comment by EricZimmerman** [comment]
it shouldnt be if its transferred off the box. there is a switch to NOT delete it i believe, but once the file gets moved to remote storage, it is not left on the local machine that i recall

what is the exact command line you are using?

**Comment by antmar904** [comment]
Hi.  Sorry for the late response.  I am currently having issues with my Azure account.  Once I get it fixed I will test again and post my findings.
