### ISSUE TITLE
Winpmem.mkape update

### ISSUE THREAD

**Issue by Richard1611** [EricZimmerman/KapeFiles#492]
Due winpmem updates, the specified winpmem command arguments within your winpmem.mkape dont work properly.

Check it out how I'm already using it: https://github.com/Richard1611/RemoteKapeTriage/blob/main/WinPmem.mkape

**Comment by rathbuna** [comment]
Feel free to do a PR here so it can be fixed.

**Comment by EricZimmerman** [comment]
make sure you are using the proper version of winpmem.

if the module expects say, v.1.5m you cannot just drop v2.3 and expect it to work
