### ISSUE TITLE
Densityscout module

### ISSUE THREAD

**Issue by Beercow** [EricZimmerman/KapeFiles#5]
The output from the densityscout module is saved in unicode (nul characters in between). Not sure if this is because of the way KAPE captures the output.

Example:

0 . 0 2 8 6 2 | Z : \ s u r g e - c o l l e c t - p r o \ C a s e s \ 1 0 . 8 0 . 2 . 2 3 6 \ 2 0 1 8 0 8 1 6 1 3 5 9 2 0 \ f i l e s \ C \ $ R e c y c l e . B i n \ S - 1 - 5 - 2 1 - 2 9 3 5 0 1 7 1 4 6 - 1 1 7 5 0 7 2 8 0 3 - 3 6 0 6 4 7 8 1 6 7 - 1 8 3 8 6 7 \ $ R W U O K 8 K . e x e 
 
 0 . 0 3 9 9 4 | Z : \ s u r g e - c o l l e c t - p r o \ C a s e s \ 1 0 . 8 0 . 2 . 2 3 6 \ 2 0 1 8 0 8 1 6 1 3 5 9 2 0 \ f i l e s \ C \ U s e r s \ x 0 6 5 8 5 5 \ A p p D a t a \ L o c a l \ T e m p \ n p p . 7 . 5 . 6 . I n s t a l l e r . e x e 
 
 0 . 0 4 7 8 4 | Z : \ s u r g e - c o l l e c t - p r o \ C a s e s \ 1 0 . 8 0 . 2 . 2 3 6 \ 2 0 1 8 0 8 1 6 1 3 5 9 2 0 \ f i l e s \ C \ $ R e c y c l e . B i n \ S - 1 - 5 - 2 1 - 2 9 3 5 0 1 7 1 4 6 - 1 1 7 5 0 7 2 8 0 3 - 3 6 0 6 4 7 8 1 6 7 - 1 8 4 8 8 2 \ $ R C Q Y U P Y . e x e 
 
![image](https://user-images.githubusercontent.com/10360919/52967523-f8332a80-336f-11e9-9239-e9ae2567bef8.png)

**Comment by EricZimmerman** [comment]
has to be a way around that. most likely due to the redirect somehow.

its a shame these programs do not allow saving to a file directly. ill see what i can do but if you keep looking that will be helpful too

**Comment by Beercow** [comment]
Densityscout can save to a file directly with the -o option.

**Comment by EricZimmerman** [comment]
then i would switch to that and drop the file name in the module config
you can do -o %sourcedirectory%\densityscout.txt

also look at the output in console log with --debug and see if it looks right

**Comment by Beercow** [comment]
Can't do a pull request right now but here is the fix.
change commandline to: 
CommandLine: -pe -p 0.1 -l 0.1 -d -r %sourceDirectory% -o %destinationDirectory%\DensityScout.txt
delete:
ExportFile: DensityScout.txt

**Comment by Beercow** [comment]
The documentation has ExportFIle listed as required.

**Comment by Beercow** [comment]
Pull request submitted. #6

**Comment by EricZimmerman** [comment]
ExportFIle is required? ill have to check and remove that if it does. it isnt required except for redirection

**Comment by EricZimmerman** [comment]
i pulled in your PR
