### ISSUE TITLE
kape.exe --sync failing without admin privs

### ISSUE THREAD

**Issue by rathbuna** [EricZimmerman/KapeFiles#502]
**KAPE version**

1.0.0.2

**Describe the bug**

`Administrator privileges not found! Exiting!!`

receiving this error when running an updater script not as admin

**To Reproduce**

1. kape.exe --sync without admin privs

**Expected behavior**

Sync without admin privs

**Screenshots**

N/A

**Additional context**

DMs from 6/20/2021 1700ish

**Comment by EricZimmerman** [comment]
done for next release
