### ISSUE TITLE
S3 Pre-signed URL issue

### ISSUE THREAD

**Issue by dfirhoze** [EricZimmerman/KapeFiles#519]
**KAPE version**

v1.0.0.3

**Describe the bug**

When attempting to ship data via the --s3url command, I get the error "Error validating S3 presigned Url! Exiting!! Error: The remote server returned an error: (403) Forbidden." I have tested the presigned URL with curl and am successfully able to curl a file to the bucket.  See command syntax below:
`.\kape.exe --tsource C: --tdest G:\kapetest --tflush --target Prefetch --s3url https://_bucketname_.s3.amazonaws.com/s3test.zip_XXredactedXX_Expires=1628616213 --zip s3test`

**Comment by EricZimmerman** [comment]
how did you generate the URL? i assume you are using a PUT (vs GET url?)

it looks like an error with the URL tho, because its throwing a forbidden error

i just did a test with a presigned URL generated via the SDK right now and it worked fine:

![image](https://user-images.githubusercontent.com/4265254/129097029-c45e6b9a-7c22-4d1e-8e8d-f2e6e9a6dc88.png)

**Comment by EricZimmerman** [comment]
add the debug switch. is it failing on the validation, or the actual upload?

i have no idea how your permissions are configured tho, but i know this works fine

**Comment by dfirhoze** [comment]
Apologies for lack of initial detail.  Yes, using a PUT url, using a lambda function:

![image](https://user-images.githubusercontent.com/88800427/129103615-9c22cce0-b886-4ab9-9ee6-9ca47edcc679.png)

Lambda role has these permissions:
![image](https://user-images.githubusercontent.com/88800427/129103788-ae880145-5a72-44f5-a7a7-4e0554a114de.png)

Here is the output with --debug:
![image](https://user-images.githubusercontent.com/88800427/129103503-cc315451-cfc0-4d82-85ba-144ce622b7d0.png)

**Comment by dfirhoze** [comment]
So I just tried changing the quotes around the url to single quotes, and now getting these errors. 

![image](https://user-images.githubusercontent.com/88800427/129105970-2686e63f-3565-4918-bbcd-77c0a79bee87.png)

**Comment by EricZimmerman** [comment]
well, its an aws/s3 issue because my test worked fine. again, i have no idea what your s3 bucket permissions look like, etc. but according to this:

https://medium.com/@lakshmanLD/upload-file-to-s3-using-lambda-the-pre-signed-url-way-158f074cda6c

its a bucket permission issue

**403 forbidden errors occur when your AWS credentials used to create the pre-signed URL does not have enough S3 permissions.**

this may have something too

https://stackoverflow.com/questions/46869962/getting-403-forbidden-when-uploading-to-s3-with-a-signed-url

as you can see tho, for my test, things work fine, so theres unfortunately not much i can do if S3 is complaining about permissions on your side

**Comment by EricZimmerman** [comment]
also i did my  test in powershell and had the URL in single quotes

**Comment by EricZimmerman** [comment]
you can see in the output it does not seem to see the zip switch either. if one of the container options is not there, it wont send the file.

your first test it did try to validate the URL, so i would stick to that command. once you get the permission issues resolved, it should be fine

**Comment by EricZimmerman** [comment]
the IAM stuff i use looks like this

```
@"{
    ""Version"": ""2012-10-17"",
    ""Statement"": [
        {
            ""Sid"": ""VisualEditor0"",
            ""Effect"": ""Allow"",
            ""Action"": [
                ""s3:PutObject"",
                ""s3:GetObject"",
                ""s3:DeleteObject"",
                ""s3:ListMultipartUploadParts""
            ],
            ""Resource"": ""arn:aws:s3:::<<BUCKETNAME>>/*""
        },
        {
            ""Sid"": ""VisualEditor1"",
            ""Effect"": ""Allow"",
            ""Action"": [
                ""s3:GetEncryptionConfiguration"",
                ""s3:ListBucket"",
                ""s3:GetBucketLocation""
            ],
            ""Resource"": ""arn:aws:s3:::<<BUCKETNAME>>""
        },
        {
            ""Sid"": ""VisualEditor2"",
            ""Effect"": ""Allow"",
            ""Action"": ""s3:ListBucket"",
            ""Resource"": ""arn:aws:s3:::<<BUCKETNAME>>/*""
        }
    ]
}"
```

adjust as needed for your use case. i dont think a Resource of * is allowed

**Comment by EricZimmerman** [comment]
closing for now. if we can show this is kape related we can reopen

**Comment by dfirhoze** [comment]
Hey Eric, thanks for your help on this in the past.  I have tried every method I could think of to get the pre-signed URL to work with KAPE, but am still running into issues with the Forbidden error.

As you can see below, I am able to successfully curl a file to S3 with the same URL I have also tried in KAPE (via cli and gui). 
![image](https://user-images.githubusercontent.com/88800427/134205955-15a1ff4e-fdcc-4e32-a0b5-1db7cf725e83.png)

Do you have any suggestions or methods you used to generate your URL?  I did notice in your original screenshot that your URL has "X-Amz-Expires" and "X-Amz-Date", whereas mine has the AWSAccessKey, Signature, x-amz-security-token, and Expires.

Here is the code snippet I am using to generate my URL.  Wondering if I might be missing some parameters?
![image](https://user-images.githubusercontent.com/88800427/134207104-d4284d67-f114-4915-9f68-e8b1c3af3a0b.png)

I appreciate any insight! Thanks again for your help.

**Comment by arsolutioner** [comment]
Hey,
I have the exact same issue with, i am generating PUT URL using lambda and the following code.

**Comment by EricZimmerman** [comment]
you MUST use signature version 4. it will NOT work without it.

```
# Imports
import boto3
from botocore.client import Config

# Globals
bucket = 'cloudymccloudface'

# Get hostname
host = input('Enter hostname: ')
host = host + '.zip'

# Generate presigned URL
psu = boto3.client('s3', config=Config(signature_version='s3v4')).generate_presigned_url(ClientMethod='put_object', Params={'Bucket': bucket, 'Key': host})

# Display output
print(psu)
---
```

**Config(signature_version='s3v4')**

is the key
