### ISSUE TITLE
Module: RDP-Usage 

### ISSUE THREAD

**Issue by Banaanhangwagen** [EricZimmerman/KapeFiles#52]
The module [RDP-Usage.mkape](https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/RDP-Usage-events.mkape) does not correctly execute.

When looking at the "command line" we see 
```
FROM '%sourceDirectory%','%sourceDirectory%' 
```

I don't think this is correct. The exact file needs to be precised there, in stead of the directory. Right?

Unfortunately, when manually changing this to 
```
FROM '%sourceDirectory%/Microsoft-Windows-TerminalServices-RemoteConnectionManager%4Operational.evtx','%sourceDirectory%/Microsoft-Windows-TerminalServices-LocalSessionManager%4Operational.evtx' 
```
it does not work. 
When executing it only with one `FROM`, it works. Ofcourse the INTO needs to be adapted to avoid overwriting.
(ping @Beercow )

**Comment by Beercow** [comment]
The from statement is correct. Everyone’s collection is not laid out the same. If you look at the comment in the script, the from example is from my environment. Your from statement would not work on my collection. That is why it needs to be setup by the end user. 

Can you turn on debug and trace and attach the log so I can troubleshoot?

**Comment by Banaanhangwagen** [comment]
Ok, you're proposed 'setup-by-end-user' works. Oddly, I tried it before several times, but it gave me no results.
Must been a typo then. :unamused:

Wouldn't it be easy to fill this already in, like [here ](https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/SMB-Server-Anonymous-Logon.mkape) or [here ](https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/Logon-Logoff-events.mkape)

Or, other idea, maybe write:
```
FileMask: Microsoft-Windows-TerminalServices-LocalSessionManager%4Operational.evtx
FileMask: Microsoft-Windows-TerminalServices-RemoteConnectionManager%4Operational.evtx

[...]

FROM '%sourceFile%','%sourceFile%' 
```
Like you did [here](https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/Detailed-Network-Share-Access.mkape)

**Comment by Beercow** [comment]
The problem with that is you can only have one FileMask, so that will not work. The modules you are referring to only point to one file. The other option would be to define variables for the two event log files on the command line. Eric, am I leaving any other options out?

**Comment by EricZimmerman** [comment]
no thats about it. the problem here is the parser, not KAPE. when my event log tool is done it will understand how to do a whole directory or single files, etc

**Comment by Beercow** [comment]
I could just point it to the event log directory but parsing that would take much longer that pointing it at two files. If Banaanhangwagen agrees, I think this issue can be closed.
