### ISSUE TITLE
Get-DoSvc4n6.mkape

### ISSUE THREAD

**Issue by Dracoriam** [EricZimmerman/KapeFiles#521]
# Error on Get-DoSvc4n6.mkape

> KAPE 1.0.0.3

I don't know if this relevant anymore, I don't know really well what this script is expected to do, I am a student just playing with KAPE. I like it, why not make it better :)

The problem is related to module Get-DoSvc4n6. The way it is called in the `.mkape` file doesn't allow it to run.

## Expected behavior

I don't know if this is relevant anymore because I don't know what this script is supposed to do completely . I did run it manually and I go as far as I understand zero results and some _TraceRpt.exe_ exceptions both. The run was on fresh windows VM. Based on `.SYNOPSIS Extracts different categories of events from DoSvc ETL logs` in [Get-DoSvc4n6.ps1](https://github.com/EricZimmerman/KapeFiles/blob/0c574025ee2404701e58287a4b9b8dce5f205722/Modules/LiveResponse/Get-DoSvc4n6.mkape) I expected something. Any way this is is not relevant to KAPE.

Problem as follows:

## To Reproduce
```powershell
PS Z:\USB\KAPE> .\kape.exe --msource C: --mdest Z:\USB\KAPE\KAPE-OUTPUT --module Get-DoSvc4n6 --debug
```
```
Enabled debug messages...
KAPE version 1.0.0.3 Author: Eric Zimmerman (kape@kroll.com)

KAPE directory: Z:\USB\KAPE
Command line: --msource C: --mdest Z:\USB\KAPE\KAPE-OUTPUT --module Get-DoSvc4n6 --debug

System info: Machine name: MSEDGEWIN10, 64-bit: True, User: IEUser OS: Windows10 (10.0.17763)
Validating configuration files
233 targets and 213 modules validated successfully

Using Module operations
        Get-DoSvc4n6: Determining correct processor based export type 'csv'...
                Found processor 'Executable: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe, Cmd line: -Command "& '%kapedirectory%\Modules\bin\Get-DoSvc4n6.ps1' %sourceDirectory% -SkipIP2Location -OutputPath %destinationDirectory%", Export: csv, Append: False'!
Discovered 1 processor to run.
Module name: Get-DoSvc4n6, Processor: Executable: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe, Cmd line: -Command "& '%kapedirectory%\Modules\bin\Get-DoSvc4n6.ps1' %sourceDirectory% -SkipIP2Location -OutputPath %destinationDirectory%", Export: csv, Append: False  , Category: SystemActivity
Executing modules with file masks...
Executing remaining modules...
        Running 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe': -Command "& 'Z:\USB\KAPE\Modules\bin\Get-DoSvc4n6.ps1' C:\ -SkipIP2Location -OutputPath Z:\USB\KAPE\KAPE-OUTPUT\SystemActivity"
 _____       _          _____        _____          _  _           __
/ ____|     | |        |  __ \      / ____|        | || |         / /
| |  __  ___| |_ ______| |  | | ___| (_____   _____| || |_ _ __  / /_
| | |_ |/ _ \ __|______| |  | |/ _ \\___ \ \ / / __|__   _| '_ \| '_ \
| |__| |  __/ |_       | |__| | (_) |___) \ V / (__   | | | | | | (_) |
 \_____|\___|\__|      |_____/ \___/_____/ \_/ \___|  |_| |_| |_|\___/
(v.2019-08-23)
Author: Gabriele Zambelli @gazambelli
https://github.com/forensenellanebbia
The script extracts different categories of events from DoSvc ETL logs. Use Get-Help for more details.
WARNING: Not enough parameters provided.
Examples:
.\Get-DoSvc4n6.ps1 dosvc.20181212_133942_927.etl -ExtractAll
.\Get-DoSvc4n6.ps1 C:\CustomLogPath -ExternalIP -SkipIP2Location -OutputPath C:\CustomOutputPath
.\Get-DoSvc4n6.ps1 C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Microsoft\Windows\DeliveryOptimization\Logs -DiskInfo
Executed 1 processor in 0.3985 seconds

Total execution time: 0.4107 seconds

```
Emphasis on:
```
WARNING: Not enough parameters provided.
```

Based on  [DoSvc4n6.ps1#L209](https://github.com/forensenellanebbia/powershell-scripts/blob/1b9474a1ed2ac478497bce71381e332f67abf038/Get-DoSvc4n6.ps1#L209) updated on `Latest commit f5c0ac0 on Jan 15, 2020` this if is enter if all 3 "ands" are present:

```powershell
if(
            $LogPath `
    -and `
            ($PSBoundParameters.Count -ge 2) `
    -and `
        ($PSBoundParameters.ContainsKey('DiskInfo') `
        -or $PSBoundParameters.ContainsKey('CaptivePortal') `
        -or $PSBoundParameters.ContainsKey('ExternalIP') `
        -or $PSBoundParameters.ContainsKey('InternalIP') `
        -or $PSBoundParameters.ContainsKey('LocalPeers') `
        -or $PSBoundParameters.ContainsKey('PowerState') `
        -or $PSBoundParameters.ContainsKey('ShutdownTime') `
        -or $PSBoundParameters.ContainsKey('ExtractAll'))
    ) {}
```

The module Get-DoSvc4n6 wont run because the way it is called currently in KAPE\Modules\LiveResponse\**Get-DoSvc4n6.mkape.**
```
    Executable: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    CommandLine: -Command "& '%kapedirectory%\Modules\bin\Get-DoSvc4n6.ps1' %sourceDirectory% -SkipIP2Location -OutputPath %destinationDirectory%"
    ExportFormat: csv
```
or
```powershell
.\Get-DoSvc4n6.ps1 %sourceDirectory% -SkipIP2Location -OutputPath %destinationDirectory%
```
or 
```powershell
.\Get-DoSvc4n6.ps1 C: -SkipIP2Location -OutputPath E:\USE\KAPE\KAPE-OUTPUT\HOSTNAME-DATE\mdest
```
 The above call cant run because its missing one more input parameter.

Adding simply `-ExtractAll` wont affect what we want from the script.

## Recommended Action

Change [Get-DoSvc4n6.mkape#L11](https://github.com/EricZimmerman/KapeFiles/blob/0c574025ee2404701e58287a4b9b8dce5f205722/Modules/LiveResponse/Get-DoSvc4n6.mkape#L11) 
From:
```
CommandLine: -Command "& '%kapedirectory%\Modules\bin\Get-DoSvc4n6.ps1' %sourceDirectory% -SkipIP2Location -OutputPath %destinationDirectory%"
```
To:
```
CommandLine: -Command "& '%kapedirectory%\Modules\bin\Get-DoSvc4n6.ps1' %sourceDirectory% -ExtractAll -SkipIP2Location -OutputPath %destinationDirectory%"
```

Thanks John

**Comment by rathbuna** [comment]
@forensenellanebbia tagging you on this

**Comment by forensenellanebbia** [comment]
Thanks for reporting the issue. I've just updated the module and added the collection of DoSvc ETL logs to _EventTraceLogs.tkape_. The latest version of [Get-DoSvc4n6.ps1](https://raw.githubusercontent.com/forensenellanebbia/powershell-scripts/master/Get-DoSvc4n6.ps1) can be downloaded from my [repository ](https://github.com/forensenellanebbia/powershell-scripts). The script aims to extract the events mentioned in this blog post of mine: [https://forensenellanebbia.blogspot.com/2018/12/what-was-my-ip-ask-dosvc-on-windows-10.html](https://forensenellanebbia.blogspot.com/2018/12/what-was-my-ip-ask-dosvc-on-windows-10.html)
