### ISSUE TITLE
I left a # Comment on L10 :( 

### ISSUE THREAD

**Issue by ecapuano** [EricZimmerman/KapeFiles#522]
Not sure if it matters, but I accidentally left a template comment on L10 - it validates and runs fine, so probably non-issue.

https://github.com/EricZimmerman/KapeFiles/blob/0c574025ee2404701e58287a4b9b8dce5f205722/Targets/Compound/ServerTriage.tkape#L10

**Comment by rathbuna** [comment]
I'll remove it. No worries and thank you for bringing it up. Even more thank you for using the guide 😎

**Comment by rathbuna** [comment]
https://github.com/EricZimmerman/KapeFiles/commit/1c1d4f4a0af8c3dd589c1a504dd4d0d85a6f71ca
