### ISSUE TITLE
Ignore folders on target

### ISSUE THREAD

**Issue by flukes86** [EricZimmerman/KapeFiles#527]
**KAPE version**
1.0.0.3

**Is your feature request related to a problem? Please describe.**
Collecting data from Onedrive folders is not needed 

**Describe the solution you'd like**
It would be good to have the option to ignore certain folders during the data collection.

**Comment by EricZimmerman** [comment]
Need more info. Give me an example

Why can you use a regex to simply copy certain things, effectively ignoring everything else?

**Comment by rathbuna** [comment]
I'll try to fill in the gaps here. @flukes86 are you saying you don't like how the OneDrive Target grabs user files? 

https://github.com/EricZimmerman/KapeFiles/blob/4d781c43e1e349e62cb5f0e7f4ba7b3d82fa9b30/Targets/Apps/OneDrive.tkape#L8 

If so, the beauty of Targets if you can comment out lines that you don't want your local copy of KAPE to grab. As in, do the following:

```
#    -
#        Name: OneDrive User Files
#        Category: Apps
#        Path: C:\Users\%user%\OneDrive*\
#        Recursive: true
#        Comment: "Caution -- This target will collect OneDrive contents from the local drive AND on-demand cloud files. Ensure your scope of authority permits cloud collections before use"
```

**Comment by rathbuna** [comment]
@flukes86 does that sound like an accurate assessment of the Issue?

**Comment by flukes86** [comment]
Thanks for looking into this, It was more like if i wanted to collect a bunch of artefacts on a system and there happens to be a onedrive folder on the endpoint which i wanted to ignore during my collection. 

For examples sake if i wanted to grab files from an endpoint with the extsion *.abcdef but not target the onedrive folder. Or if during a collection you dont have permission to take anything from a certain user profile on a system, you could block this out.

**Comment by EricZimmerman** [comment]
Yeah those kind of specific things you're going to have to get a little bit more custom with your unique requirements for the Target file

After your user profile question all of the targets support variables as well so you can get creative with your profile names there too

**Comment by flukes86** [comment]
Ok thats great, thanks for looking into this and steering me.

**Comment by rathbuna** [comment]
> 
> 
> Thanks for looking into this, It was more like if i wanted to collect a bunch of artefacts on a system and there happens to be a onedrive folder on the endpoint which i wanted to ignore during my collection.
> 
> For examples sake if i wanted to grab files from an endpoint with the extsion *.abcdef but not target the onedrive folder. Or if during a collection you dont have permission to take anything from a certain user profile on a system, you could block this out.

Check your !Disabled Targets folder. There's lots of examples in there which you can use to create specific Targets for your unique use cases. They provide a nice running start.

https://github.com/EricZimmerman/KapeFiles/tree/master/Targets/!Disabled
