### ISSUE TITLE
Compound Module Output Locations

### ISSUE THREAD

**Issue by jackdyson1399** [EricZimmerman/KapeFiles#531]
**KAPE version**
v1.0.0.3

**Is your feature request related to a problem? Please describe.**
I am creating my own compound modules for my employer to use and I would like the parsed output files to be saved into a custom named subfolder in the selected module destination. Having looked at the Module guide in this repo, this output subfolder is based on the 'Category' field, and it appears for compound modules, it will always take the lowest level category.

For example, say I would like to run the SystemInfo.mkape and NetSystemInfo.mkape modules, they would be outputted to a subfolder called 'LiveResponse' in the module destination folder, as those two modules have 'LiveResponse' as their category. 
However, if I then call these two modules from my custom compound module with a category of 'System Information', it will still output their results into the 'LiveResponse' subfolder not the desired 'System Information' subfolder.

**Suggested Solution:**
Let the subfolder for the outputted parsed file be named after the category field of the parent mkape file.

**Possible Alternatives:**
Alternatively, include an option to specify the subfolder's name, though I imagine this would require a lot of rework.

**Comment by rathbuna** [comment]
If you're maintaining local Modules, then you should utilize the !Local folder. In this instance, it may be advised for you to take SystemInfo.mkape and NetSystemInfo.mkape, rename them adding CUSTOM to the filename or something that makes them unique from the one in the repo, change the [GUID](https://www.guidgenerator.com/) for the ones that'll be in !Local so they don't collide with the ones in the main repo, then point your Compound Module to the !Local filenames, i.e., !SystemInfo.mkape and !NetSystemInfo.mkape (! will put the Modules towards the top of gKape's Module list). That way you can always maintain your local copies that work for your unique use case. 

Does that solve your problem? That way you can choose whatever Category you want for your !Local Modules.

**Comment by jackdyson1399** [comment]
Hi, 
Yes I would imagine that would work, I will try this now.
However my custom compound module uses many modules which would then need copying over, changing and then manually maintaining/updating regularly.
I was just wondering if it would be possible to implement a more user friendly way to do this. Such as modules inheriting their parent's category (if set) rather than me duplicating 80% of the modules locally to change their category.

I do understand the reason for this separation, and I will put my compound module into the !local folder however it would be nice not to have to duplicate that many modules.

**Comment by EricZimmerman** [comment]
This is not a simple change. Compound stuff works by drilling down to the lowest, non compound modules. 

Why aren't the existing categories sufficient?

**Comment by rathbuna** [comment]
Making that change would then invalidate !EZParser, which is the most commonly used Module. Whatever Category !EZParser has set would then override the lowest level categories, and the output would not have separate folders that separate MFT output from LNK file output, etc. It would be a huge mess of CSVs that aren't separated out. KAPE thankfully allows anyone to change things how they and maintain their own custom Targets and Modules to have the tool work how you want it to. Edge cases can be accommodated but usually it's on the individual, not maintainers of the tool, to make the edge case work for them so long as the tool gives you the ability to do that, which KAPE already does.

**Comment by jackdyson1399** [comment]
Okay not to worry. rathbuna has provided an method which works.

The reason I would like to change some of the categories is because my team wish to separate the LiveResponse modules up further into categories like 'Networking', 'SystemInformation' as the whole of their work is LiveResponse. But I appreciate this is a company specific view. 
It is just a minor query I thought I would raise to see if there was an easy fix. But as you have explained this would complicate things. I will put the work in myself to customise it, KAPE is a great tool because of this!

**Comment by rathbuna** [comment]
It's always worth asking but thanks for understanding the workaround for your company's specific use case. It may not be a bad idea to spin up a private repo on GitHub for your company so you all can maintain what you effectively will store in your `!Local` folder company-wide. That's what I'd do if I was in that situation but YMMV.
