### ISSUE TITLE
Enhancement to zip target and module output in one archive

### ISSUE THREAD

**Issue by gs3cl** [EricZimmerman/KapeFiles#571]
**KAPE version**
1.1.0.0

**Describe the solution you'd like**
I would like to have an additional option to zip the whole folder after Triage not seperate. For more refer to attachment
![KAPE_suggestion](https://user-images.githubusercontent.com/89155053/140820514-48e6f07a-4feb-48cc-b56a-48ae9b714882.png)

Regards,

**Comment by EricZimmerman** [comment]
this is more work than it seems.

**Comment by gs3cl** [comment]
Hey Eric, for me you can close the issue/request I found a workaround thats works.
