### ISSUE TITLE
SFTP Permission Denied Error

### ISSUE THREAD

**Issue by TestLeper** [EricZimmerman/KapeFiles#576]
Kape Version:
Latest as of November

Issue:
I am getting a permission denied error when trying to connect to an atmoz\sftp container hosted in azure tied to an azure file share.

The image deployed from here https://docs.microsoft.com/en-us/samples/azure-samples/sftp-creation-template/sftp-on-azure/

I can connect and upload using native linux sftp and FileZilla client with no issue.

There is an 'upload' folder that is mounted to the azure fileshare and have tried various combos of lead and trailing slashes and different folder names 

The Kape command I'm using for testing is:
.\Kape.exe --tsource C: --tdest C:\KapeOutput --target P2PClients --scs 52.255.x.x --scp 22 --scu [user] --scpw [pass] --scd upload --vhdx test

It connects fine but then errors out with

"Error validating SFTP Server! Exiting!! Error: Permission denied; Permission denied."

**Comment by EricZimmerman** [comment]
not sure what i can do if your FTP server wont allow writes.

did you enable --debug to see if there are more details?

if kape cant write to the directory, it wont even do the collection for it to just fail later.

**Comment by TestLeper** [comment]
The directory does allow writes and works as expected with other ftp software, it’s only kape that seems to have an issue. I even created a second directory inside the upload folder through FileZilla while kape was saying it couldn’t create a directory. 

I tried debug and trace and it doesn’t add any more info around the sftp session unfortunately

**Comment by EricZimmerman** [comment]
if it cant create a file in the directory specified, its going to error. its failing even creating the test file from the looks of it. what does the logs on the azure ftp side of things show?

can you try the same test using kapes built in FTP server? there is a sample config on the kapedocs site.

does the upload directory already exist?

can you set up a test server for me to use and supply the creds?

**Comment by TestLeper** [comment]
"What does the logs on the azure ftp side of things show?" Not a whole lot unfortunately. Since it's a lightweight container it doesn't have logging set up in the image so getting anything useable is a chore (https://github.com/atmoz/sftp/issues/86) 

 "can you try the same test using kapes built in FTP server? there is a sample config on the kapedocs site." I will try after this next batch of meetings and let you know 

"does the upload directory already exist?" Yes the upload folder already exists and is what is tied back to the azure storage account. So it goes /home/sftp/upload/ and then inside upload you can create new directories and upload files, etc.

"can you set up a test server for me to use and supply the creds?" Be more than happy to, where should I send?

**Comment by EricZimmerman** [comment]
my email is fine

saericzimmerman
gmail

**Comment by EricZimmerman** [comment]
ok issue fixed

the problem is that i was only changing to the directory specified if it didnt exist and i had to create it. i moved the change directory stuff out of the dir create section and now it should be fine. will email you a build to test

**Comment by TestLeper** [comment]
That fixed the issue, was able to successfully connect and upload a test package. Thank you!!!

**Comment by EricZimmerman** [comment]
i uploaded my $ Boot file.

dont do anything crazy with it

**Comment by EricZimmerman** [comment]
will push 1.1.0.1 here soon

**Comment by TestLeper** [comment]
> i uploaded my $ Boot file.
> 
> dont do anything crazy with it

Already deleted :P

**Comment by EricZimmerman** [comment]
1101 is up
