### ISSUE TITLE
Errors regarding the "Target options"

### ISSUE THREAD

**Issue by F1H3** [EricZimmerman/KapeFiles#584]
KAPE version: 0.9.0.1

I tried to use the "Target options" -> "!SANS_Triage_31621cd8-908f-4dac-b841-8b0be229d7d2" to perform the files collection on a live endpoint but it failed to run properly. 

![image](https://user-images.githubusercontent.com/90133767/144568575-74431419-3279-49df-98ab-732d782bea1f.png)

![image](https://user-images.githubusercontent.com/90133767/144570018-ff44ee16-0271-45ef-900f-390a8cae19ec.png)

Similar errors occur for all the options in "Target options".

**To Reproduce**

1. Execute the gkape.exe
2. Click on "Target options"
3. Scroll down to check the "!SANS_Triage"/"!BasicCollection"/any others

**Expected behavior**
The "Target options" should be use to perform file collection on a live endpoint.

Please correct me or advise if anything I can try to make things work.

Thank you!

Regards,
F1H3

**Comment by AndrewRathbun** [comment]
Any reason why you're using a very outdated version of KAPE?

**Comment by EricZimmerman** [comment]
Update to 1.1.0.1 and try again

**Comment by AndrewRathbun** [comment]
0.9.0.1 2020-03-10

Please update KAPE and report back. If you can't manage updating KAPE on your own, please strongly consider using my PowerShell script that'll cover everything that needs to be updated. You are missing out on so much. 

https://github.com/AndrewRathbun/KAPE-EZToolsAncillaryUpdater

I break down what this script covers here: https://youtu.be/mIb1GQP3ciE
