### ISSUE TITLE
Enhancement: Export format option 

### ISSUE THREAD

**Issue by mcvic1rj** [EricZimmerman/KapeFiles#591]
**KAPE version**
v1.1.0.1

**Is your feature request related to a problem? Please describe.**
When working with a module that has multiple `ExportFormat` options, it is not possible to select a non-default format if it is not in the radio button group.

This can be worked around by either:
- Changing the module's default `ExportFormat` property
- Running `kape.exe` on the command line with the option `--mef {desired format}`

**Describe the solution you'd like**
- Document a preferred list of `ExportFormat` values that are included in the GUI (Current State: CSV, HTML, JSON)
- Update the verbiage of Export Format to more correctly identify it is a preference
- Specify additional formats are available via the `kape.exe` cli

**Describe alternatives you've considered**
- On load of modules, build a list of the `ExportFormat` values seen and update the GUI to reflect those in a dropdown list
- Add a Freeform text field to allow the user to specify their own `ExportFormat` value.

**Additional context**
Below is a mockup of the verbiage changes suggested
![image](https://user-images.githubusercontent.com/10363041/148112389-b9edc937-2676-4115-93d2-bb95d0e8baad.png)
![image](https://user-images.githubusercontent.com/10363041/148113174-5b66f500-fd4c-4945-a93a-6462406aa891.png)

**Comment by EricZimmerman** [comment]
use the cli directly if it gets crazy. pick one of the other optons, KAPE builds args. adjust the --mef are. done?

this is the easiest way

if i did adjust the GUI for this, it would be to add a text box, called 'Other' or something similar, that lets you enter something, but this is just about as much work as above.

what other export formats are we missing besides what we have already?

**Comment by mcvic1rj** [comment]
I ran into this with XML but it appears that there are just over a dozen different export format options currently
Checking current modules from this repo, I get the below counts/types. 

```powershell
gci -Recurse |?{$_.FullName -like '*.mkape'}|%{Get-Content -Path $_.fullname|Select-String "Exportformat:"}|?{$_ -like ' *'}|%{$_.tostring().trim()}|Group-Object |select Count,Name|sort count -Descending

Count Name
----- ----
  151 ExportFormat: ""
   82 ExportFormat: csv
   79 ExportFormat: txt
   43 ExportFormat: json
   38 ExportFormat: greptext
    6 ExportFormat: html
    4 ExportFormat: xml
    2 ExportFormat: sqlite3
    2 ExportFormat: log
    2 ExportFormat: raw
    1 ExportFormat: bodyfile
    1 ExportFormat: xlsx
    1 ExportFormat: dmp
    1 ExportFormat: efu
    1 ExportFormat: tsv
    1 ExportFormat: db

```

**Comment by EricZimmerman** [comment]
the GUI is really meant to learn the syntax and help drive things, especially when getting started. for the more esoteric export formats, i would expect the end user to be using the CLI

not sure why there are modules with ExportFormat thats the empty string. can you share some of the names where this is the case?

**Comment by EricZimmerman** [comment]
found one
Sync_SQLECmd.mkape

that makes sense its "" tho

**Comment by mcvic1rj** [comment]
Sorry for the picture. In these case there seems to be a lot of `""` in Compund or general run this program (Like kape sync)
![image](https://user-images.githubusercontent.com/10363041/148121500-1bf6f7b8-c2ed-4ef2-94bd-f3b8a5ba512c.png)

**Comment by mcvic1rj** [comment]
Upon refinement, I found this affects a total of 4 modules. Based on the low impact and clarification on what the gui is for, I think this is a non-issue. 

Affected modules:
```text
File: C:\Forensic Program Files\Collection\KAPE\Modules\Apps\Everything_ParseEFU.mkape
        Default: ExportFormat: ""
        Available: ExportFormat: efu
File: C:\Forensic Program Files\Collection\KAPE\Modules\EZTools\EvtxECmd\EvtxECmd.mkape
        Default: ExportFormat: csv
        Available: ExportFormat: xml
File: C:\Forensic Program Files\Collection\KAPE\Modules\EZTools\EvtxECmd\EvtxECmd_RDP.mkape
        Default: ExportFormat: csv
        Available: ExportFormat: xml
File: C:\Forensic Program Files\Collection\KAPE\Modules\Windows\Windows_schtasks.mkape
        Default: ExportFormat: csv
        Available: ExportFormat: xml
```
Here is the PowerShell used to generate that list:
```powershell
$guiOptions=@('csv', 'json', 'html', '""')
gci -Recurse | ? {
    $_.FullName -like '*.mkape' } | % {
    $file = $_.fullname;
    $matches = Get-Content -Path $file | Select-String "Exportformat:";
    foreach ($match in $matches) {
        $s = $matches[0].tostring().trim();
        $c = $match.tostring().trim();
        $f = $c.Split(' ') | select -Last 1;
        if ($s -ne $c) {
            if ($f -notin $guiOptions) {
                write-host "File: $file";
                write-host "`tDefault: $s";
                write-host "`tAvailable: $c"
            }
        }
    }
}
```
Apologies. I thought this affected more modules than it does.

**Comment by EricZimmerman** [comment]
no worries! this is a good discussion because it lets us explore where we can make things better. thanks for putting the numbers together!

**Comment by AndrewRathbun** [comment]
Really great work @mcvic1rj it's awesome to see so much effort put in to help resolve an issue. Cheers man!
