### ISSUE TITLE
CrowdStrike_CrowdResponse.mkape calls non-existent executable

### ISSUE THREAD

**Issue by La3ZmC4A** [EricZimmerman/KapeFiles#606]
**KAPE version**

1.1.0.1

**Describe the bug**

fresh crowdresponse download from binaryurl: in https://github.com/EricZimmerman/KapeFiles/tree/master/Modules/Apps/CrowdStrike_CrowdResponse.mkape

BinaryUrl: https://www.crowdstrike.com/wp-content/uploads/2020/03/CrowdResponse.zip

when extracted there is no "crowdresponse64.exe" (as run error shows below)

it is just called "crowdresponse.exe"

run-time error
Running 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe': -Command "& 'C:\tools\ir\kape\Modules\bin\CrowdResponse\CrowdResponse64.exe' -i C:\tools\ir\kape\Modules\bin\CrowdResponse\config.txt -o C:\temp\ir\liveresponse\LiveResponse\CrowdResponse.xml;&'C:\tools\ir\kape\Modules\bin\CrowdResponse\CRConvert.exe' -v -c -f C:\temp\ir\liveresponse\LiveResponse\CrowdResponse.xml -o C:\temp\ir\liveresponse\LiveResponse;Remove-Item 'C:\temp\ir\liveresponse\LiveResponse\CrowdResponse.xml'"
                & : The term 'C:\tools\ir\kape\Modules\bin\CrowdResponse\CrowdResponse64.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**To Reproduce**

1. get BinaryUrl to download zip from "https://github.com/EricZimmerman/KapeFiles/tree/master/Modules/Apps/CrowdStrike_CrowdResponse.mkape"
2. download zip, extract in appropriate location
3. run liveresponse with crowdresponse option
4. see error

**Expected behavior**

expect CrowdStrike_CrowdResponse.mkape to call the correct executable

**Screenshots**

![Screenshot from 2022-02-09 10-47-45](https://user-images.githubusercontent.com/75484438/153262172-dd6ea50e-0a37-476e-8a6c-8b6e61575b0a.png)
![Screenshot from 2022-02-09 10-48-03](https://user-images.githubusercontent.com/75484438/153262177-9e5a1964-d86b-4dbb-899a-73d6876d2863.png)

attached

**Comment by EricZimmerman** [comment]
Have you reached out to the module author on this?

**Comment by AndrewRathbun** [comment]
^^ beat me to it

If you can find the updated URL, then do a PR and correct the BinaryURL value.

**Comment by La3ZmC4A** [comment]
i don't know how to reach out to the author

the binary url is correct, it's the execution commandline that is wrong

**Comment by EricZimmerman** [comment]
I would assume that the author did a PR into this repository so it can be tracked down that way and at least link back to his GitHub profile

**Comment by AndrewRathbun** [comment]
Have you tried executing the Module after modifying it to remove the 64 from the filename?

**Comment by AndrewRathbun** [comment]
https://github.com/MohamedEl-Hadidi is the author

**Comment by AndrewRathbun** [comment]
Before the great reorg of October 13, 2021, you can see the history of that particular Module, which can be found here: https://github.com/EricZimmerman/KapeFiles/commits/5a238001f2b952778c22699bbfc35061465a80f0/Modules/LiveResponse/CrowdResponse.mkape

**Comment by gs3cl** [comment]
Hey, change the binary to `CrowdResponse64.exe` and then it works fine.

`.\kape.exe --msource C:\ --mdest C:\temp\mout2 --mflush --module CrowdStrike_CrowdResponse --mef csv --gui`

```
Using Module operations
        Flushing module destination directory 'C:\temp\mout2'
        Creating module destination directory 'C:\temp\mout2'
                Found processor 'Executable: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe, Cmd line: -Command "& '%kapedirectory%\Modules\bin\CrowdResponse\CrowdResponse64.exe' -i %kapedirectory%\Modules\bin\CrowdResponse\config.txt -o %destinationDirectory%\CrowdResponse.xml;&'%kapedirectory%\Modules\bin\CrowdResponse\CRConvert.exe' -v -c -f %destinationDirectory%\CrowdResponse.xml -o %destinationDirectory%;Remove-Item '%destinationDirectory%\CrowdResponse.xml'", Export: csv, Append: False'!
Discovered 1 processor to run.
Executing modules with file masks...
Executing remaining modules...
        Running 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe': -Command "& 'D:\FORENSICS\KAPE\Modules\bin\CrowdResponse\CrowdResponse64.exe' -i D:\FORENSICS\KAPE\Modules\bin\CrowdResponse\config.txt -o C:\temp\mout2\LiveResponse\CrowdResponse.xml;&'D:\FORENSICS\KAPE\Modules\bin\CrowdResponse\CRConvert.exe' -v -c -f C:\temp\mout2\LiveResponse\CrowdResponse.xml -o C:\temp\mout2\LiveResponse;Remove-Item 'C:\temp\mout2\LiveResponse\CrowdResponse.xml'"

```

There is no other URL you can find information about the tool here:
https://www.crowdstrike.com/resources/community-tools/crowdresponse/

and then it goes to the same URL like in the module

I can make a PR later together with a new module.

Regards

**Comment by AndrewRathbun** [comment]
Well, here's food for thought. Changing it to `*64.exe` may serve the purpose to solve this issue, but it is possibly a misrepresentation. Full disclosure, I know nothing about the tool, but if the tool isn't 64-bit, then maybe the Module needs to have the 64 removed and the binary is correct the way it is. A simple removal of the 64 from the Module is all that needs to be done here, it seems.

**Comment by La3ZmC4A** [comment]
changed .mkape file to only call "**crowdresponse.exe**" instead of "crowdresponse64.exe"

PS C:\tools> c:\tools\ir\kape\kape.exe --msource C:\ --mdest C:\temp\ir\liveresponse --mflush --module CrowdStrike_CrowdResponse
KAPE version 1.1.0.1 Author: Eric Zimmerman (kape@kroll.com)

KAPE directory: C:\tools\ir\kape
Command line: --msource C:\ --mdest C:\temp\ir\liveresponse --mflush --module CrowdStrike_CrowdResponse

System info: Machine name: DESKTOP-9S0P1ER, 64-bit: True, User: user OS: Windows10 (10.0.19044)

Using Module operations
        Flushing module destination directory 'C:\temp\ir\liveresponse'
        Creating module destination directory 'C:\temp\ir\liveresponse'
                Found processor 'Executable: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe, Cmd line: -Command "& '%kapedirectory%\Modules\bin\CrowdResponse\CrowdResponse.exe' -i %kapedirectory%\Modules\bin\CrowdResponse\config.txt -o %destinationDirectory%\CrowdResponse.xml;&'%kapedirectory%\Modules\bin\CrowdResponse\CRConvert.exe' -v -c -f %destinationDirectory%\CrowdResponse.xml -o %destinationDirectory%;Remove-Item '%destinationDirectory%\CrowdResponse.xml'", Export: csv, Append: False'!
Discovered 1 processor to run.
Executing modules with file masks...
Executing remaining modules...
        Running 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe': -Command "& 'C:\tools\ir\kape\Modules\bin\CrowdResponse\CrowdResponse.exe' -i C:\tools\ir\kape\Modules\bin\CrowdResponse\config.txt -o C:\temp\ir\liveresponse\LiveResponse\CrowdResponse.xml;&'C:\tools\ir\kape\Modules\bin\CrowdResponse\CRConvert.exe' -v -c -f C:\temp\ir\liveresponse\LiveResponse\CrowdResponse.xml -o C:\temp\ir\liveresponse\LiveResponse;Remove-Item 'C:\temp\ir\liveresponse\LiveResponse\CrowdResponse.xml'"
                *** PSList: Warning: No details for PID 92. Possibly protected process.
                *** PSList: Warning: No details for PID 316. Possibly protected process.
                *** PSList: Warning: No details for PID 436. Possibly protected process.
                *** PSList: Warning: No details for PID 508. Possibly protected process.
                *** PSList: Warning: No details for PID 524. Possibly protected process.
                *** PSList: Warning: No details for PID 660. Possibly protected process.
                *** PSList: Warning: No details for PID 1808. Possibly protected process.
                *** PSList: Warning: No details for PID 3008. Possibly protected process.
                *** PSList: Warning: No details for PID 6856. Possibly protected process.
                *** PSList: Warning: No details for PID 4784. Possibly protected process.
                *** PSList: Warning: No details for PID 7372. Possibly protected process.
                *** PSList: Warning: No details for PID 4024. Possibly protected process.
                *** PSList: Warning: No details for PID 4640. Possibly protected process.
                *** PSList: Warning: No details for PID 2628. Possibly protected process.
                *** Prefetch: Error: File does not contain prefetch signature
		...
		...
                *** Prefetch: Error: File does not contain prefetch signature
                File:    1
                  "C:\temp\ir\liveresponse\LiveResponse\CrowdResponse.xml"
                  Size: 10276311 bytes
                  Loaded successfully
Executed 1 processor in 190.5082 seconds

at least it runs, but maybe are some more errors to work
