### ISSUE TITLE
Opera.tkape - quotes

### ISSUE THREAD

**Issue by yarox24** [EricZimmerman/KapeFiles#608]
**KAPE version**

Any

**Describe the bug**

In following plugin /Targets/Browsers/Opera.tkape quotes used in Comment for: Opera - Roaming Folder are non-standard ones. I'm not sure if this affects functionality of Kape.

**To Reproduce**

N/A

**Expected behavior**

N/A

**Screenshots**

N/A

**Additional context**

N/A

**Comment by AndrewRathbun** [comment]
https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Browsers/Opera.tkape#L18

This? I'm not seeing anything wrong here but I've also been awake for about 2 minutes. The comment field is just that: comments. It'll have no bearing on the functionality of the Target. If there's YAML issues then KAPE will let you know. 

Does that help?

**Comment by yarox24** [comment]
So describing the full story. 

Hexdump
![issue](https://user-images.githubusercontent.com/18016218/153621050-d017d5fa-cc72-419a-8017-648b998e8432.jpg)


I suspect that this quote error is affecting plugin generation in another project: https://github.com/Velocidex/velociraptor

This is the error (This single line is not in valid CSV format):
https://github.com/Velocidex/velociraptor/blob/4bb660155c46e8d788298aaab14b3858aa15171f/artifacts/definitions/Windows/KapeFiles/Targets.yaml#L1099

This Targets.yaml file is generated by this script based on .tkapes files from this repository:
https://github.com/Velocidex/velociraptor/blob/6bdbf0945906f224550ee382c5059ec34ec89042/scripts/kape_files.py

So I got 2 options:
- Create issue in Velociraptor project to fix the script
- Crete issue here at potential "source" of the problem [Which I choosen]

**Comment by AndrewRathbun** [comment]
https://github.com/EricZimmerman/KapeFiles/commit/10b8e33429e58fa9bf067bfccfdeac7d75f6acf7
