### ISSUE TITLE
Error in Target display

### ISSUE THREAD

**Issue by dondaniel2890** [EricZimmerman/KapeFiles#614]
KAPE version - 1.1.0.1

After adding the Target source, I am not able to view the targets. Please refer to the screenshot. Kindly help me out.

![KAPE Error](https://user-images.githubusercontent.com/100094682/154863000-394b5320-db42-4b53-8815-88764ddf261d.jpg)

**Comment by AndrewRathbun** [comment]
Have you tried closing gkape and then reopening? That often solves that issue for me.

**Comment by dondaniel2890** [comment]
I tried that, I even changed to location of gkape folder.

**Comment by EricZimmerman** [comment]
Looks like a resolution issue to me. Can you make your resolution bigger that usually fixes it?

**Comment by dondaniel2890** [comment]
Ah i tried adjusting the resolution before but didn't work. Now, I adjusted the scale and it worked. Thanks!

**Comment by EricZimmerman** [comment]
ah ok this is good to know! so you have a 4k monitor or something? what was your scaling set to? i will look into seeing what i can do to prevent scaling in gkape to prevent this.

@AndrewRathbun this might be good for KapeDocs FAQ section

**Comment by dondaniel2890** [comment]
my previous resolution was 1920x1080 and scaling was set to 150% (which is the recommended normal view). now, i just adjusted the scaling to 125%, which has made all fonts and icons small (which is a pain to use) but i really want kape to work so am ok with it. Of course, it would be really helpful if you could do something regarding this.

**Comment by AndrewRathbun** [comment]
> ah ok this is good to know! so you have a 4k monitor or something? what was your scaling set to? i will look into seeing what i can do to prevent scaling in gkape to prevent this.
> 
> @AndrewRathbun this might be good for KapeDocs FAQ section

https://github.com/EricZimmerman/KapeDocs/pull/20

**Comment by dondaniel2890** [comment]
I have an HDR one and the scaling was set to 150%. Now, after reducing it to 125% I am able to view the targets but not completely. And if I reduce the scaling a bit more to 100% I get the proper view of gkape. But, keeping the scale to 100% with 1920x1080 resolution makes the fonts and icons look very tiny which becomes hard for any user to read.

**Comment by dondaniel2890** [comment]
This is how it looks when scaling is set to 125%

![125](https://user-images.githubusercontent.com/100094682/154866187-0e36cb51-533a-4805-8d75-f8b5f788b7db.jpg)

This is how it looks when scaling is set to 100%

![100](https://user-images.githubusercontent.com/100094682/154866196-b4b82000-6182-4575-ad16-05e3d6e8fab2.jpg)

**Comment by AndrewRathbun** [comment]
Closing this issue. Feel free to reopen if anything more comes of this.
