### ISSUE TITLE
Impossible to create a new directory via SFTP options with --scd

### ISSUE THREAD

**Issue by xalicex** [EricZimmerman/KapeFiles#618]
**KAPE version**

1.1.0.1

**Describe the bug**

The documentation says "SFTP default directory to upload to. **Will be created if it does not exist**. Default is root directory".

My upload directory on server side is called "in" and is at the root. When I do "--scd in", it works fine all the files are pushed correctly in the "in" directory.

I tried to push the files to an unexisting directory inside "in" to sort my results in folders by computer name. So I tried "--scd in/MyComputerName"

I'm getting this error : 

```
Using Target operations
Validating connectivity to '66.66.66.66'...
Connected to '66.66.66.66'! Checking permissions...
'in/MyComputerName' does not exist! Creating...
         Unable to create SFTP directory 'in/P107501S269568T': Failure; Failure.
         Changing to directory 'in/P107501S269568T'...
Error validating SFTP server! Exiting!! Error: No such file; No such directory.
```

However, if I connect via an sftp client, I am able to create the MyComputerName directory in the directory "in". So it seems that the problem is not the server configuration but Kape :/

**Comment by EricZimmerman** [comment]
can you give me a test set of creds to connect to and try this? there is a difference between manually creating a dir in a dir vs having dir/another/something/else created.

KAPE has a build in sftp server you can try as well to see if it works the same, so we know if its a kape bug vs the sftp server being used in this instance.

https://ericzimmerman.github.io/KapeDocs/#!Pages\6.-SFTP.md

**Comment by EricZimmerman** [comment]
but you are running kape from a windows box, so use kape to stand up an sftp server to test against, so we can see if its ALL sftp servers, or just yours.

**Comment by xalicex** [comment]
Ok so I've just test with the Kape sftp server on another machine.

It works. But.

If I put this configuration :

```
Port: 22
HomeDirectory: C:\Users\A_User\Documents\Work\Forensic\sftp\toto
LogDirectory: C:\Users\A_User\Documents\Work\Forensic\sftp\Logs
LogLevel: Verbose
Users:
    -
        UserName: ericUDL
        Password: wizzo123!
        Access: Upload|Download|List
        Jail: true
```

And I launch in a bat

`kape.exe --debug --tsource C: --tdest "%UserProfile%\Desktop\raw_%computername%" --tflush --target $MFT --scs AN_IP --scp 22 --scu ericUDL --scpw %passwd% --scd in/%computername% --zip Kapeoutput --zpw %zippasswd% --mdest "%UserProfile%\Desktop\module_%computername%" --zm true --mflush --module MFTECmd_$MFT --mef csv`

It will create a directory "ericUDL" in toto (which is the root directory) and then within a directory "in" and finally directory with the computername.

so "C:\Users\A_User\Documents\Work\Forensic\sftp\toto\ericUDL\in\ComputerName"

and not "C:\Users\A_User\Documents\Work\Forensic\sftp\toto\in\ComputerName"

The problem is that with chroot in linux you cannot write in the root folder. Maybe the issue is this ? It tries to create a new directory at the root ? 

(In this case it's like in my linux server. the "in" directory already exist".

**Comment by EricZimmerman** [comment]
could be, i mean, it has no way to know where "home" is other than what the server presents, so it tries to create each directory you specify if it does not exist.

you jailed the user in your example above with kape. set jail to false and it should make toto\in\ and so on

**Comment by xalicex** [comment]
I just tried with jail at false.

If the "in" directory already exist within toto:

```
Using Target operations
Validating connectivity to 'IP'...
Connected to 'IP'! Checking permissions...
'in/ComputerName' does not exist! Creating...
Unable to create SFTP directory 'in/ComputerName': File already exists; Already exists.
Changing to directory 'in/ComputerName'...
Error validating SFTP server! Exiting!! Error: No such file; No such directory.
```

If the "in" directory doesn't exit within toto:

```
Using Target operations
Validating connectivity to 'IP'...
Connected to 'IP'! Checking permissions...
'in/vComputerName' does not exist! Creating...
Changing to directory 'in/ComputerName'...
Created test file OK!
```

**Comment by EricZimmerman** [comment]
ok that helps. looks like on validation at least, i need to check each dir in turn and create only missing.

**Comment by xalicex** [comment]
Yes and if we want to put the results of all machines in a dedicated directory like "output" and sorted by machines like"

output/machineA
output/machineB
output/machineC
output/machineD

It will fail because output already exists :/ And in CHROOT sftp env in linux you cannot create directory at root so just putting --scd %computername% is not an option :/

Do you think it's possible to patch this issue ? 

By the way thanks for Kape and all your awesome tools !

**Comment by EricZimmerman** [comment]
sure ill fix it asap.

**Comment by EricZimmerman** [comment]
ok, grab this and test it.

[kape.zip](https://github.com/EricZimmerman/KapeFiles/files/8216654/kape.zip)

i added a check to see if each segment of the path exists already, and if it does, skip it. 

if it works, ill release 1.2.0.0 officially. this is just a test build

**Comment by xalicex** [comment]
Thanks !

It works perfectly !

**Comment by EricZimmerman** [comment]
Ok great. 1.2.0.0 will be out later today

**Comment by xalicex** [comment]
Thank you !

**Comment by EricZimmerman** [comment]
1.2.0.0 is live

**Comment by xalicex** [comment]
Thank you again !!! And thanks for your work !
