### ISSUE TITLE
Missing download links for SUM-Repair.ps1 and SRUM-Repair.ps1

### ISSUE THREAD

**Issue by Qazeer** [EricZimmerman/KapeFiles#633]
**KAPE version**
1.2.0.0

The download links for the `SUM-Repair.ps1` and `SRUM-Repair.ps1` scripts are missing in the `PowerShell_SumECmd_SUM-RepairAndParse.mkape` and `PowerShell_SrumECmd_SRUM-RepairAndParse.mkape` modules. If I am not mistaken, the scripts are not publicly released.

If needs be, I can implement the scripts to follow the documentation of the modules ("copy of the SUM / SRUM DB with PowerShell, repair with esentutl.exe, and extract SUM data with SumECmd / SrumECmd").

**Comment by AndrewRathbun** [comment]
They're on my to-do list. They already exist but just gotta refactor them for KAPE. I'll try to do it this week!

**Comment by AndrewRathbun** [comment]
https://github.com/EricZimmerman/KapeFiles/commit/574d3a8c678d21ce8d14ca788fef500a2b63f416
https://github.com/EricZimmerman/KapeFiles/commit/665f233fccc2022a337580d9b8f562d8a9eb35b7

This is resolved. Thank you for bringing this up!
