### ISSUE TITLE
Additional KAPE variable for unique output filenames

### ISSUE THREAD

**Issue by Qazeer** [EricZimmerman/KapeFiles#638]
**KAPE version**

1.2.0.0

**Is your feature request related to a problem? Please describe.**

Some tools only allow for the specification of an output filename, overriding previous data if multiple executions are triggered.

For example, Nirsoft `usbdeview.exe` utility may retrieve data from the `SYSTEM` and `RegBack\SYSTEM` registry hives, but the second execution overrides the data from the previous one:

![image](https://user-images.githubusercontent.com/5614972/164978456-fed9aa0a-6419-4640-9243-ea9d0c07c146.png)

**Describe the solution you'd like**

A way to add uniqueness to output filename for tools that do not natively support this would be nice. A `%timestamp%` variable, replaced at runtime by the execution timestamp, would allow third-party tools to match the behavior of Eric Zimmerman's tools.

**Describe alternatives you've considered**

Instead of a `%timestamp%` variable, a variable that would convert the `%sourceFile%` path to a (Windows) valid filename would also allow for unique outputs. For example by converting `X:\Windows\System32\config\SYSTEM` to `X_Windows_System32_config_SYSTEM`.

**Comment by EricZimmerman** [comment]
what if the path is crazy long? that would break things. would something like %guid% work to add a random guid to the output filename, guaranteeing uniqueness? heck, even a new random #s between 0 and 10000 work.

**Comment by Qazeer** [comment]
Indeed anything that would make the filename unique would work (prefered solution mentioned timestamps, but a `GUID` or a random number would be fine as well)

**Comment by Beercow** [comment]
+1 on this. Running into the same issue.

**Comment by EricZimmerman** [comment]
the real solution here is for other tools to not blindly overwrite things, but alas, we cant control those.

im thinking something like this since %d% already exists, for timestamp.

```
        CommandLine: -f %sourceFile% --csv %destinationDirectory%\%sourceDirectoryBase% --csvf foo_%d%.csv
```


ends up working like this:

![image](https://user-images.githubusercontent.com/4265254/208735714-2e311ba6-5fd7-4819-95f2-f3dd3d2f15b6.png)


i also added %guid%, so this works:

![image](https://user-images.githubusercontent.com/4265254/208736465-6f95badc-5c31-4b7c-a5fa-c57426d173b0.png)

**Comment by EricZimmerman** [comment]
this will be in 1.3
