### ISSUE TITLE
Password Protect Collected Target

### ISSUE THREAD

**Issue by antmar904** [EricZimmerman/KapeFiles#639]
Hi

I collect artifacts on remote systems and would like to know if it would be possible to add the option to enter a password in order to password protect the "ZIP" folder KAPE creates after it's target collection?

Thanks again for the great work!

**Comment by EricZimmerman** [comment]
https://ericzimmerman.github.io/KapeDocs/#!Pages\3.-Using-KAPE.md#zpw

It's been in kape forever.

**Comment by antmar904** [comment]
Ah sorry, I should have checked out the documentation before.  I did not see the opting in gkape so I assumed it was not available.  Face palm.

**Comment by EricZimmerman** [comment]
It's in gkape too

Lower right

**Comment by antmar904** [comment]
OMG.  Thanks.  Again I assumed that was for the "Module" section...
