### ISSUE TITLE
SysInternals_Autoruns module: bug when there is a space in the destination path

### ISSUE THREAD

**Issue by andersnese** [EricZimmerman/KapeFiles#644]
**KAPE version**

KAPE version 1.2.0.0

**Describe the bug**

If there is a space in the mdest variable, like in the example below, the SysInternals_Autoruns will not produce correct output. 

**To Reproduce**

.\kape.exe --msource c:\ --mdest "C:\Output Folder\Test%d" --mflush --module SysInternals_Autoruns --gui

**Comment by EricZimmerman** [comment]
Looks like you fixed it in your PR. I'll close this until we get a chance to pull that in
