### ISSUE TITLE
STDOUT

### ISSUE THREAD

**Issue by Epod** [EricZimmerman/KapeFiles#647]
Greetings, 

When writing a CommandLine, I am running into issues with tools that only log to STDOUT. Normally to write this data to a file, I would just > at the end of the command - however with KAPE any attempt to write the output in this way returns a syntax error. 

Specifically, programs will return messages like "invalid arguments" which is odd because the same command works manually. 

I am curious of there are examples of redirecting STDOUT with KAPE?

**Comment by AndrewRathbun** [comment]
@Epod I have to imagine you found the documentation for ExportFile here: https://ericzimmerman.github.io/KapeDocs/#!Pages\2.2-Modules.md#ExportFile, right? I just want to make sure the solution is posted here for others to benefit from later on.
