### ISSUE TITLE
Space in mvars value

### ISSUE THREAD

**Issue by andersnese** [EricZimmerman/KapeFiles#649]
1.2.0.0
The version of KAPE you are currently using

**Is your feature request related to a problem? Please describe.**
I want to create a new module for running Thor and ThorLite on remote systems, where a module variable spesifies which options thor* should run with. 

For instance, `--mvar thorScanOptions:'--quick --json'` 

The problem is with the space in the mvar value. I found this issue to be related: https://github.com/EricZimmerman/KapeFiles/issues/104. However, the fix in this issue was to find a way to avoid using a space in the value. In this case I do not think that is an option. 

**Describe the solution you'd like**
A more robust handling of mvars such that it is possible to provide mvars is space in the value.

**Comment by EricZimmerman** [comment]
Did you solve this? What 2as it? Why not just have different modules for different options? Then it's more clear when calling things anyways

**Comment by andersnese** [comment]
It was solved by fixing the quotes: ` --mvars thorScanOptions:"$ThorScanOptions"`

CommandLine in Module: `CommandLine: "%thorScanOptions% -e %destinationDirectory%\\THOR"`

The reason for supplying the command line arguments via a module variable rather than creating additional Thor LiveResponse modules is to support custom Thor scans (depending on context) without making changes to the KAPE package. 

A use case for this could for instance be if you run KAPE via a wrapper powershell script using an EDR. The setup could then be to push kape.zip and Invoke-Kape.ps1 to the EDR library. During IR you can then ask the EDR to fetch kape.zip and Invoke-Kape.ps1, then run Invoke-Kape.ps1 with some paramters. The Thor command line arguments would then be part of the parameters passed to Invoke-Kape.ps1. **TLDR; this setup would not require you to upload a new version of kape.zip if you want to run Thor with custom command line args.**
