### ISSUE TITLE
Add MaxAge option to Target Specification

### ISSUE THREAD

**Issue by hkelley** [EricZimmerman/KapeFiles#665]
**KAPE version**
v1.2.0.0

**Is your feature request related to a problem? Please describe.**
I would like to include folders like these in my target, but only return files most likely to be of interest in an investigation (those written within the past _n_ (7?) days.
```
        Path: C:\Users\%user%\Downloads\
        Path: C:\Users\%user%\AppData\Local\Microsoft\Windows\INetCache\Content.Outlook
```

**Describe the solution you'd like**
Add a target specifier like the following MaxAge (days old)

```
    -
        Name: User Files - Outlook attachments
        Category: LiveUserFiles
        Path: C:\Users\%user%\AppData\Local\Microsoft\Windows\INetCache\Content.Outlook
        Recursive: true
        MaxAge:  7
```

**Describe alternatives you've considered**
Including the entire folder contents in the collection,  which can be quite bulky.

**Comment by AndrewRathbun** [comment]
I'm not discounting the usefulness of this requested feature, as it would be awesome in a vacuum, but one thing to consider is that in an IR context, or even potentially in an LE context, timestomping could be involved. Therefore, files of interest that appeared within the last 7 days on the target disk could be timestomped back to 2015, for example, and then you'd be missing out on grabbing those files with this approach. Just something to consider given that timstomping is trivial to accomplish. 

Regardless, proper analysis of the $MFT, $J, and various other artifacts should be conducted in those scenarios so you ensure you're not missing potentially important evidence, but that's sort of going out of the scope of this Issue :)

**Comment by hkelley** [comment]
That's an excellent point.   You've convinced me that this is better handled on the module side using the $* data to build a list of files, then manually fetching those using other tools.

**Comment by hkelley** [comment]
Correct, no further action here.
