### ISSUE TITLE
KAPE Variable expansion issues

### ISSUE THREAD

**Issue by mcvic1rj** [EricZimmerman/KapeFiles#669]
**KAPE version**
V1.2.0.0

**Describe the bug**

Using a KAPE Variable as the first item in the module output can lead to "double paths" one is the current KAPE Directory (put in when a fully qualified path is not specified) and the other piece is the variable being expanded.
 
**To Reproduce**

1. Run KAPE from the Module source disk and use the Magnet Ram Capture module
2. set output directory and module source
    Example CLI: `--msource c: --mdest %kapeDirectory%\caps\temp --mflush --module MagnetForensics_RAMCapture --gui`
3. Observe Commandline MRC is run with:
    `Running 'MRC.exe': /accepteula /go E:\KAPE\E:\KAPE\caps\temp\Memory\memory.raw /silent`

**Expected behavior**

The ability to use kape/module variables in the Module Output path/When resolving `%destinationDirectory%`. 

**Screenshots**
<img width="905" alt="image" src="https://user-images.githubusercontent.com/10363041/179406070-4c8b394c-953e-4727-bd13-98d242c53783.png">

**Additional context**

This also will happen when using `--mvars`
`Command line: --msource c: --mdest %kapesrc%\caps\temp --mflush --module MagnetForensics_RAMCapture --gui --mvars kapesrc:e:\KAPE`

`Running 'MRC.exe': /accepteula /go E:\KAPE\e:\KAPE\caps\temp\Memory\memory.raw /silent`

**Comment by EricZimmerman** [comment]
eh, why WOULDNT . be the KAPE directory?

its in the online docs too.

**Comment by EricZimmerman** [comment]
you dont need to use mvars for built in variables either

**Comment by EricZimmerman** [comment]
I'm going in and verifying / tweaking some things, and I see why the Cape
directory was specified twice when you use it how you were using it so
that'll be fixed going forward.

The bigger issue is not having quotes around the entire output path and I'm
also in there fixing that issue as well

**Comment by EricZimmerman** [comment]
closing this and reopening other issue
