### ISSUE TITLE
Suggestions Needed:  Azure transfer to fixed IP?

### ISSUE THREAD

**Issue by hkelley** [EricZimmerman/KapeFiles#672]
We are trying to configure our KAPE file collection so that we can:

1. Isolate/contain a host so that it only communicates with limited IPs (breaking DNS resolution)
2. Collect files in an Azure storage account by setting KAPE's -asu (Azure Storage SAS Uri) parameter

The fixed IP (requirement 1)  is at odds with the Azure URI scheme so we have considered, but not yet tested, using an Azure Application Gateway in front of the storage account.  

Has anyone else accomplished something similar?

**Comment by EricZimmerman** [comment]
cant you use azure to limit what SOURCE ip is allowed to talk to the sas uri?

**Comment by hkelley** [comment]
Moved to Discussion #675.  Sorry about the faux pas.
