### ISSUE TITLE
Need to update BinaryUrl for RECMD across the board in all modules 

### ISSUE THREAD

**Issue by mgdevsoft** [EricZimmerman/KapeFiles#687]
Kape 1.2.0.0

In all the related Modules that refer to RECmdtool and contains BinaryUrl, the URL refer to a file that does not exist (404 response code) 
404 response code: https://f001.backblazeb2.com/file/EricZimmermanTools/RegistryExplorer_RECmd.zip
200 OK : https://f001.backblazeb2.com/file/EricZimmermanTools/RECmd.zip

The same for EvtxECmd:
current BinaryUrl: https://f001.backblazeb2.com/file/EricZimmermanTools/EvtxExplorer.zip (404 not found)
working URL: https://f001.backblazeb2.com/file/EricZimmermanTools/EvtxECmd.zip (200 OK)

Kind Regards,
Gal Miller

**Comment by AndrewRathbun** [comment]
Done, thanks for bringing it up!
