### ISSUE TITLE
bstring BinaryURL does not refer to the binary only to the project in github

### ISSUE THREAD

**Issue by mgdevsoft** [EricZimmerman/KapeFiles#689]
KAPE version 1.2.0.0
For automation purposes the direct executable URL needed to be supplied.
current BinaryURL : https://github.com/EricZimmerman/bstrings
needed: https://f001.backblazeb2.com/file/EricZimmermanTools/bstrings.zip

**Comment by AndrewRathbun** [comment]
Did you want to try to do a PR and correct it? Or do you want me to do it?

**Comment by mgdevsoft** [comment]
You can correct it.

 I am working on a script to also update all the tools in kape including
those that have releases.  Between IR cases.

 I am writing it as generic as possible.

 So, when new tools will be added it will automatically support the updates.

Kind regards,
Gal

**Comment by AndrewRathbun** [comment]
Good deal. Feel free to fork https://github.com/AndrewRathbun/KAPE-EZToolsAncillaryUpdater and see if that'll give you a nice running start.

**Comment by mgdevsoft** [comment]
Thanks!
