### ISSUE TITLE
Chrome. target typo

### ISSUE THREAD

**Issue by pechom** [EricZimmerman/KapeFiles#717]
**KAPE version**
1.2.0.0

**Describe the bug**
Chrome.tkape at line 102 is "        FileMask: Download Metadata" but there should not be a space in the file name. The file is "DownloadMetadata"

**To Reproduce**
1. Go to https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Browsers/Chrome.tkape line 102

**Expected behavior**
line should be "        FileMask: DownloadMetadata"

**Comment by AndrewRathbun** [comment]
Did you want to try to do a PR? Or did you want me to fix it?

**Comment by AndrewRathbun** [comment]
https://github.com/EricZimmerman/KapeFiles/commit/e83d02a35d7181a986122be28d590c4423174338

This is fixed
