### ISSUE TITLE
SFTP exception 

### ISSUE THREAD

**Issue by nemesislvlup** [EricZimmerman/KapeFiles#736]
**KAPE version**

1.3.0.1

**Describe the bug**

I'm using a lazagne (pw collection) module with exfil to SFTP, which worked fine on 1.2.0.0, but I'm getting the following output on 1.3.0.1:

**_kape.cli**:

> .\kape.exe --msource "." --mdest ".\Process\%m\C" --mflush --zm true --module Lazagne --scs XXXXXXX --scp 22987 --scu kape --scpw XXXXXXX --scc RCCU_Triage

**ConsoleLog:**
> [2023-01-03 15:41:27.2549185 | INF] SFTPing module output to XXXXXXX
> [2023-01-03 15:41:27.5521756 | FTL] Value cannot be null.
> Parameter name: paths:    at Alphaleonis.Win32.Filesystem.Path.CombineCore(Boolean checkInvalidPathChars, String[] paths) in C:\Users\jjangli\Documents\GitHub\AlphaFS\AlphaFS\Filesystem\Path Class\Path.Combine.cs:regel 65
>    at kape.Program.Main(String[] args)
> System.ArgumentNullException: Value cannot be null.
> Parameter name: paths
>    at Alphaleonis.Win32.Filesystem.Path.CombineCore(Boolean checkInvalidPathChars, String[] paths) in C:\Users\jjangli\Documents\GitHub\AlphaFS\AlphaFS\Filesystem\Path Class\Path.Combine.cs:regel 65
>    at kape.Program.Main(String[] args)

Adding --debug doesn't give more information about the exception. 

**To Reproduce**

Use the command and setup your SFTP server. I'm using my own SFTP server which has worked all the time. The write_test works fine and that file shows up in my SFTP logs.

**Comment by nemesislvlup** [comment]
Output of 1.2.0.0:

`2023-01-03 16:09:29.2736 | I | SFTPing module output to 'XXXXXXX'
2023-01-03 16:09:30.0103 | W | 	Starting transfer of '2023-01-03T150837_ModulesOutput.zip'
2023-01-03 16:09:30.1410 | W | 		Transfer for '2023-01-03T150837_ModulesOutput.zip' complete!
2023-01-03 16:09:30.1639 | W | 	Starting transfer of '2023-01-03T150837_ConsoleLog_SFTP.txt'
2023-01-03 16:09:30.2436 | W | 		Transfer for '2023-01-03T150837_ConsoleLog_SFTP.txt' complete!
2023-01-03 16:09:30.2436 | F | Total execution time: 52,2499 seconds
`

**Comment by EricZimmerman** [comment]
if you use the stock sftp config from the KAPEDOCS site, can you replicate this?

have you tried adding --trace?

**Comment by nemesislvlup** [comment]
Hi Eric, 

I'm not using the SFTP-server function of KAPE, only the switches in the command to upload the result to my own SFTP server. Version 1.2.0.0 with exactly the same commands works perfectly whereas version 1.3.0.1 errors out. So I believe it's due to a change between those two versions. 

--trace adds a lot of output, but nothing to the final lines where it shows the Exception.

**Comment by EricZimmerman** [comment]
sure i understand, but if 1.2 works with my KAPE SFTP, but 1.3 does not, it makes it easier for me to debug locally.

**Comment by nemesislvlup** [comment]
1.3.0.1 also doesn't work with your SFTP server. 

**ConsoleLog 1.3.0.1:**

> [2023-01-03 16:44:23.0188524 | INF] KAPE directory: E:\KAPE
> [2023-01-03 16:44:23.0258516 | INF] Command line:   .\kape.exe --msource . --mdest .\Process\C --mflush --zm true --module Lazagne --scs 127.0.0.1 --scp 22 --scu test --scpw XXXXXXXXX --scc Test 
> [2023-01-03 16:44:23.0258516 | INF] System info: Machine name: DELLBJORN, 64-bit: true, User: Bjorn OS: "Windows10" (10.0.19044)
> [2023-01-03 16:44:23.5958724 | INF] Using Module operations
> [2023-01-03 16:44:23.6018714 | INF]   Validating connectivity to 127.0.0.1...
> [2023-01-03 16:44:23.9938791 | WRN]   Unable to delete test file from 127.0.0.1
> [2023-01-03 16:44:23.9998801 | WRN]   Flushing module destination directory E:\KAPE\Process\C
> [2023-01-03 16:44:24.0058792 | WRN]   Creating module destination directory E:\KAPE\Process\C
> [2023-01-03 16:44:24.0118801 | INF]     Found processor Executable: laZagne.exe, Cmd line: all -oN  -output %destinationDirectory%, Export: csv, Append: False!
> [2023-01-03 16:44:24.0128798 | INF] Discovered 1 processor to run
> [2023-01-03 16:44:24.0138799 | INF] Executing modules with file masks...
> [2023-01-03 16:44:24.0138799 | INF] Executing remaining modules...
> [2023-01-03 16:44:24.0158790 | INF]   Running laZagne.exe: all -oN  -output E:\KAPE\Process\C\LiveResponse
> [2023-01-03 16:45:13.6223450 | INF] Executed 1 processor in 49.6141 seconds
> [2023-01-03 16:45:13.6233439 | WRN] Compressing directories in E:\KAPE\Process\C to E:\KAPE\Process\C\2023-01-03T154422_ModulesOutput.zip...
> [2023-01-03 16:45:13.7693460 | INF] Done. Compressed size: 2,9KB
> [2023-01-03 16:45:13.7703447 | INF] SFTPing module output to 127.0.0.1
> [2023-01-03 16:45:14.0683451 | FTL] Waarde kan niet null zijn.
> Parameternaam: paths:    bij Alphaleonis.Win32.Filesystem.Path.CombineCore(Boolean checkInvalidPathChars, String[] paths) in C:\Users\jjangli\Documents\GitHub\AlphaFS\AlphaFS\Filesystem\Path Class\Path.Combine.cs:regel 65
>    bij kape.Program.Main(String[] args)
> System.ArgumentNullException: Waarde kan niet null zijn.
> Parameternaam: paths
>    bij Alphaleonis.Win32.Filesystem.Path.CombineCore(Boolean checkInvalidPathChars, String[] paths) in C:\Users\jjangli\Documents\GitHub\AlphaFS\AlphaFS\Filesystem\Path Class\Path.Combine.cs:regel 65
>    bij kape.Program.Main(String[] args)

Output SFTP server KAPE:

![image](https://user-images.githubusercontent.com/63041852/210391611-3fa31ee5-20b9-4846-b6da-74ee9565b11d.png)

**Comment by EricZimmerman** [comment]
i see the issue. when using module options only, one of the paths for the log file ends up being null.

will have 1.3.0.2 out here soon

**Comment by EricZimmerman** [comment]
released. please update and try it

**Comment by nemesislvlup** [comment]
Works flawlessly. Thanks for the fast fix.

**Comment by EricZimmerman** [comment]
Sweet
