### ISSUE TITLE
Validating connectivity to Azure Storage - Error validating Azure Storage information

### ISSUE THREAD

**Issue by hkelley** [EricZimmerman/KapeFiles#760]
**KAPE version**

KAPE version 1.3.0.2

**Describe the bug**

I am testing the Azure storage feature.  At the end of the command, I get this error,

  Validating connectivity to Azure Storage
Error validating Azure Storage information! Exiting!! Error: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

**To Reproduce**

1. Created new blob container in my Azure storage account.
2. Created a SAS token in the container with "racwdl"

`https://xxx.blob.core.windows.net/kape-uploads?sp=racwdl& `

3. Run the following:
`.\kape.exe --trace  --debug --target  ScheduledTasks --tsource C: --tdest c:\temp\_kape_scratch --vhdx c:\temp\_kape_scratch  --asu  XXXX`

4. Message above is reported.

**Expected behavior**

Upload to Azure container

**Screenshots**

**Additional context**

I haven't used this feature before so operator error is likely.  I've read the docs and don't see what I'm missing

**Comment by EricZimmerman** [comment]
Well, I can tell you you're at least using the VHDX switch incorrectly. It doesn't expect a path but just a base name

So I would clean those things up and look at some of the other example documentation. But I've not heard anybody having any issues with creating an azure SAS URL and using it effectively

**Comment by hkelley** [comment]
Thanks for the tip about the VHDX.   

I just tested my SAS token with Set-AzStorageBlobContent  and I get the same message so I'll test further there before I retry KAPE.   Apologies for the spam.

**Comment by hkelley** [comment]
Root cause:  I was not paying attention to the encoding in my SAS URI.   A percent sign in the signature was being interpreted as a variable in my Windows batch script.

**Comment by EricZimmerman** [comment]
glad you found it! =)
