### ISSUE TITLE
Variable %sourceDirectoryBase% Is Not Expanded

### ISSUE THREAD

**Issue by dsplice** [EricZimmerman/KapeFiles#763]
**KAPE version**

1.3.0.2

**Describe the bug**

%sourceDirectoryBase% is not being expanded prior to running a program within a module. 

**Expected behavior**

%sourceDirectoryBase% will be translated to the correct source directory

**Screenshots**

![2023-02-16 11 01 27](https://user-images.githubusercontent.com/1919754/219449821-40c33b8d-c9ca-4309-9b03-af0b21b7696a.png)

**Comment by Karneades** [comment]
Hi @dsplice 

I guess you adopted https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/Apps/GitHub/INDXRipper.mkape into `INDXRipper-da`. According to [KAPE documentation](https://ericzimmerman.github.io/KapeDocs/#!Pages\2.2-Modules.md) the `%sourceDirectoryBase%` is used `for Modules that use FileMask, 'base' directory under --tdest. Examples: C, VSS1, VSS2, etc. Useful to group output by where the files were found`.

Do you have set FileMask? How are you using / invoking the module?

If the error's still there, then if possible, share your module. The existing module in the repo doesn't use base but sourceDriveLetter.

Best
Andreas

**Comment by dsplice** [comment]
The use case I had originally envisioned does not make any sense since there is no way to use a target to copy all Index files.  The issue was raised because it was noticed during troubleshooting.  No current modules use @sourceDirectoryBase%.  Yet it is listed in the online documentation as being available.  The lines with the code are below:

`Processors:
    -
        Executable: INDXRipper\INDXRipper.exe
        CommandLine: --deleted-dirs %sourceDirectoryBase% %destinationDirectory%\INDXRipper_All.csv
        ExportFormat: csv`

**Comment by Karneades** [comment]
As noted above %sourceDirectoryBase% is used _for Modules that use FileMask_, you don't have a file mask set as far as I see it in your screenshot.

Why do you want to use that variable for that module? What's wrong with the existing INDXRipper.mkape?
