### ISSUE TITLE
Running KAPE inside Docker container

### ISSUE THREAD

**Issue by francutura** [EricZimmerman/KapeFiles#778]
## KAPE version

KAPE version 1.3.0.2
System info: 64-bit: true, User: ContainerAdministrator OS: "Windows10" (10.0.17763)

## Describe the bug

When running KAPE inside a windows docker [container](https://hub.docker.com/_/microsoft-windows) the command breaks. I get the following error:

### Traceback
```
System.IO.IOException: The request is not supported.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at RawDiskLib.RawDiskStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at DiscUtils.Streams.StreamUtilities.ReadExact(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
   at DiscUtils.Ntfs.NtfsFileSystem..ctor(Stream stream)
   at RawCopy.Helper.VerifyFileSystemOpen(String path)
   at RawCopy.Helper.RawFileExists(String path)
   at kape.Classes.Copy.RawDiskLibCopy.Copy(String vssMountDirectory, Boolean deduplicate, Boolean usingContainer, TimeSpan findTime, Boolean simulateCopy)
[2023-03-14 13:45:47.8577260 | FTL] Could not copy file [redacted] to [redacted]. Error: The request is not supported.
```

Command that was run:
```
.\kape.exe --tsource C:\ --tdest xxx--vhdx xxx--target !SANS_Triage --vss
```

### Final output
```
WARNING: THERE WERE {.Count:N0} FILE COPY FAILURES! See the console log for details!!!

Copied 0 out of 467 files in 11.8057 seconds. File copy errors: 467. See console log for details! See 2023-03-17T13_08_52_0744784_CopyLog.csv in the VHD(X)/Zip located in [redacted] for copy details
Initializing VHDX creation. This may take a while...

No files were copied. Cannot create VHD(x) file!

Total execution time: 12.1556 seconds
```

### Additional Info

All the files that are being processed were contained inside the filesystem of the docker container as well as the kape executable. The output directory is inside the docker container as well. Trying to copy the files manually from the source to the destination directory, that the tool reports is unable to copy, using xcopy command is succesfull. 

## Question

Is it possible to run KAPE inside a windows server docker container?

**Comment by EricZimmerman** [comment]
No idea. Never tried it. Don't see why it wouldn't work if the file system is ntfs.

**Comment by francutura** [comment]
Thank you for the fast response!

The filesystem should be NTFS. Running the following command tells me it is NTFS
```
PS C:\> wmic volume get FileSystem
FileSystem
NTFS
```
It is a Windows 10 Enterprise LTSC 2019 docker container running on a Windows 10 Pro host.

**Comment by Karneades** [comment]
I never run KAPE inside a Windows server, but that the `RawDiskLibCopy` (as stated in the [initial KAPE blog post](https://binaryforay.blogspot.com/2019/02/introducing-kape.html) "process all deferred files using raw disk reads to get a copy of the file") gave an `The request is not supported` error, it seems that the raw disk read access fails. This would be a lib limitation inside containers.

Eric could confirm, that the lib used in KAPE is not working within a container and this is something to write explicitly like "contraints" or "known limitation" somewhere.

**Comment by francutura** [comment]
@Karneades Haven't been able to solve it. For me it is not needed anymore I found an alternative workflow. I agree with your above point I'm sure it is a limitation of containers.

**Comment by EricZimmerman** [comment]
We good to close this then? If so, please do
