### ISSUE TITLE
--zip without basename fails quietly 

### ISSUE THREAD

**Issue by ecapuano** [EricZimmerman/KapeFiles#78]
Running with `--zip` option will silently ignore the option entirely if a basename is not specified which can be hard to troubleshoot. 

Perhaps add a warning when required arguments are not provided?

**Comment by EricZimmerman** [comment]
looks like all the containers work this way. will fix all of em

**Comment by EricZimmerman** [comment]
so, cant really do this. if you do --zip or --vhdx and leave the value blank, it comes in as null, so i have no way to know if it was sent in or not.
