### ISSUE TITLE
Powrshell_LiveResponse_SystemInfo.mkape cannot find module

### ISSUE THREAD

**Issue by Beercow** [EricZimmerman/KapeFiles#783]
**KAPE version**

v1.3.0.2

**Describe the bug**

When running the Powrshell_LiveResponse_SystemInfo.mkape, it produces the error Cannot find module file PowerShell_LocalAdmin! Skipping...

This is due to PowerShell_LocalAdmin.mkape missing from the KAPE modules

**To Reproduce**

.\kape.exe --msource C: --mdest c:\temp\test --mflush --module Powrshell_LiveResponse_SystemInfo

**Expected behavior**

PowerShell_LocalAdmin.mkape to be present

**Screenshots**

![image](https://user-images.githubusercontent.com/10360919/230925630-3c58669e-ab70-4545-9fa6-aed14ba7cf04.png)

**Additional context**

PowerShell_LocalAdmin.mkape missing from the KAPE modules

**Comment by AndrewRathbun** [comment]
@piesecurity @Karneades any chance you can opine on this?

**Comment by Karneades** [comment]
Thanks @Beercow for finding this.

This module was introduced by Vito Alfano & @piesecurity in January this year (commit by @vxsh4d0w).

The corresponding line in that module is found here: 
https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/Compound/Powrshell_LiveResponse_SystemInfo.mkape#L17

The authors/uploaders should upload the currently missing module `PowerShell_LocalAdmin.mkape` or we use the existing PowerShell module https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/Windows/PowerShell_NetUserAdministrators.mkape for getting local admins in that compound.

And besides that, we should fix the typo in the module name `Powrshell_LiveResponse_SystemInfo`.

**Comment by vxsh4d0w** [comment]
My apologies. I thought I committed that module to extract local administrators. I'll do immediately and fix the issue. Sorry again for my error.

**Comment by vxsh4d0w** [comment]
@AndrewRathbun @Beercow @Karneades  I just submitted the local admin module that was unexpectedly missed. Sorry again.

**Comment by AndrewRathbun** [comment]
Thank you all!
