### ISSUE TITLE
Warning does not show number of file copy errors

### ISSUE THREAD

**Issue by Beercow** [EricZimmerman/KapeFiles#790]
**KAPE version**

1.3.0.2

**Describe the bug**

Warning message in console and logs does not show number of file copy failures

**Expected behavior**

Warning message in console and logs should show number of file copy failures

**Screenshots**

![image](https://user-images.githubusercontent.com/10360919/232640944-1e6e6d76-9839-4c34-9b72-bd8765f67b1d.png)

**Comment by AndrewRathbun** [comment]
You really are trying to break KAPE, aren't you? :) Props to you for hunting this down!

**Comment by EricZimmerman** [comment]
this is fixed for next version
