### ISSUE TITLE
Issue opening KAPE

### ISSUE THREAD

**Issue by Lerrosa** [EricZimmerman/KapeFiles#791]
Hi all,

I'm pretty new to this so I might be asking a stupid question, but I can't seem to find the .exe to open KAPE, anyone got an idea of that I should do? Thanks.

**Comment by AndrewRathbun** [comment]
@Lerrosa kape.exe is the command line executable for KAPE. gkape.exe is the graphical user interface (GUI) for KAPE. If you're looking for the GUI, open gkape.exe and start there.

![image](https://user-images.githubusercontent.com/36825567/233092897-39460230-5a9e-4cb4-984f-c7a905f031f9.png)

Let me know if you have any further issues.

**Comment by Lerrosa** [comment]
@AndrewRathbun 
Thanks for the help, I downloaded this from GitHub and this is what the unzipped files look like.
![Screenshot 2023-04-19 094123](https://user-images.githubusercontent.com/116929292/233093618-10e763ad-3e6a-4093-8682-ae83ec6d7d08.png)

**Comment by AndrewRathbun** [comment]
KAPE doesn't live on GitHub. You have to download it here: https://www.kroll.com/en/services/cyber-risk/incident-response-litigation-support/kroll-artifact-parser-extractor-kape

If you have any issues getting the download link via email, please email kape@kroll.com and we'll send you a link.

**Comment by AndrewRathbun** [comment]
Email sent, hope that helps!
