### ISSUE TITLE
GKAPE doesn't show the Targets and Modules available

### ISSUE THREAD

**Issue by rafaroedel** [EricZimmerman/KapeFiles#792]
GKAPE 1.3.0.2 (Running on Windows 11)

I can't see the Targets and Modules available to run

1. Open gkape with '.\gkape.exe' (on PowerShell with administrative rights)
2. Click on the boxes that habilitate Targets and/or Modules
3. The boxes below doesn't show the available objects and they are bad formatted.

<img width="454" alt="kape1" src="https://user-images.githubusercontent.com/132069930/235152310-cef057cb-9850-46d0-aecf-5819744c32ed.png">

I'd expect to see the targets and modules available.

* I've tried running in compatibility mode (Win 8 and Win7 - Win10 wasn't available).
* When I list the targets (--tlist) and modules(--mlist) in the CLI, the objects are shown normally.
* The CLI version works fine at all.

**Comment by EricZimmerman** [comment]
It's your monitor resolution

**Comment by rafaroedel** [comment]
Indeed! Thanks!
