### ISSUE TITLE
hayabusa_LiveResponse module error

### ISSUE THREAD

**Issue by grizzlycode** [EricZimmerman/KapeFiles#839]
**KAPE version**

1.3.0.2

**Describe the bug**

Running "hayabusa_LiveResponse" module results in an error. 

It is not clear how you specifiy the "level" as indicated in the error (at least to me). Looking at the module description it doesn't say how to apply the level(s) you require for proper execution. 

error: 
`ERR]     [0m[ERROR]  You specified an invalid level. Please specify informational, low, medium, high or critical.
`

**To Reproduce**

Execute the "hayabusa_LiveResponse" module on evtx file(s). 

**Expected behavior**

Process evtx files with chosen level(s) and output a csv file.

**Comment by AndrewRathbun** [comment]
https://github.com/EricZimmerman/KapeFiles/blob/c2e6c077ca87dc027e3c2b9a0c51ec232fd4205d/Modules/Apps/GitHub/Hayabusa/hayabusa_LiveResponse.mkape#L11C27-L11C27

I just tested this on my VM and noticed that `--live-analysis` needed to be changed to `--live_analysis`, so I can do a PR to address that.

Also, I changed `med` to `medium`, and it appeared to work. I can include that in the aforementioned PR. Thanks for flagging! I haven't used this Module before.

**Comment by grizzlycode** [comment]
Thanks for the quick response! I imagine if you wanted to do multiple levels it just a comma seperated value?  (i.e., -m medium, high, critical)

**Comment by AndrewRathbun** [comment]
> Thanks for the quick response! I imagine if you wanted to do multiple levels it just a comma seperated value? (i.e., -m medium, high, critical)

I have no idea, test it out in the Module, aka edit it in gkape and run it as a test.

![gkape_hrMos1ul7e](https://github.com/EricZimmerman/KapeFiles/assets/36825567/e8906ff2-c147-49ad-8771-126e2771882c)

I don't use the tool in a Live Response manner so I'm unfamiliar with this syntax.

**Comment by grizzlycode** [comment]
I think `--live-analysis` is the correct option. After syncing the module update I'm getting an error for `--live_analysis` so the error was probably related to the level not being spelled out? I changed the option back to former name --live-analysis and it worked this time. 

It appears you can't do a comma separated value either. I would recommend mabe a key:value pair with this module indicating levels and allowing for comma seperation. As of right now I have to edit the module description command to change the levels. That is something a user would know they have to do...I would recommend updating the description to indicate that it needs to to be manually updated based on level you want.

**Comment by grizzlycode** [comment]
Ok, so I figured out that the -m stand for minimum level. It will for instance with default "medium" report all Medium and greater alerts. I tihnk this is probably a good default for the command now that I understand it better.

**Comment by grizzlycode** [comment]
```
Usage:
  hayabusa.exe csv-timeline <INPUT> [OPTIONS]

Input:
  -d, --directory <DIR>  Directory of multiple .evtx files
  -f, --file <FILE>      File path to one .evtx file
  -l, --live_analysis    Analyze the local C:\Windows\System32\winevt\Logs folder
  -J, --JSON-input       Scan JSON formatted logs instead of .evtx (.json or .jsonl)
```

That may be it I'm using a previous version of Haybusa not 2.6. If they did change it the need to update their Github page which still shows this: 

```
Usage: csv-timeline <INPUT> [OPTIONS]

Input:
  -d, --directory <DIR>  Directory of multiple .evtx files
  -f, --file <FILE>      File path to one .evtx file
  -l, --live-analysis    Analyze the local C:\Windows\System32\winevt\Logs folder
  -J, --JSON-input       Scan JSON formatted logs instead of .evtx (.json or .jsonl)
```

**Comment by AndrewRathbun** [comment]
I'm sure that's an oversight on their part. However, it seems like for 2.7 there might be another change?

https://github.com/Yamato-Security/hayabusa/blob/851d16ddb87bf45f71a6e3139cacd5af74430099/CHANGELOG.md?plain=1#L32

https://github.com/Yamato-Security/hayabusa/issues/1139

**Comment by grizzlycode** [comment]
Yeah it appears the caught the option name error and are reverting it back to the previous name `--live-analysis`

**Comment by gs3cl** [comment]
Yea that's right there are some changes due to last version. Feel free to update otherwise I can check and fix this later :)
