### ISSUE TITLE
NirSoft FullEventLogView Loop

### ISSUE THREAD

**Issue by salty4n6** [EricZimmerman/KapeFiles#867]
**KAPE version**
1.3.0.2

**Describe the bug**
When using the module, NirSoft_FullEventLogView_AllEventLogs, there is a loop instead of just processing 1 time.

Also, the path is incorrect in the module. Missing \C

As distributed: 
Executable: FullEventLogView.exe
CommandLine: `/TimeFilter 0 /DataSource 3 /LogFolder %sourceDirectory%\Windows\System32\winevt\Logs\ /scomma %destinationDirectory%\all_event_logs.csv`
ExportFormat: csv

Should be:
CommandLine: `/TimeFilter 0 /DataSource 3 /LogFolder %sourceDirectory%\C\Windows\System32\winevt\Logs\ /scomma`

**To Reproduce**

Target Options:
Target source: C:\
Target destination: C:\Localhost
Flush: Checked
Targets: !SANS_Triage

Module options:
Module destination: C:\Localhost\NirSoft
Flush: Checked
Module: NirSoft_FullEventLogView_AllEventLogs

**Expected behavior**
Loop through all event logs 1 time and produce 1 CSV file.

**Screenshots**

![NirSoft](https://github.com/EricZimmerman/KapeFiles/assets/81833785/a7521300-aedc-4c0b-9fd4-daac23ecb176)
![NirSoft-1](https://github.com/EricZimmerman/KapeFiles/assets/81833785/5cc03324-e08f-4ddc-9256-abe7684e72b5)
![NirSoft-2](https://github.com/EricZimmerman/KapeFiles/assets/81833785/7901650e-1723-41d4-820b-4b37d5713806)
![NirSoft-3](https://github.com/EricZimmerman/KapeFiles/assets/81833785/877039ba-26e7-43d1-bdb0-1fa54ff5b7fc)

**Additional context**

You can see the output file is continually overwritten with each loop.  

When manually running the command that KAPE is running, everything works at expected, 1 pass through all event logs and 1 output file.

Thanks,
~Salty

**Comment by AndrewRathbun** [comment]
I've always thought NirSoft's tools were a nightmare when using them on the command line. I see what you mean re: the loop, but I've tested it out and it still doesn't work for me. 

`.\FullEventLogView.exe /TimeFilter 0 /DataSource 3 /LogFolder "C:\temp\fulleventlogviewTEST\tout\C\Windows\System32\winevt\logs" /scomma "C:\temp\fulleventlogviewTEST\tout\C\Windows\System32\winevt\logs\events.csv"`

I don't know what command you're running, but I can't get this tool to work. Also, is there any reason to use this tool over EvtxECmd?

**Comment by salty4n6** [comment]
I'm with you about NirSoft tools and running them via the CLI.

I'm running the following command manually to confirm the syntax is correct and the tool works as expected:
From KAPE's output:
Running FullEventLogView.exe: /TimeFilter 0 /DataSource 3 /LogFolder C:\Localhost\C\Windows\System32\winevt\Logs\ /scomma C:\Localhost\NirSoft\EventLogs\all_event_logs.csv

Manually running this (works as expected):
C:\Software\KAPE\Modules\bin\FullEventLogView.exe /TimeFilter 0 /DataSource 3 /LogFolder C:\Localhost\C\Windows\System32\winevt\Logs\ /scomma C:\Localhost\NirSoft\EventLogs\all_event_logs.csv

I do run EvtxECmd, but I'm also running other tools as a means of trust but verify.  I don't put all my trust in 1 tool. 

Thanks for looking at it.

~Salty

**Comment by EricZimmerman** [comment]
here is your problem

https://github.com/EricZimmerman/KapeFiles/blob/432fd1ca4c7d6901fa2d774ba0fed5c1a037c719/Modules/Apps/NirSoft/NirSoft_FullEventLogView_AllEventLogs.mkape#L8C19-L8C19

you are running a tool that knows how to find logs, but telling KAPE to run that program ONCE FOR EACH evtx IT FINDS.

delete that line and you good

**Comment by salty4n6** [comment]
Excellent.  I wasn't thinking about it like that.  Tested and confirmed it's working as expected now.

~Salty
