### ISSUE TITLE
SFTP transfer for Module operations

### ISSUE THREAD

**Issue by antekirtt** [EricZimmerman/KapeFiles#877]
Hi Eric,

**KAPE version**

KAPE version 1.3.0.2

**Describe the bug**

I'm using a Powershell script in combination to Microsoft MDE Live Response (testing also directly on my laptop) to:
1. Generate a Forensic Triage image using Targets, with the SFTP transfer option to a controlled SFTP Linux server
2. Grab the memory of the host using Modules (MagnetForensics_RAMCapture), with the SFTP transfer option to a controlled SFTP Linux server

The 2 point above are running in 2 different processes not interfering to each other (I'm testing everything separately).
Point 1 is working flawlessly, the Forensic Image is generated using Targets, and successfully transferred to the SFTP server.
Point 2 instead is where there is an issue related to the SFTP transfer (without the SFTP transfer option the memory image is created correctly), giving back, at "Validating connectivity" time the following message:
-  **Error validating SFTP server! Exiting!! Error: Permission denied; Permission denied.**

The 2 processes have the same command line switches for SFTP transfer (this code comes from testing on my laptop), as follows:
1. `--tsource C: --tdest "c:\tools\forensics\test-kape" --target !SANS_Triage --scs xxx.xxx.xxx.xxx --scp 443 --scu test--scpw xxxxx --scd images --vhdx KapeTriage --debug`
2. `--msource C: --mdest "c:\tools\forensics\test-kape" --module MagnetForensics_RAMCapture --scs xxx.xxx.xxx.xxx --scp 443 --scu test--scpw xxxxx  --scd images --zm true`

The second point above have been tested also with `--module JLECmd --mef json` with the same validation error, making me suspecting that the behavior affects module operations as a whole (but of course I might be wrong).

The SFTP auth logs show the opening of the new session, without any issue. The same logs entry applies for both the working and not working operations.

I tried some debugging by giving full permission (on Linux, 777), but I had the same result.

br,
Christian

**Comment by EricZimmerman** [comment]
Can you try the same with kapes built in sftp server? There's a simple sample config on the documentation site

**Comment by EricZimmerman** [comment]
Can you email me temp creds and sftp info so I can do some testing ? Email me at

saericzimmerman gmail

**Comment by antekirtt** [comment]
email sent

**Comment by EricZimmerman** [comment]
ok check your server for stuff. i uploaded to images and a few subdirs of that.

**Comment by antekirtt** [comment]
Found the stuffs under images and the subdirs you created, it worked.

**Comment by EricZimmerman** [comment]
[kape.zip](https://github.com/EricZimmerman/KapeFiles/files/12768755/kape.zip)

yay. try this and let me know

**Comment by antekirtt** [comment]
it works, tested with 2 "only module" (ipconfig and memory) and 1 target.
Thanks for the very fast debug.
