### ISSUE TITLE
Parameterize blob container name for Azure destination

### ISSUE THREAD

**Issue by hkelley** [EricZimmerman/KapeFiles#878]
**KAPE version**
 1.3.0.2

**Is your feature request related to a problem? Please describe.**
If the default `KAPE_data_push_....` container name for Azure is not already parameterized, could it be?   

**Describe the solution you'd like**
A straight parameterized input for the Azure storage account container name to be created.   If this already exists, forgive my ignorance, which -- option is it?    I haven't used the S3 options before, but it appears to have `--s3kp`.

**Describe alternatives you've considered**

**Additional context**
Being able to search/filter for containers in the Azure storage account UI without having to type KAPE_data_push_ every time would be very convenient.

**Comment by EricZimmerman** [comment]
That's all implies within the sas uri, is it not?

**Comment by EricZimmerman** [comment]
In other words you make a container then a uri. From there the data ends up in that sas uri.

**Comment by hkelley** [comment]
Perhaps I'm not using the correct terms.

We have a container in our storage account called `kape-uploads`.   Yes, that is specified in the URI.

What I want to change is the format/text of these "blob folders" in the picture below.   We don't specify that in our URI

```
-AzSasUri 'https://xxxxx/kape-uploads?<SAS_TOKEN_HERE>'
```

![image](https://github.com/EricZimmerman/KapeFiles/assets/8828244/feb1b943-1899-4d94-a36e-d9a04d231d94)

**Comment by EricZimmerman** [comment]
Does that work, to just add that in there and it ends up in a directory?

**Comment by hkelley** [comment]
Dang!  You're right. Sorry about the spam issue.  I didn't realize the paths were so flexible.

```
 --asu "https://xxxx/kape-uploads/aaaa?sp=c.....
```
![image](https://github.com/EricZimmerman/KapeFiles/assets/8828244/c8641ddf-32ad-4f37-a0f1-d69c4316253f)
