### ISSUE TITLE
HELP - My Custom Modules keeps vanishing (!Local)

### ISSUE THREAD

**Issue by secure-cake** [EricZimmerman/KapeFiles#892]
**KAPE version**
KAPE version 1.3.0.2

**Describe the bug**

When I create a custom module, save it to the !Local folder, then later run !!ToolSync (or "sync with Github" via gkape), the custom mkape file is removed. 

**To Reproduce**

1. Create custom mkape file (!EvtxEcmd-Triage.mkape in my example)
2. Save to KAPE\Modules\!Local\
3. I've tested multiple, alternate subdirectories for kicks, same results. 
4. Execute !!Toolsync or "sync with github"
5. Farewell !EvtxEcmd-Triage.mkape file. 

**Expected behavior**

I need a place to safely store custom modules. Based on the KAPE documentation, I understood that to be the !Local folder. If not, will happily take correction/redirection to accomplish persistent custom modules some other way. Thank you!!!

**Comment by EricZimmerman** [comment]
did you change the id?

i cannot think of a situation where the file would be nuked unless you altered an included file and did not change the id.

**Comment by EricZimmerman** [comment]
what does the console say? enable debug or trace as it might show more detail, but start with the above

**Comment by secure-cake** [comment]
I edited an existing module and then performed a "save as" via Gkape, not realizing I needed to change the ID. I changed the ID and re-tested and, unsurprisingly it now works like a charm: custom module retained in !Local folder! 

Thank you for the ridiculously speedy response!

**Comment by EricZimmerman** [comment]
Good to hear
