### ISSUE TITLE
Request for a Remote Access Compound Target to be updated to also pick up SCCM Remote access logs

### ISSUE THREAD

**Issue by TunaTsuna** [EricZimmerman/KapeFiles#906]
Hi! I work in government so I was using KAPE to do some forensic triage collection. Would love to see the Remote Access Compound target to include picking up the files in "C:\Windows\CCM\Logs" for SCCM remote control investigations.

**Comment by AndrewRathbun** [comment]
https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Windows/AssetAdvisorLog.tkape

How about I generalize this Target to include the folder you specified instead of simply the log I once saw malware in? Would that work?

**Comment by AndrewRathbun** [comment]
@TunaTsuna please review the PR and let me know if that'll do the trick, if so, I'll merge and it'll close this Issue

**Comment by AndrewRathbun** [comment]
Also, are you wanting this renamed Target to be added to https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Compound/RemoteAdmin.tkape, as well ?

**Comment by TunaTsuna** [comment]
Hi @AndrewRathbun renaming AssetAdvisorLog.tkape to SCCMClientLogs.tkape and fetching the folder of logs is perfect!

For the RemoteAdmin.tkape, I think a very specific addition could be "C:\Windows\CCM\Logs\CMRcViewer.log" filepath. I briefly looked at the MS documentation and it is a very small addition to the compound that can fetch the default log.(https://learn.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/log-files#BKMK_RCLog).

Thank you for picking this request up so soon as well.
