### ISSUE TITLE
Scaling Issue

### ISSUE THREAD

**Issue by cv-vertex** [EricZimmerman/KapeFiles#945]
**KAPE version**
1.3.0.2

Both target and module options in gKAPE are "bunched" together.  I am unable to view available targets or modules.  

I have attempted adjusting resolution, overriding high DPI settings for both system and application, and adjusting zoom down to 100%. 

![kape screenshot](https://github.com/EricZimmerman/KapeFiles/assets/173709361/09323922-0965-489a-8d11-9dd0b573fca9)

**Comment by EricZimmerman** [comment]
its your system

- too low resolution
- goofy scaling issues
- some small laptop

nothing i can do about it. theres simply too many switches to show it on any smaller of a window

**Comment by AndrewRathbun** [comment]
https://ericzimmerman.github.io/KapeDocs/#!Pages\50-Frequently-asked-questions.md#i-am-experiencing-scaling-issues-with-gkape-how-do-i-fix-this addresses this. Let us know if you have any further questions.

**Comment by AndrewRathbun** [comment]
@EricZimmerman I've pinned the Issue referenced in the above link, so it should be much more visible now.

**Comment by AndrewRathbun** [comment]
This issue is related to https://github.com/EricZimmerman/KapeFiles/issues/614
