### ISSUE TITLE
Failure to transfer Kape output to AWS S3 using Pre-Signed URL

### ISSUE THREAD

**Issue by paweltbucki** [EricZimmerman/KapeFiles#954]
**KAPE version**

1.3.0.2

**Describe the bug**

Trying to upload the output of Kape to an AWS S3 bucket using the pre-signed URL option within gkape.exe. We get the following error: Error: The remote server returned an error: (403) Forbidden.

Example of the command used as follows:

.\kape.exe --tsource C:\Windows\Logs --tdest C:\TEMP --target !BasicCollection,!SANS_Triage --s3url https:// --vhdx kape --gui

The S3 Pre-Signed URL was created using Microsoft Visual Studio 2022 with the AWS toolkit installed. Using the Pre-Signed URL manually outside of Kape works and allows file upload.

**To Reproduce**

1.	Open gkape.exe
2.	Select Use Target Options
3.	Enter Target Source : C:\Windows\Logs
4.	Enter Target Destination: C:\TEMP
5.	Select !BasicCollection and !SANS_TRIAGE
6.	Select Container Option VHDX
7.	Enter base name: kape
8.	Zip container checked
9.	Select Transfer
10.	Select Transfer Options
11.	Select AWS S3 Pre-signed URL
12.	Paste AWS Pre-signed URL into box
12.  Click Execute!
13. Error occurred

**Expected behavior**

We expect that Kape will connect successfully using the Pre-Signed URL and upload its output to the S3 Bucket.

**Screenshots**

![image](https://github.com/user-attachments/assets/11db77ad-296b-4ab1-b007-ae1d93beb0b0)

**Comment by EricZimmerman** [comment]
This has been discussed several times. You have to use v4 for the signature. Search in closed issues for exact details.

**Comment by AndrewRathbun** [comment]
@paweltbucki https://github.com/EricZimmerman/KapeFiles/issues/519

**Comment by paweltbucki** [comment]
Thanks Eric and Andrew for your help and quick responses.
We have tested with the v4 and it works so just have to streamline our process now.
Thanks again.
