### ISSUE TITLE
Enhancement: Make Kape Modules and Targets into YAML/JSON files

### ISSUE THREAD

**Issue by darkquasar** [EricZimmerman/KapeFiles#99]
Kape Modules and Targets are written in a custom format. They could be re-written in YAML/JSON format which is a wide known standard and allow for easier parsing/editing/logging (for example sending the modules to a SIEM instance to identify IR coverage or to ingest them as part of an automation workflow). YAML/JSON would also make this config files more extensible, and easier to add new attributes like ATTK mappings.

**Comment by EricZimmerman** [comment]
They are yamll already.
